### ISSUE TITLE
Proofread the wiki page for user stories

### ISSUE THREAD

**Issue by niccokunzmann** [AllYarnsAreBeautiful/ayab-desktop#11]
[This page](https://github.com/AllYarnsAreBeautiful/ayab-desktop/wiki/2016-05-25-User-Stories---Text) should be read proof by kirstin.

**Comment by chris007de** [comment]
There appeared a second page for [User Stories English](https://github.com/AllYarnsAreBeautiful/ayab-desktop/wiki/User-Stories-English), but it has less content than the German version - which is the one we are definitely working with? (I guess it should be the English one?)

**Comment by niccokunzmann** [comment]
I also think that we should use the English one. Better if we do everything in English from now on.

**Comment by niccokunzmann** [comment]
Done. The English version is complete.
