### ISSUE TITLE
Document specification of .knit format

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#12]
Which data will be stored in a .knit instruction? (Instructions, Motif Data, ...)
How is it stored? (xml, json, ..., human readable, ...)
How to handle machine model specific parameters and instructions (special carriages types, ...)

**Comment by niccokunzmann** [comment]
Some representative DROPs knitting instructions should be converted to .knit format, so one can test out whether the conversions of #2 work.

**Comment by niccokunzmann** [comment]
I would like it to be JSON.

**Comment by niccokunzmann** [comment]
Starting [here](https://github.com/AllYarnsAreBeautiful/knittingpattern).

**Comment by niccokunzmann** [comment]
Converting examples from website into pattern. https://github.com/AllYarnsAreBeautiful/knittingpattern/tree/master/examples

**Comment by niccokunzmann** [comment]
This should be split in several issues, now.

**Comment by niccokunzmann** [comment]
Make a Wiki post that defines what is possible with the format.

**Comment by niccokunzmann** [comment]
https://github.com/fossasia/knittingpattern/issues/57
