### ISSUE TITLE
Choose License

### ISSUE THREAD

**Issue by niccokunzmann** [AllYarnsAreBeautiful/ayab-desktop#13]
Licenses are extremely important. They determine how a community collaborates.
We should choose a free OSS license.

What are your preferences?
Examples:

- MIT - if everything should be possible
- LGPL - if proprietary software is allows to be built with it but our work is still free and modifyable
- GPL if only free software should be built with it.
- [more](https://tldrlegal.com/)

I would vote for something like LGPL in order to allow last-century knitting-software producers to support our format, ...

@kirstin @mariobehling @andz82 @chris007de please choose a license (does not need to be mentioned above)

**Comment by chris007de** [comment]
Currently, the the AYAB GUI Software/Firmware portions are licensed under GPLv3, Hardware schematics and layouts are held under CC-BY-SA 3.0 ("Open-Source Hardware").
My proposal is to keep it like this, and put the upcoming .knit pattern specification (and libraries to parse it) under LGPL (or even better, MIT).
This would enable everybody to use the open .knit data format instantly even for proprietary/commercial usage, whereas improvements on the AYAB Software/Firmware keep flowing back to the community.

**Comment by mariobehling** [comment]
:+1:

**Comment by kirstin** [comment]
I think we should keep the licenses on the software/hardware that was already created.
For the .knit pattern specifications I don't prefer MIT over LGPL or vice versa. We could flip a coin, or someone with a strong opinion on this chooses one of them.

**Comment by niccokunzmann** [comment]
Decided: LGPL
