### ISSUE TITLE
avrdude binary missing when flashing Arduino firmware using the GUI utility

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#136]
Allie Jones:
I wasn't able to use the firmware tool included with the AYAB GUI. I get this error after clicking the "flash" button:
```
DEBUG:root:/usr/local/lib/python2.7/dist-packages/ayab/plugins/ayab_plugin/firmware/avrdude -v -p atmega328p -C "/usr/local/lib/python2.7/dist-packages/ayab/plugins/ayab_plugin/firmware/avrdude.conf" -c arduino -P /dev/ttyACM0 -b115200 -D -Uflash:w:"/usr/local/lib/python2.7/dist-packages/ayab/plugins/ayab_plugin/firmware/hardware_test/uno/firmware.hex":i 
/bin/sh: 1: /usr/local/lib/python2.7/dist-packages/ayab/plugins/ayab_plugin/firmware/avrdude: not found
INFO:root:Error on flashing firmware.
DEBUG:root:message emited: 'Error on flashing firmware.'
```
It looks like the avrdude binary is missing. My guess is that `pip install` isn't installing the binary along with the rest of the files (though I am not very knowledgable about pip)--it exists in the git repo and the zip download from your site, but isn't copied to the dist-packages directory.

I'm running the GUI on Ubuntu 12.04 with Python 2.7.3.

chris007de:
Well, you are right, we were assuming that avrdude is already installed and available in the PATH (i.e. because the Arduino IDE is installed). We will add an info about this dependency in the release notes of the next version!

Holger Schmeisky:
We just stumbled across this too and it would be even more helpful if the UI provided a hint, e.g. "avrdude is missing. Did you install the Arduino IDE?"
Is it feasible to capture the output of subprocess.call and search for occurences of "avrdude: not found" and then display a message accordingly? (in firmware_flash.py:144)

chris007de:
For the reason of not finding avrdude although it's installed: I think this occurs because we call avrdude with an absolute path in the linux version, but as we do not supply avrdude in the PyPi package, it's not found in the firmware folder. Let's change this to call just "avrdude" without any path and expected it as a prerequisite.

Holger Schmeisky:
yup to call it that way is weird :) Arduino IDE seems to set up the PATH correctly, too so just using "avrdude" should be no problem

**Comment by chris007de** [comment]
For Linux, we rely on avrdude available through PATH (tested with avrdude 6.1), for Windows, we deliver our own avrdude.exe plus libusb0.dll and avrdude.conf in the /firmware folder (currently, avrdude 5.11) (tested on Win10 64)

**Comment by rogerw-gh** [comment]
Had this same issue on Ubuntu 16.04 LTS, already had Arduino tools installed, but debug error message hidden by scrolling of error message every second.  Installed avrdude manually, flashing now works.

**Comment by chris007de** [comment]
@rogerw-gh Thanks for this follow-up. Let's add avrdude to the prerequisites on linux.
