### ISSUE TITLE
Choose machine type in ReqStart Message

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#139]
Get rid of necessity to compile different firmware versions for KH930 and KH910, choose version when sending ReqStart Message.

This implies a also a change in the AYAB Firmware and API

**Comment by chris007de** [comment]
We should try to get this into the 1.0.0 firmware.
@Sturla22 has a WIP for the firmware part of this issue: https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/29

Not sure if my work in https://github.com/AllYarnsAreBeautiful/ayab-desktop/tree/v0.9_mono_firmware is still relevant, perhaps it's worth to simply start work on this issue over again.

To Dos:

- [ ] Update AYAB protocol to be able to set machine type from Host
- [ ] Remove unnecessary UI elements for choosing machine type from Firmware widget
- [ ] Add machine type to preferences menu
- [ ] Add machine type to configuration object

**Comment by t0mpr1c3** [comment]
OK, I'll have a go at the UI changes. It's timely, the firmware flash UI needed a few changes anyway.

**Comment by t0mpr1c3** [comment]
#3 implemented here: https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/373

**Comment by t0mpr1c3** [comment]
Firmware changes implemented here: https://github.com/AllYarnsAreBeautiful/ayab-firmware/pull/34
AYAB API v6 documented here: https://github.com/AllYarnsAreBeautiful/ayab-manual/pull/13

Issue can be closed once firmware changes have been tested.

**Comment by t0mpr1c3** [comment]
In the current version of the API, machine type is specified in the `reqInit` message not `reqStart`.

**Comment by dl1com** [comment]
Implementation is done, closing.
