### ISSUE TITLE
Style of documentation

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#14]
This is just to find a common understanding and expectations of documentation.
Currently, the python code of the AYAB GUI is documented with documentation strings, which enables code documentation being generated e.g. with doxygen (https://www.stack.nl/~dimitri/doxygen/manual/docblocks.html#pythonblocks).
Concepts, API and Dev/Build instructions are documented with Sphinx (https://all-yarns-are-beautiful.readthedocs.io from https://bitbucket.org/tian2992/ayab-apparat/src/355e9612c141/software/python/docs/?at=develop).

@niccokunzmann , @kirstin what is your preferred way to do documentation, would you like to change something of this?
At least, we could move to allyarnsarebeautiful.readthedocs.io to keep the naming consistent.

**Comment by niccokunzmann** [comment]
I just heard the talk about Documentation Driven Development form the Django project and I would like to test that out - we are already doing TDD and DDD seems to be even better to get people involved. [Blog](http://niccokunzmann.github.io/blog/2016-06-10/Documentation-Driven-Development).

**Comment by niccokunzmann** [comment]
- [ ] set up sphinx
- [ ] intergrate with travis build (uploads it automatically to pypi)
- [ ] set up on readthedocs

**Comment by niccokunzmann** [comment]
docs are available at http://knittingpattern.readthedocs.io/

**Comment by niccokunzmann** [comment]
travis uploads it automatically http://pythonhosted.org/knittingpattern/
