### ISSUE TITLE
(Re)move knitting progress bar

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#141]
This bar does not contain high priority information, so we might make it smaller, and/or arrange it vertically beside the pattern area

**Comment by Adrienne200** [comment]
Moving the bar to be vertical is a great idea.  Also, please display the row number bigger, so I can read it from a few feet away. The progress bar is good information, and the row number is very important information to have as you knit. But it's OK if it doesn't change in v0.9.

**Comment by chris007de** [comment]
Progress bar has been removed. Let's see if everybody likes it that way.
Otherwise we will add it again :)
