### ISSUE TITLE
Serial port is not released properly when closing the GUI

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#143]
Currently, the serial port is obviously only released when knitting is finished properly. When closing the application using the x button and restarting, the serial port often cannot be obtained

**Comment by chris007de** [comment]
I did not experience that problem for a long time, probably it was more an issue of the operating system. Any comments?

**Comment by oskay** [comment]
I don't think that I've experienced this issue (at least recently) -- however, it is best practice to trap cases like that and force the serial port to close, if we are not already doing so. 

Some discussion of ways to approach that.
http://stackoverflow.com/questions/9249500/pyside-pyqt-detect-if-user-trying-to-close-window
http://stackoverflow.com/questions/24532043/proper-way-to-handle-the-close-button-in-a-main-window-pyqt-red-x

**Comment by Adrienne200** [comment]
I don't think I have ever seen this, how old was the bitbucket comment that it was copied from? I went back and did a brief retry on 0.75 and 0.8 on WinXP.  The symptom would be: Windows, in the middle of knitting, close the GUI by clicking the X in the top right, relaunch, it would fail to find the serial port? Can't get that to happen.
I think you can either close this, or if you're not sure that you have implemented best practices, defer and remove it from the 0.9 milestone.

**Comment by derchrisuk** [comment]
We are actually closing the port twice, hence a message at the end after closing the app that the serial port could not be closed because it is already closed.
I too would say to close this one.

**Comment by chris007de** [comment]
At least, I removed the unhandled exception, let's rest this issue until somebody experiences a blocked serial port again.
