### ISSUE TITLE
Provide User with feed back while flashing

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#145]
Mark Anderson:
After clicking "Flash", there is no indication of "Working..." or "Done" Only indication that something is going on seems to be lack of responsiveness to clicking the top right corner close X.
Actually getting error, but no indication until exit from ayab Application. Dialog box doesn't appear until exiting program.

chris00de:
Proposal: Parse avrdude output for status output (success/failed) Dump avrdude output to ayab logfile for debug purposes

**Comment by jonathanperret** [comment]
For anyone who stumbles upon this while testing AYAB 1.0: the firmware flashing dialog now shows a message box when the flashing is done, but other than that, no feedback is given during the actual flashing operation.
