### ISSUE TITLE
"drivers" directory not present in ayab-windows 0.8 installation

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#147]
The current AYAB Quick-Start guide, found at `http://ayab-knitting.com/software-and-documentation/` asks you to install the ayab-windows software on your computer, and then to install the driver:

>In the case you do NOT have the Arduino IDE on the computer already: 
To install the Arduino Driver, run the following for 64 bit Windows:
`C:\ayab-windows\drivers\dpinst-amd64.exe`
...

However, the `C:\ayab-windows\` directory does not appear to contain a `drivers` subdirectory. 

I would recommend that either 
1. A drivers directory is added there with the appropriate software, or
2. Alternate installation instructions are added there instead, or
3. That the instruction is removed, if no longer deemed necessary.

**Comment by chris007de** [comment]
We should re-check what is definitely necessary to run the AYAB-Software/an Arduino on a fresh Win7/Win10 installation and adapt the instructions/installation package appropriately.

**Comment by chris007de** [comment]
Just tested Firmware flashing on a Win10 installation (inside a virtualbox), there was no need to install any drivers, flashing the Arduino with the avrdude and libusb dll version we currently deliver just worked out of the box.

**Comment by oskay** [comment]
The latest revision of the Adafruit Metro Mini (which we are using on the new shields) has the SiLabs CP210x USB interface. We'll need to check with these as well.

**Comment by chris007de** [comment]
*bump*
How do we want to handle this issue? Do we really want to ship drivers with AYAB? Easiest solution would be to assume a working Arduino environment/driver as a prerequisite.
@oskay How do you think about this?

**Comment by oskay** [comment]
If it's a judgement call, I suggest that (for the time being at least) we _not_ include a "drivers folder", but instead provide clear links to any needed drivers as part of the installation process.

**Comment by chris007de** [comment]
see #196
