### ISSUE TITLE
Include basic Brother patterns in installation package

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#150]
Include the original Brother patterns of the KH-910 in the pattern folder of the installation package

**Comment by oskay** [comment]
Good idea. I have a few test patterns to contribute for the time being.

**Comment by chris007de** [comment]
Added them as a git submodule in the folder "patterns", check if this folder is existing and actually contains files after install/unpacking

**Comment by Adrienne200** [comment]
Where will this folder be on a Mac?

**Comment by oskay** [comment]
I don't think that this is in the mac application right now-- perhaps we could add it to the installer DMG as a separate folder? It could, for example, have prompting graphics/folder to copy it to the downloads folder.

**Comment by derchrisuk** [comment]
Yes, I can add the "patterns" folder as well.

**Comment by derchrisuk** [comment]
For now, this will be included in the App folder
`/Applications/AYAB-Launcher.app/Contents/Resources/patterns/`
I updated the current DMG with this change.

**Comment by Adrienne200** [comment]
Thanks, the files are in the Mac now. If this becomes its permanent home, it will need instructions on how to copy it to somewhere more accessible.
Thank you to whoever scanned in all those Brother patterns. But they are from the 910 not the 930.

**Comment by chris007de** [comment]
@Adrienne200 Thanks for the hint regarding 910/930, I will rename the folder for final release

**Comment by derchrisuk** [comment]
One solution would be that I could either copy them to the Documents folder on first run of the Launcher.
Or add it to the DMG file, with another symlink to the Documents folder.
But then these have to be copied/drag'n'droped manually.

**Comment by derchrisuk** [comment]
At first start on a Mac, the patterns folder will be copied to the Documents folder in `AYAB/patterns`

**Comment by Adrienne200** [comment]
The Brother 910 patterns are now included, so we can close this. Related discussion continuing in #211 about the location of the Mac patterns and where Load Images should point.

**Comment by derchrisuk** [comment]
#211 was for the file dialog, which is fixed now.
Only thing left is to come up with a solution on file location of the actual patterns itself.
They are in different locations on all the 3 OS we build for.
We should come up with a central location for all of them.
My suggestion is the home folder, and a subfolder called AYAB.
Not all OS have the concept of a "Documents" folder.
But all have a home folder.

**Comment by derchrisuk** [comment]
I will close this for now.
At the moment we have the sample patterns available on all platforms, even though in different locations.
These have to be documented.
We can open a new issue if we feel a need for a centralised file location
