### ISSUE TITLE
Count Start Line from 1

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#151]
Currently, the setting for a start line offset is counting from zero, which is probably not convenient for non-engineers.
Start counting from 1.

**Comment by Adrienne200** [comment]
This change is only to the box where you manually set the start row, right? Or does it also affect the row numbering of the knitting itself?

**Comment by chris007de** [comment]
@Adrienne200 It only affects the box.

Tested -> fixed

**Comment by chris007de** [comment]
@Adrienne200 : "The line for starting not at the beginning of the pattern starts at 1 now, but only goes to row 70 of my 71 row image. (might have been like that before)"

**Comment by chris007de** [comment]
As my commit comment says I implemented "Start Line spinbox allowing values from 1 to image height-1", but it should be set to "1 to image height".

**Comment by chris007de** [comment]
Should be fixed with #153 already, tested with several images and I can choose between 1 and height of the image.

**Comment by chris007de** [comment]
Seems to work, closing
