### ISSUE TITLE
Start and Stop needle should automatically be set to the width of the file

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#153]
Open a pattern file that is say 72 pixels wide. The most common use is L36-R36 centered, the software should set the start and stop needles to 36.

**Comment by chris007de** [comment]
Tested -> fixed

**Comment by chris007de** [comment]
@Adrienne200: "I opened a file that is 71x71. It selected 35 - 35, big improvement on always 20-20, but I’d like it to round an odd number up to 36-35 or 36-36."

**Comment by chris007de** [comment]
Seems to work, closing
