### ISSUE TITLE
Display name of current file more prominently

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#156]
On small laptops (Macbook Air, netbooks, etc) one must currently scroll up to see the file name.

I would suggest that the name of the current file loaded be displayed in the title bar of the window, if possible. This will make it easier to see the name of the file. It has a side benefit of freeing up space, where it is currently displayed in the sidebar.

**Comment by chris007de** [comment]
Note to myself:
PyQt handles this not as straight forward as one might think: https://stackoverflow.com/questions/32082231/pyqt-change-dynamically-a-qmainwindow-title

Perhaps it's also ok to show the filename in to bottom status line of the window...let's see

**Comment by chris007de** [comment]
I guess this is ok for now, closing.
