### ISSUE TITLE
MCU with SiLabs USB IC not initializing properly after first time  (Mac)

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#160]
Using an Arduino variant with the SiLabs CP210x IC, the AYAB software appears to work well on both Mac, Windows, and Linux.

However, on Mac only, after canceling and re-configuring, the machine does not appear to init properly -- beeping, etc -- without a hard reset. This behavior is not encountered on Windows or Linux.

Issue reproduced on more than one Mac, and verified to not be present on more than one Windows machine.

Additional data:
* This does not occur on Arduino variants with the FTDI USB IC.
* Restarting the AYAB Desktop software did not have an effect-- only resetting the board.
* Testing on a copy of Ubuntu installed on the same Mac through VirtualBox worked quite correctly. This would appear to imply that the software protocols used in the AYAB Desktop software are the root cause, rather than (say) a deeper issue with the firmware or USB driver.

**Comment by oskay** [comment]
I am _not_ observing this behavior with the 0.9rc4 version on Mac. However, this requires confirmation before closing the issue.

**Comment by derchrisuk** [comment]
Who else can test this?

**Comment by Adrienne200** [comment]
I have been testing this configuration recently, having gotten one of the SiLab EMSL boards a month or two ago. (previously I was using an earlier EMSL with the previous generation of Mini Metro Arduino) I saw this issue from time to time in 0.8, and never so far in 0.9, currently RC8. I think we can close this.

Sometime it takes a few attempts to Cancel, change a setting and get going again, but that's the same on all hardware variants. If I ever get a solid reproduce case for that I'll log it separately.

**Comment by oskay** [comment]
Thank you; that matches my recent experience as well.
