### ISSUE TITLE
Change the name of the Windows log file

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#162]
The log file is called ayab.exe.log.  The problem with that is that by default Windows does not show file extensions, so this looks like ayab.exe. The instructions tell the user to find ayab.exe to launch the program, causing confusion.

**Comment by chris007de** [comment]
@oskay @Adrienne200 Any suggestions on the filename? ayab_logfile.log perhaps?

**Comment by oskay** [comment]
How about ayab_log.txt -- this describes the file well enough that it can be identified without an extension, and text editors will happily open it.

**Comment by oskay** [comment]
Verified; I recommend to close the issue.
