### ISSUE TITLE
Suppress error log file notification?

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#163]
In AYAB 0.8, testing on Windows: After every knitting session, when quitting the AYAB desktop program, there is an unnecessary dialog box that one must close. 

The dialog box is titled "Errors occurred", and says "See the logfile `C:\ayab-windows-0.80\ayab.exe.log' for details".  This dialog appears after every session, including when everything has (so far as the user can see) gone perfectly.

The log file includes useful developer-oriented debug messages, but usually, no actual error messages that are important for the user to see. I would advocate for suppressing the dialog box, if it has not already been removed. 

Reasoning: 

1. The text of the dialog is misleading. Although it says that there has been an error, what it really means to say is that there is a log file. (The log file *may* indicate errors, but it also may not.) I'm attaching an example log file at the end of this issue report.

2. The dialog performs no real benefit. Most users do not need to know that there is a log file. 

3. The dialog box may provide a _negative_ benefit. Since the dialog indicates (often falsely) that there has been an error, this can lead users to question whether something is wrong with their input data, with the knitting procedure, with their hardware, and so forth. Removing this will increase users confidence in AYAB, and reduce the number of incidents of support requests.

4. Since dismissing the dialog box is an additional step for the user to perform, which provides no real benefit, it should be removed in the name of reducing [user interface friction](https://blog.codinghorror.com/reducing-user-interface-friction/).

A typical session log is as follows:

```
DEBUG:root:Loading AYAB from normal package structure.
DEBUG:root:Loading AYAB from normal package structure.
INFO:root:Plugin AYAB activated
INFO:root:Set enabled_plugin as <yapsy.PluginInfo.PluginInfo object at 0x002F0F10> - AYAB
DEBUG:root:called onconfigure on AYAB Knitting Plugin
DEBUG:root:{'inf_repeat': 0, 'start_needle': 80, 'stop_needle': 119, 'filename': 'C:/ayab-windows-0.80/patterns/1x5s/1onX5off@4.png', 'testmode': False, 'machine_type': 'single', 'portname': 'COM27', 'num_colors': 2, 'start_line': 0, 'alignment': PyQt4.QtCore.QString(u'center')}
DEBUG:root:called onknit on AyabPluginControl
INFO:root:API v4, FW v0.80
INFO:root:Notification: Please init machine. (Set the carriage to mode KC-I or KC-II and move the carriage over the left turn mark).
INFO:root:Notification: Please Knit
DEBUG:root:0 0 reqLine: 0 imgRow: 0 indexToSend: 0 [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]
DEBUG:root:0 1 reqLine: 1 imgRow: 1 indexToSend: 2 [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]
DEBUG:root:0 2 reqLine: 2 imgRow: 2 indexToSend: 4 [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]
DEBUG:root:0 3 reqLine: 3 imgRow: 3 indexToSend: 6 [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]
DEBUG:root:0 4 reqLine: 4 imgRow: 4 indexToSend: 8 [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]
DEBUG:root:0 5 reqLine: 5 imgRow: 5 indexToSend: 10 [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]
DEBUG:root:0 6 reqLine: 6 imgRow: 6 indexToSend: 12 [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]
DEBUG:root:0 7 reqLine: 7 imgRow: 7 indexToSend: 14 [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]
DEBUG:root:0 8 reqLine: 8 imgRow: 8 indexToSend: 16 [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]
DEBUG:root:0 9 reqLine: 9 imgRow: 9 indexToSend: 18 [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]
DEBUG:root:0 10 reqLine: 10 imgRow: 10 indexToSend: 20 [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]
INFO:root:Notification: Knitting cancelled
INFO:root:Finished Knitting.
DEBUG:root:Closing Serial port successful.
```

**Comment by chris007de** [comment]
This may be related to http://www.py2exe.org/index.cgi/StderrLog

But it did not occur anymore during my latest tests with PyQt5 on Win10.
If anybody experiences this again, please report here and paste the logfile or some hints which action might caused an exception.

**Comment by oskay** [comment]
Verified, closing issue.
