### ISSUE TITLE
The double-beep at the end of a pattern is not clearly different from the single beep

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#164]
The double-beep was not different enough from the single on the original AYAB, and is even less distinct on the EMSL board. The single sound is slightly longer than before, and merges with the second beep.

**Comment by chris007de** [comment]
We'll test some other settings for the beeps to achieve a better distinguishment between single and double beep.

**Comment by chris007de** [comment]
This issue was moved to AllYarnsAreBeautiful/ayab-firmware#8
