### ISSUE TITLE
Incorrect display on High-resolution Windows screen

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#166]
On a hi-res monitor, the components overlap and the alignment droplist is almost covered. Seen on a new  Microsoft Surface (Pro 4, November 2016) and an Asus PB287 4K monitor. Both Windows10-64. The screenshot is from the Asus, it was worse on the Surface. Fortunately is seems to be possible to get at all the functions, but it’s ugly.

I believe this is a QT issue, that QT didn’t support Hi-res monitors until v5.

<img width="182" alt="hi-res" src="https://cloud.githubusercontent.com/assets/24358225/21254752/65d03d7e-c31c-11e6-800a-a26861030069.PNG">

**Comment by chris007de** [comment]
Let's see how we can reproduce this to be able to fix it...which resolution is set on the devices?

**Comment by Adrienne200** [comment]
It's set to 4Kx2K, 3840x2160.
And Windows 10 is at its default recommended text size of 150%

**Comment by oskay** [comment]
Is migration to QT5 underway?

**Comment by chris007de** [comment]
Can somebody check if this is solved by usage of PyQt5? (current version of v0.9 branch)

**Comment by oskay** [comment]
I think that @Adrienne200 can check this (she is ready to help with beta testing and knows someone who had this issue on their computer) but she'll need a compiled application to test with.

**Comment by chris007de** [comment]
Response by @Adrienne200 on 17/04/15: "I briefly tried the 0.9 version on the other Windows (10-64) machine with a Hi-Res monitor with the same result as the Microsoft Surface, the display is still the same as before; the UI boxes still overlap, though useable. I don’t know what else you did besides upgrading to QT5, but it’s not there yet."

So I guess I have to get a Win 10 HiRes Setup to fix properly.

**Comment by chris007de** [comment]
For the meantime, the application is maximizing on startup so the bottom status bar is visible.
HiRes problems still have to be investigated.

**Comment by Adrienne200** [comment]
I now have direct access to a Microsoft Surface that exhibits this problem, so I can test it more easily.

**Comment by Adrienne200** [comment]
Agree that it's OK to defer this until after 0.9

**Comment by caelor** [comment]
The fix described under the "4k scale error" at https://github.com/x64dbg/PyQt5/wiki/Troubleshooting seems to fix this for me (according to http://doc.qt.io/qt-5/highdpi.html it needs Qt5.6 and above).

The entirety of the fix is to add the following after the imports in ayab.py (line 52 in current head):

    if hasattr(QtCore.Qt, 'AA_EnableHighDpiScaling'):
        QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)

    if hasattr(QtCore.Qt, 'AA_UseHighDpiPixmaps'):
        QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)

Would you like a pull request?

**Comment by chris007de** [comment]
> Would you like a pull request?

@caelor Thanks for finding a fix, I would highly appreciate a pull request :)

**Comment by caelor** [comment]
Thanks. Pull Request #265 refers.

**Comment by chris007de** [comment]
Finally merged pull request #265.
@Adrienne200 please test if the issue is resolved in the next release candidate.

**Comment by derchrisuk** [comment]
http://ayab-debug.s3-website.eu-central-1.amazonaws.com/

**Comment by Adrienne200** [comment]
Unfortunately no, not fixed in 0.95.

**Comment by chris007de** [comment]
Ok, we'll defer this another time, as I have no possibility to recreate the issue on my side.

@Adrienne200 you wrote
> It's set to 4Kx2K, 3840x2160.
> And Windows 10 is at its default recommended text size of 150%

Does it show correctly when you set the text size to 100%?

**Comment by chris007de** [comment]
When starting the application, it shows "AA_EnableHighDpiScaling must be set before QCoreApplication is created.", so I think we have to move https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/1.0.0-dev/src/main/python/ayab/ayab.py#L72-L76 before https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/1.0.0-dev/src/main/python/ayab/ayab.py#L586
(see https://stackoverflow.com/a/57457438)

**Comment by X-sam** [comment]
We believe this is fixed but want the beta testers to confirm.

**Comment by Adrienne200** [comment]
We have user reports that this is fixed in 1.0, user had 0.99-rc4 on windows.
