### ISSUE TITLE
Error with Infinite Repeat when not starting at the first row

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#167]
If you set Infinite Repeat, and tell it to start at say row 4, it gets to the end of the first repeat and fails to beep and continue. Errors in the log.
What should it do?
 - do all subsequent repeats starting at row 4? or
 - only the first repeat from row 4, after that do full repeats from the beginning?
It has to be the second option, do full repeats after the first one. If you really need all the repeats to be shorter, you need to make a new image. The primary reason to be doing this is because you just corrected a mistake and need to restart at row 4, then continue doing full repeats.

[ayab-log-inf-repeat-offset.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/656642/ayab-log-inf-repeat-offset.txt)

**Comment by Adrienne200** [comment]
This is correct now for single bed.  Still failing with the ribber setting, but I can't really test that properly until #148 is fixed.

**Comment by chris007de** [comment]
@Adrienne200 #148 should be OK now

**Comment by Adrienne200** [comment]
It crashes.  Set up the sample as described in #148 (in the comment on May 15th 2017) except set it to start at row 4. So that's ribber, infinite repeat, start at row 4. Everything else at defaults.
Air-knit as usual, watching the two passes per row. When it gets to row 10, it selects 10B then 10A, next should be 1A, but it has crashed in ucrtbase.dll. Event log attached.
This was Win7-64, 0.9RC4.
[Bug 167 DBJ crash.evtx.zip](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1037259/Bug.167.DBJ.crash.evtx.zip)

**Comment by chris007de** [comment]
I fixed it already, but forgot to commit the changes *sigh*

**Comment by Adrienne200** [comment]
Working now on Mac. (0.9 RC4 dated June 10th).

**Comment by chris007de** [comment]
Whoops, closed this one too early, @Adrienne200 wanted to test this one on Windows, too.

**Comment by Adrienne200** [comment]
This works on Windows now too. 2-color, infinite repeat, ribber, start at row X.
Windows 7-64, 0.9 RC5. 
However see the note I added to #148, that I hadn't tried infinite repeat with circular, or with 3-color/ribber, and they both have the issue where infinite repeat goes back to the beginning after half the rows. So I can't confirm how they behave here.

**Comment by Adrienne200** [comment]
This is good now, though see the comment I added to #148
