### ISSUE TITLE
Left image marker is one stitch off

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#168]
The line on the image showing where the start needle is - it is one stitch to the right of where it should be. The left one should be just before the first stitch, the right one just after the last stitch.

![left marker](https://cloud.githubusercontent.com/assets/24358225/21256391/d5aad708-c326-11e6-9a89-b33171d222ba.png)

**Comment by chris007de** [comment]
Should already be fixed with 0d8505408bb5ff84795755bc5dd8eacee328e905

**Comment by chris007de** [comment]
Tested -> fixed
