### ISSUE TITLE
AYAB desktop not opening on Mac 

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#169]
A Mac user reports that they are unable to get the AYAB desktop software to open.

MacOS 10.11 El Capitan
XCode is installed
Homebrew, qt, and libtiff are installed
AYAB DMG downloaded, AyabMac copied to Applications, DMG ejected
Try to open by right-click on icon > select Open from menu

The AyabMac icon appears in the dock for a little while and then goes away, without opening the application.

I would be interested to hear any suggestions for things that we might try.

**Comment by Adrienne200** [comment]
Gatekeeper? System prefs -> Security and Privacy -> General. Change “Allow apps downloaded from” to Anywhere. Try launching. Then set it back afterwards to where it was.

**Comment by boisophieron** [comment]
Hi,
I've the same problem. And my system pref are ok.
I've make a reboot and it doesn't open. I open Ayab by right click on its icon.
If you have an idea, I will be happy!

Sophie

**Comment by oskay** [comment]
Sophie,
Please make sure that you have the Xcode command line tools installed on your computer (`sudo xcode-select --install`) and then make sure that you have both libtiff and qt installed via homebrew. (`brew install libtiff` and `brew install qt`).

If you try again with `brew install qt`, can you please post here what the response is?

**Comment by boisophieron** [comment]
Thanks!!

Yes, I've already Xcode command line tools and homebrew.
But it's true, I have maybe a problem with qt, I've this warning:
Warning: qt5 is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version

Am I doing this?

Many thanks!

**Comment by oskay** [comment]
You are using a different QT version that I am-- mine is QT4 (and AYAB is working), but you have QT5.  Please try the following: `brew remove qt` and then `brew install cartr/qt4/qt` -- this should force it to install the older version.

**Comment by boisophieron** [comment]
It works!!! Many thanks!

**Comment by arte-misia** [comment]
I have the same problem, and the process you suggest to do for me that does not work. 
However, in my case the ayabmac.dmg didn't open at all and seems to be damaged (when i right click on it appear a windows that said "ayabmac is damaged and can't be opened.You must throw it away in the trash bin". I am not an expert so I think that I made some mistake in the installation process. Is there any tutorial or some step by step instruction to install ayabmac.dmg? I hope to have written this in the right place... 
Thanks in advance!

**Comment by oskay** [comment]
@arte-misia: Since this is not a related issue, let's please discuss it in a new topic, here: #170.

**Comment by oskay** [comment]
Confirmed that this is a fix on the second computer with this report as well. as well: Using QT4, not QT5 allows AYAB to launch. (This is not a long-term sustainable situation; QT4 is obsolete. The software should, at a minimum be updated to handle QT5.)

----

**Solution to this issue:**

If you have run into this situation on your computer (AYAB Mac will not open in this particular manner), even if you try opening from the contextual menu (control-click on the AyabMac icon, and select "Open" from the menu there), AND, you used the command `brew install qt` to install QT on your computer, then use the following recipe to get up and running:

`brew remove qt`
`brew cleanup`
`brew install cartr/qt4/qt`
`brew linkapps qt`

----

Side note to AYAB team: Unless you have a better suggestion, I would recommend that we update the Mac installation instructions to read `brew install cartr/qt4/qt` instead of `brew install qt`.
