### ISSUE TITLE
Improve serial protocol for firmware

### ISSUE THREAD

**Issue by niccokunzmann** [AllYarnsAreBeautiful/ayab-desktop#17]
find a way to specify how knitting instructions can be converted to instructions for the machine

**Comment by kirstin** [comment]
Documentation for this can be found here:  
[https://bitbucket.org/chris007de/ayab-apparat/wiki/english/Software](https://bitbucket.org/chris007de/ayab-apparat/wiki/english/Software)

**Comment by chris007de** [comment]
Check also [this wiki entry](https://bitbucket.org/chris007de/ayab-apparat/wiki/english/Software/SerialCommunication) and its implementation in [ayab_communication.py](https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/master/software/python/ayab/plugins/ayab_plugin/ayab_communication.py)

**Comment by niccokunzmann** [comment]
- machine asks: give me line [uint8_t]
- serial answer: line number, 200bit as bit mask
- small and fast to be placed between interrupt
- checksum crc? unused
- needle position:
  - 1 = d
  - 0 = b
laut @andz

**Comment by niccokunzmann** [comment]
added the communication documentation http://ayabinterface.readthedocs.io/en/latest/communication/index.html

**Comment by niccokunzmann** [comment]
@chris007de @andz82 I have the following questions:

1. [ ] Why does the debug message not start with a "0xFF" but with "#" https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/1
2. [ ] How do I know when the debug message ends? is is \r\n or \r\n\r\n ?
3. [ ] what is the [indInit message]( http://ayabinterface.readthedocs.io/en/latest/communication/index.html#m-84) 
4. [ ] indState is not listed https://github.com/AllYarnsAreBeautiful/AYABInterface/blob/communication-content/AYABInterface/communication.py#L89
5. [ ] what is the byte order in indState?

... more to follow, please refer to the numbers when replying

**Comment by niccokunzmann** [comment]
@chris007de @andz82 

waffle deleted my last post.

1. The debug message starts with "#" but in the specification with "0xFF" how to go about this? https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/1
2. cnfInfo [Chris' source code](https://github.com/AllYarnsAreBeautiful/AYABInterface/blob/communication-content/AYABInterface/communication.py#L77) does not match the [specification](http://ayabinterface.readthedocs.io/en/latest/communication/index.html#m-c3)
3. [indState](https://github.com/AllYarnsAreBeautiful/AYABInterface/blob/communication-content/AYABInterface/communication.py#L89) is not listed
4. [in indState](https://github.com/AllYarnsAreBeautiful/AYABInterface/blob/communication-content/AYABInterface/communication.py#L91) what is the byte order of uint16?
5. [indInit](http://ayabinterface.readthedocs.io/en/latest/communication/index.html#m-84) does not occur in the source code and in the sequence diagram - what does it do?

**Comment by niccokunzmann** [comment]
If you like you can add documentation here:
https://github.com/AllYarnsAreBeautiful/AYABInterface/blob/master/docs/communication/index.rst#the-reqstart-message

**Comment by niccokunzmann** [comment]
**About (4)**  
In the [implementation](https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/c236597c6fdc6d320f9f2db2ebeb17d64c438b64/knitter.cpp#L382), the higher order byte comes first.

**About (5) and (3)**  
indInit does not appear in the source code. I assume that indInit means indState. Documentation needs to be adjusted.

**Comment by niccokunzmann** [comment]
**(1) and (2) Resolved**  
I assume I can update the specification according to what is used in the Arduino file.

I also linked [the documentation to the Python implementation and the Arduino source](http://ayabinterface.readthedocs.io/en/latest/communication/index.html#the-reqstart-message) code. #123 could improve linking.

**Comment by niccokunzmann** [comment]
@chris007de @andz82 You can review my assumptions.

**Comment by niccokunzmann** [comment]
New questions:

- (6) What is `initState` in `indState( bool initState = false)` ?
- (7) Do success messages use 0 == false and success != 0 ? I am not sure what [casting a bool to a byte](https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/c236597c6fdc6d320f9f2db2ebeb17d64c438b64/knitter.cpp#L378) does. I would like to assume that success == 1 and all values >1 are invalid values. Before I decide on this, I would like to hear your thoughts. @chris007de 
- (8) What is [cnfTest](https://github.com/AllYarnsAreBeautiful/AYABInterface/blob/communication-content/AYABInterface/communication.py#L81) ?

**(6) Resolved**  
I assume that it means "success" != "0", failure == "0".

**(7) Resolved**  
I assume - because it is safe to assume - that 0 == false and success != 0 for all booleans in true/false messages in the specification. The specification needs to be rewritten, then but the Arduino program can be left untouched.

**(8) Resolved**  
I assume:: cnfTest the message that should be answered to a [reqTest](https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/c236597c6fdc6d320f9f2db2ebeb17d64c438b64/ayab.ino#L119). Both are not in the specification and should be put in the specification. @chris007de If you could write down what the test mode should do, this can be put in the specification.

**Comment by chris007de** [comment]
Your assumptions are mostly correct.
Just some remarks to further clarify things:
- The host waits for a **indState(true)** message before requesting to start the knitting. On startup, the Arduino continuously checks for the initialization of the machine (carriage passed left hall sensor). When this happens, it sends an **indState(true)** to tell the host that the machine is ready to knit. After receiving this message, the host sends a **reqStart** message, which is immediately confirmed with a **cnfStart** message. When **reqStart** was successful, the Arduino begins to poll the host for line data with **reqLine**, the host answers with **cnfLine**. This reqLine/cnfLine happens each time the carriage moves passed the borders given by the Start/StopNeedle parameters in **reqStart**. When the host does not have any more lines to send, it marks the last line with the *lastLine* flag in its last **cnfLine** message.

- reqTest (immediately confirmed by cnfTest) puts the Arduino in a Testmode, instead of a knitting mode (see https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/master/software/python/ayab/plugins/ayab_plugin/ayab_control.py#L605).
Instead, it sends indState messages periodically, containing the sensor and position values.

I will clarify this in the specification today evening

**Comment by niccokunzmann** [comment]
@chris007de thanks. 

- (9) **Resolved** The sequence diagram does not contain the **indState** message. 
- (10) What does indState(false) mean?

**(9) Resolved**  
I assume the indState(true) message should be added to the diagram.

**(10) Resolved**  
**indState(initState)** is called with true/false. Thus, I assume that

- true means the controller has waited for this message and this is the first indState sent
- false means the controller can send this message from time to time to notify the host about changes.
  - This only takes place in the [Opstate_t s_test](https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/c236597c6fdc6d320f9f2db2ebeb17d64c438b64/settings.h#L128). [Then `initState(false)` is called](https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/c236597c6fdc6d320f9f2db2ebeb17d64c438b64/knitter.cpp#L298).

**Comment by niccokunzmann** [comment]
(11) Is it possible to send a `reqStart` again to reset the start and stop needle in case the knitwork is not a rectangle? Will his require to reset the line count?

**Comment by chris007de** [comment]
This issue was moved to AllYarnsAreBeautiful/ayab-firmware#3
