### ISSUE TITLE
Mac DMG file reporting as damaged.

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#170]
@arte-misia wrote in #169:
>[...] In my case the ayabmac.dmg didn't open at all and seems to be damaged (when i right click on it appear a windows that said "ayabmac is damaged and can't be opened.You must throw it away in the trash bin"). I am not an expert so I think that I made some mistake in the installation process. Is there any tutorial or some step by step instruction to install ayabmac.dmg?

**Comment by oskay** [comment]
I believe that this indicates that you have your security settings configured on your computer such that it does not allow "unsigned" third-party software to be downloaded. Please follow [this link](http://www.tech-recipes.com/rx/45404/mac-downloaded-app-is-damaged-and-cant-be-opened-error-solved/) for a step-by-step procedure to disable this setting. 

Once you have successfully installed the AYAB software, you can set your security settings back to their original values.

**Comment by arte-misia** [comment]
Thank you very much! 
As you can see, I am not an expert. 
Tanks again, problem solved!

**Comment by oskay** [comment]
Great-- And, thank you for following up here. (This should be a good record for anyone else who has this issue in the future.)
