### ISSUE TITLE
QT5 migration: Update/fix display_blocking_pop_up 

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#173]
Assuming that pull request #172 is merged, the current status of the QT5 migration is as follows:

* I am able to launch AYAB desktop (via the ayab_devel_launch.py script) and successfully run knitting operations. (Test computer is a Mac, running python 2.7.13.)

* Pop-up dialog boxes are not working. For example, if I try to Configure without selecting a valid serial port, we have a crash at display_blocking_pop_up, with the following traceback:

```DEBUG:root:message emited: 'Please choose a valid port.'
Traceback (most recent call last):
  File "[...]/software/python/ayab/ayab.py", line 327, in display_blocking_pop_up
    QtWidgets.QMessageBox.AcceptRole)
TypeError: information(QWidget, str, str, buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.Ok, defaultButton: QMessageBox.StandardButton = QMessageBox.NoButton): argument 4 has unexpected type 'ButtonRole'
Abort trap: 6
```

The function in question is this:

```    def display_blocking_pop_up(self, message="", message_type="info"):
        logging.debug("message emited: '{}'".format(message))
        box_function = {
            "info": QtWidgets.QMessageBox.information,
            "warning": QtWidgets.QMessageBox.warning,
            "error": QtWidgets.QMessageBox.critical,
        }
        message_box_function = box_function.get(message_type, QtWidgets.QMessageBox.warning)
        ret = message_box_function(
            self,
            "AYAB",
            message,
            QtWidgets.QMessageBox.AcceptRole,
            QtWidgets.QMessageBox.AcceptRole)
        if ret == QtWidgets.QMessageBox.AcceptRole:
            return True
```

I'm afraid that this is a little opaque to me, and does not line up well with code examples that I could find about proper use of QMessageBox. If someone a little more knowledgeable about this could follow up, that would be very helpful.

**Comment by chris007de** [comment]
QMessageBox expects parameters of type "StandardButton" instead of type "ButtonRole".

**Comment by oskay** [comment]
Thank you.
