### ISSUE TITLE
Handle case of no image file selected

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#174]
The `file_select_dialog()` function does not separately handle the case of the user clicking the cancel button.

This can cause a crash of AYAB Desktop in some circumstances. Crash noted on qt5 branch, on Mac, with the following traceback:

```
Traceback (most recent call last):
  File "[...]/software/python/ayab/ayab.py", line 339, in file_select_dialog
    self.load_image_from_string(str(file_selected_route))
  File "[...]/software/python/ayab/ayab.py", line 223, in load_image_from_string
    self.pil_image = Image.open(image_str)
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 2317, in open
    fp = io.BytesIO(fp.read())
AttributeError: 'str' object has no attribute 'read'
Abort trap: 6
```

**Comment by oskay** [comment]
A possible solution would be to follow this approach: http://stackoverflow.com/questions/28594714/error-when-cancel-while-opening-a-file-in-pyqt4

**Comment by chris007de** [comment]
Tested -> fixed
