### ISSUE TITLE
Test pyqt5 branch on Linux

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#176]
Prior to merging the pyqt5 branch, it should be tested on Linux.

Amongst other things, we need to test that the basic functionality is present (dialog boxes, loading files, knitting) and that firmware flashing works properly.

**Comment by chris007de** [comment]
Just tested the pyqt5 branch on Linux (Debian jessie, PyQt 5.3.2), firmware flashing and knitting works.

**Comment by chris007de** [comment]
Merged #179
