### ISSUE TITLE
Test pyqt5 branch on Windows

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#177]
Prior to merging the pyqt5 branch, it should be tested on Windows.

Amongst other things, we need to test that the basic functionality is present (dialog boxes, loading files, knitting) and that firmware flashing works properly.

**Comment by chris007de** [comment]
Just tested the pyqt5 branch on Win10, with python2.7.13 (64bit) and python-qt5 0.1.10 (pip install python-qt5).

Flashing and knitting works (just had to update the avrdude binary, like expected).

**Comment by chris007de** [comment]
Merged #179
