### ISSUE TITLE
Help/about box missing

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#183]
In current state of v0.9 branch, the Help/About box does not work. (reported by @Adrienne200, tested on Windows).

**Comment by chris007de** [comment]
Just had a look, it works under Linux, so either it's a Windows or an issue of the release we built with pyinstaller.
@Adrienne2000, is there any output in the logfile?

**Comment by oskay** [comment]
Appears to be working in today's "Windows 7" version.
