### ISSUE TITLE
AYABInstaller not working on Win7

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#187]
From @Adrienne200:
"The ayabinstaller works on Windows10, but not on Windows7. I tried two Win7-64 machines, both give the same error. One had no Visual Studio, the other had VS2010 and VS2012.

The machine I want to run this on at home is:
Asus Aspire One D270-1824, Intel Atom chip N2600, 1GB RAM
Windows 7-64 Home premium
All updates to April 2017
No Visual Studio.

The install finishes apparently correctly, but AYAB doesn’t launch. Here’s the error (and its the same if I run from an Admin command prompt, or from the non-installer download):
C:\Users\Adrienne>C:\AYAB\ayab.exe
PyInstaller Bootloader 3.x
LOADER: executable is C:\AYAB\ayab.exe
LOADER: homepath is C:\AYAB
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\AYAB\ayab.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(C:\AYAB)
LOADER: Already in the child - running user's code.
LOADER: Python library: C:\AYAB\python35.dll
Error loading Python DLL: C:\AYAB\python35.dll (error code 1114)

I found various links for Python error code 1114, such as 
https://github.com/pyinstaller/pyinstaller/issues/2542
which led here
https://github.com/pyinstaller/pyinstaller/issues/1566
They discuss a bunch of different solutions, this one looks the most promising, what do you think?
https://www.microsoft.com/en-US/download/details.aspx?id=48145"

**Comment by chris007de** [comment]
@Adrienne200: "My experiments didn't make any difference, still the same error.

That was 
https://www.microsoft.com/en-us/download/details.aspx?id=48234
and
https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145

Which may be two different ways of doing the same thing. I also tried running everything as Admin.

The file is there, right in the path where it's looking for it. It's version 2.5.3150.1013  A little reading suggests that Python 3.5 and Windows 7 don't play nicely together, but someone must have a solution. 

It installed on Windows 10 for me too, but I don't have Win10 available at home where my knitting machine is."

**Comment by derchrisuk** [comment]
I can confirm the problem with Win7

**Comment by chris007de** [comment]
The buildsystem (appveyor) is running Windows-2012ServerR2-6.3.9600-SP0.
It does not report any DLLs missing during the PyInstaller run, but we might have to add some files explicitly (see https://github.com/pyinstaller/pyinstaller/issues/1566#issuecomment-282009716).
Several ideas:
- Check C:\AYAB\Python35.dll with dependency walker, perhaps it shows the lacking DLL.
- Install Python 3.5.3-64 on the system and see if it solves the problem (https://www.python.org/downloads/release/python-353/)

When we identified the missing files, we can add them explicitly in the PyInstaller spec.

Might not be directly related, but still worth to be evaluated:
- Check if we still need the x64 version of Python (it was introduced to get PyQt5 running on Windows with Python 2.7), perhaps 32 bit is fine for us now. It still provides better compatibility than 64 bit.

**Comment by derchrisuk** [comment]
Using dependency walker on the python35.dll I get a missing file

`IESHIMS.DLL`

**Comment by chris007de** [comment]
@derchrisuk Could you please post the complete output of depwalker? IESHIMS.dll seems like a false alarm (some common dlls are frequently shown by depwalker as missing, but are not the actual problem)

**Comment by derchrisuk** [comment]
Attached is the full Module Dependency Tree and Module List

[python35.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/976214/python35.txt)

**Comment by Adrienne200** [comment]
The non-installer build ayab-windows.zip (files dated April 29, 2017) gives the same error.

**Comment by chris007de** [comment]
I tried some things:
- Getting back to 32 bit Version of Python (seems to work, so we should stick there).
- On my Win7-32 VM, I got the same error as you, both with deployments from my Win10 VM and appveyor (Server2012).
- Neither installing UCRT (KB2999226) standalone, nor installing a complete Python 3.5.3-32 (which contains UCRT), did change the error.
- Stepping down to Python 3.4 seems to be connected with some effort, as we would have to build PyQt5 (plus SIP) on our own on Windows -.-

What I propose to do next:
- Getting the software to work from source on Win7-32 with Python3.5.3-32 and then do a PyInstaller deployment.
- Check if the deployed ayab.exe works.
- If it does, compare it to the deployment done with Win10/Appveyor. If there are severe differences, I guess we would have to live with separate Deployments for Win7 and Win10 for now.

**Comment by chris007de** [comment]
I tried to run from source on my Win7-32 machine with Python 3.5.3-32, works nicely.
Generating ayab.exe with PyInstaller and running it works as well, and running this binary on Win10 also. Looks like success (for now).
Please check if it works for you also: https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/download/v0.9rc2/ayab-windows7.zip
If yes, I guess we will just go with a manually built version for Win7 for now, as there are plenty of differences between the Win10 deployment and the Win7 deployment.

**Comment by Adrienne200** [comment]
The new 0.9-RC2 now launches on Win7-64. I can open an image and start to knit, the log shows it sending the correct sequence down from the software. 
But the needles selected are random, no relation to the pattern.  0.9-RC1 still works on this machine with 0.8 firmware, selecting the correct needles, so there's nothing wrong with the knitting machine or the EMSL hardware.  Is there new firmware needed for RC2? I tried resetting the Arduino, and reloading the 0.8 firmware.

**Comment by chris007de** [comment]
Ok, thanks.
No new Firmware is needed for v0.9. I guess the "random" needle selection is caused by the changes introduced to be compatible with Python3 (https://github.com/AllYarnsAreBeautiful/ayab-desktop/commit/f5090829e0e7531b24d0a8a401bdb8bf2895b133), so I guess we have to dive into that again.
But as the Win7 compatibility has been restored, I'll close this issue and open another one for the new issues *sigh*
