### ISSUE TITLE
Needles not correct with Python 3

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#188]
Likely because of the changes done on the serial interface code done to be able to run with Python3 (https://github.com/AllYarnsAreBeautiful/ayab-desktop/commit/f5090829e0e7531b24d0a8a401bdb8bf2895b133), the correct sending of line data has been broken.
Investigate how to correctly mask data/send the bytefield in Python3 (I guess ayab_communicatio.py Line 114 or ayab_control.py Line 321)

**Comment by oskay** [comment]
Working with today's "win7" build, the simple patterns that we use for test appear to be working correctly.

I am unsure whether the issue is fixed or whether I simply am not following the correct procedure to reproduce the issue.

**Comment by chris007de** [comment]
Thanks! Sounds promising, but let's wait for @adrienne200 to verify also.

**Comment by Adrienne200** [comment]
Needle selection is basically working again now, with the 0.9 RC2 from May 9th. But see issue #190.
