### ISSUE TITLE
Selecting "Smart resize" option causes crash

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#189]
Tested with today's "windows 7" build, on Windows 7.

To reproduce: Open image, select "smart resize" from menu.

**Comment by chris007de** [comment]
I propose to remove the "Smart Resize" option for now, until we refactor the image handling.

**Comment by oskay** [comment]
Still seeing this crash in the current version (rc4).

**Comment by chris007de** [comment]
I guess this was still related to the python3 migration, fixed the module imports, please re-test in the next rc

**Comment by Adrienne200** [comment]
Are you still planning to just remove Smart Resize from the menu, pending a redesign of this feature? 
Windell has incorporated a stretch-factor into his image-dithering utility, reducing the need for resizing in the AYAB app.

**Comment by Adrienne200** [comment]
On Mac (0.9 RC4 dated June 10th) the Smart Resize box now shows, no crash. But does it do anything useful?  I'd still vote to remove it, pending a broader discussion of what (if any) image manipulation should be in the AYAB GUI.

**Comment by oskay** [comment]
I concur that it's best to remove the menu option until/unless it's an active, usable option.

**Comment by chris007de** [comment]
Removed the menu option.
