### ISSUE TITLE
Long delay before the beep

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#190]
Using the 0.9 RC2 dated May 9th. This did not happen with RC1.
The needle selection is back to normal now, (see #188) but with a long delay before the beep on the right. The behavior is similar to case #154 (moved to firmware case #9) which can still happen too. But now the long delay before the beep is primarily on the right, and every right-hand row. Crossing the turn mark doesn’t help much, still a delay. (Which is different from #154, where crossing the turn mark always fixes it.)

This wasn’t so noticeable with a very narrow piece, but the attached 60pixel file shows it. Set it up as usual, single bed, 2 colors. The beep happened as usual on the left, but took ages (10-20 seconds) on the right. 

(I was also using this test file to look carefully at the row numbering - row 1 brings forward 1 needle per repeat, row 2 is 2, etc. That part is good now, so long as you wait for the beep.)

![rownumbertest 60 x 20](https://cloud.githubusercontent.com/assets/24358225/25905455/f0e56fea-3556-11e7-9fdc-ad072a00349b.png)

**Comment by Adrienne200** [comment]
I mischaracterised this a bit, it's not a delay, it's about taking the carriage all the way to the right hand end. The left edge of the carriage has to clear needle R90 or later, then it'll beep. Not just the magnet past the turn mark, it's acting like it thinks the right needle setting is at 90. But the settings match the file, at R30-L30.

**Comment by Adrienne200** [comment]
Only happens with files of about 60 pixels wide and up. A 50 pixel file L25-R25 is fine, the right beep happens as usual. I tried a 60 and a 68, both needed the carriage taken out well past the right turn mark. (My hardware works normally with a previous AYAB version)

**Comment by chris007de** [comment]
Probably another issue with the Python3 migration...the software might not send the Start/Stop needle correctly to the Arduino (https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/python3/ayab/plugins/ayab_plugin/ayab_communication.py#L80).
Later today, I can test with a machine and hopefully fix it.

**Comment by chris007de** [comment]
Indeed, Python3 needs some different preparation of data before sending over serial.
Should be ok again.

**Comment by Adrienne200** [comment]
Good now. This is not happening in 0.9 RC4.
