### ISSUE TITLE
Rotating an image is broken

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#191]
0.9 RC2 on Windows7-64
Open up the Stirnband sample.
Choose rotate left or right from the menu.
Previously the display would flip from 160-20 to 20-160 and show the image vertically.
Now the display stays at 160-20, and only shows a small piece of the image.
![stirnband rotated 2](https://cloud.githubusercontent.com/assets/24358225/25988184/e8d5a3fa-36ab-11e7-902b-eeca1ce7ad5c.PNG)

**Comment by chris007de** [comment]
This works on Linux...could you please paste the log output?

**Comment by oskay** [comment]
I can confirm the issue.  Nothing telling in log.

```
DEBUG:root:Loading AYAB from normal package structure.
DEBUG:root:Loading AYAB from normal package structure.
INFO:root:Plugin AYAB activated
INFO:root:Set enabled_plugin as <yapsy.PluginInfo.PluginInfo object at 0x030AD7B0> - AYAB
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'sRGB' 41 1
DEBUG:PIL.PngImagePlugin:b'sRGB' 41 1 (unknown)
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 54 20
DEBUG:root:rotating image
DEBUG:root:rotating image
DEBUG:root:Closing Serial port failed. Was it ever open?
```

**Comment by chris007de** [comment]
So I guess you both tested on Windows7 with the 0.9-rc2 version?
I will try to reproduce...
