### ISSUE TITLE
Crash in ucrtbase.DLL

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#192]
It crashed for no apparent reason. I was air-knitting using the ribber setting when this happened, but I did the same steps again afterwards and no crash happened.
[crash.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/995389/crash.txt)

![crash](https://cloud.githubusercontent.com/assets/24358225/25988320/648aa59a-36ac-11e7-81ef-cdaf4c5c71ed.PNG)
[crash event.evtx.zip](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/995394/crash.event.evtx.zip)

**Comment by chris007de** [comment]
Which OS? 32 bit or 64 bit?
What did the ayab.log.txt say?

**Comment by Adrienne200** [comment]
Win7-64. On an Acer D270 with only 1GB of RAM.
I forgot to pinch off the log, but this section has to be it, it was the only place that isn't followed by Knitting Cancelled. The file was the attached smiley. But it didn't fail again, I think this was a "random" crash, not something specific I was doing.
![smiley 1 24x30](https://cloud.githubusercontent.com/assets/24358225/26006205/67c4c9c2-36f0-11e7-8ddb-5b5f8a3ae432.png)
[log.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/997293/log.txt)

**Comment by Adrienne200** [comment]
I haven't seen any random unexplained crashes recently, currently at RC11. (This was logged at RC2 or RC3)
