### ISSUE TITLE
Improve some details of Mac application (v0.9rc4, Mac)

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#195]
I'm really glad to have the Mac version up and running-- and apparently free of macports. That's *really* nice.

I will list several issues of relatively low importance here. Reducing the number of these would help the AYAB application to feel a little more polished and professional. I will start these in a single issue, but it may make sense to break them out into separate issues later (or to add similar issues here later).

The application executes as though two separate applications are running. One appears in the dock as "AYAB" (this one is the log window), the other as "Python" (this one is the AYAB desktop application).

(A.) For clarity, I would suggest that we might rename the virtual applications that appear in the dock. For example, to change the log window name to "AYAB Launcher" and the application to "AYAB" or something similar.

(B.) The launcher window (possibly a platypus app?) should ideally close at the same time as the AYAB application quits. This may be as simple as deselecting the "Remain running after initial execution" option if this is in platypus.

(C.) The application should have a custom mac icon. (Is there a suitable square AYAB application icon out there somewhere?)

(D.) The AYAB application also says "Python" in its menu bar label. (Likely a duplicate of issue (A).)

(E.) The "About AYAB" menu item works correctly, but is called "About python" in the menu.

**Comment by derchrisuk** [comment]
(A.) That is because at the end all it does is to start a python process with the AYAB source.
There might be a way to modify the Dock title.

(B.) Correct, for debug purposes it is still enabled to be left open, to grab tracebacks.

(C.) One could use the About logo and make an icon version of it.

(D.) Same as (A.)

(E.) Same as (A.)

**Comment by chris007de** [comment]
Ages ago, @andz82 made an icon for AYAB, I guess we could use this as an "official" icon for our software (but I have no idea about the required format and size):

![knoil](https://cloud.githubusercontent.com/assets/1631996/26529885/4c5eaae6-43c9-11e7-956f-22e5ac34dfc3.png)

**Comment by derchrisuk** [comment]
Fixed `C`, `D` and `E`.
`B` can be disabled once all errors have been fixed.
For `A` I'm still looking for a working solution.
So far I was not able to change the Dock tile name of the actual Python process running the GUI, just the title bar.

**Comment by oskay** [comment]
Some possible directions on (A) discussed here:

https://stackoverflow.com/questions/7827430/setting-mac-osx-application-menu-menu-bar-item-to-other-than-python-in-my-pyth

https://stackoverflow.com/questions/5047734/in-osx-change-application-name-from-python

**Comment by derchrisuk** [comment]
I just replaced the Mac image with a new version.
Tested it on fresh 10.12 install.
This one will now show correctly in the Dock.
Also changed the names, there is now AYAB-Launcher and AYAB.
At the moment the AYAB-Launcher still stays open if you exit AYAB.
If we can confirm all is well I can remove this feature, and it is good to be merged into the new release.

**Comment by oskay** [comment]
Stalled on launch for me. Possible bad link in there: `/Users/derchris/.pyenv/shims/python3` 

```
/Applications/AYAB-Launcher.app/Contents/Resources/script: line 46: /Users/derchris/.pyenv/shims/python3: No such file or directory
running app
/Applications/AYAB-Launcher.app/Contents/Resources/script: line 49: AYAB.app/Contents/MacOS/main.sh: No such file or directory
```

**Comment by derchrisuk** [comment]
Yes, there was a static link.
Fixed and uploaded new version.

**Comment by oskay** [comment]
Opens and runs well now. 

I have not done a thorough test.  Once we're good and happy with it, I should be able to sign the app & DMG for distribution.

**Comment by derchrisuk** [comment]
I will create a new issue for signing the App and the DMG once we have a final version ready.
