### ISSUE TITLE
Crash when initializing to knit 3-color DBJ

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#197]
Win7-64, 0.9RC4

Using the Mushroom 3-color sample, which works in version 0.8, 0.9RC4 crashes while doing the initial triple-beep.

Image attached.
Setup is all default except Colors=3 and Machine Type=Ribber.
Configure, Knit, move the carriage over the left turn mark. The triple-beep sounds (or sometimes doesn't complete) and then crashes.

![mushroom](https://cloud.githubusercontent.com/assets/24358225/26667332/79860176-4659-11e7-974b-ee7b5e1481e2.png)

[3-color ribber 0-9RC4.evtx.zip](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1043844/3-color.ribber.0-9RC4.evtx.zip)

[ayab_log.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1043871/ayab_log.txt)

**Comment by chris007de** [comment]
@Adrienne200 Should be working again in next RC

**Comment by Adrienne200** [comment]
Doesn't crash on Mac RC4 dated June 10th.  Can't verify yet on Windows.

**Comment by chris007de** [comment]
If this one works on Mac, it should do on Windows, closing.
