### ISSUE TITLE
0.9/RC4 doesn’t launch on Mac

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#198]
I have a MacBookAir (11-inch early 2015, El Capitan.) Neither of the 0.9 RC4 Mac dmg’s launch. 
Attached is the output from the current one, downloaded June 11th. 
The previous one didn’t launch either. If the current log doesn’t point us in the right direction, I did save some earlier logs too, I can dig them up and see if there’s anything useful.
I have run the First Aid in Disk Utility. (There’s no actual permissions repair in Disk Utility any more, but I assume it is included in First Aid.)

LOG1: It’s saying there’s a permissions error with sip.
So I drilled in and gave myself R/W privileges, that helped, but not all the way there yet.

LOG2: Almost there, but now it says that its own resources folder is Read-Only. I drill in there and there is no Ayab.app, just a folder called AYAB, see screenshot. And this folder’s permissions seem to be R/W but it says I can only Read, and won’t let me edit the permissions, even after unlocking.
Both logs in one file, attached.

[AYAB Mac log files.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1066746/AYAB.Mac.log.files.txt)
![ayab folder permissions](https://user-images.githubusercontent.com/24358225/27014296-030994e0-4eab-11e7-8c1e-e1bad3736af3.png)
![ayab-launcher has no ayab app](https://user-images.githubusercontent.com/24358225/27014297-031291da-4eab-11e7-99c6-d68f57c8c5cd.png)
![sip so was read-only](https://user-images.githubusercontent.com/24358225/27014298-03158714-4eab-11e7-9d0d-9d99e9917f51.png)

**Comment by oskay** [comment]
@Adrienne200 Please copy the file into the main Applications folder on your computer and try again.

**Comment by Adrienne200** [comment]
Yes, that was it, thanks. For this test version, Ayab-launcher needs to live in the Applications folder; I should have thought to try that.

**Comment by oskay** [comment]
Great. (It will also be the case that the final version will not work unless moved off of the DMG.)

**Comment by derchrisuk** [comment]
Was there a Link to the Applications folder after opening the DMG?
I can include a background which shows a blue arrow pointing to the folder.

**Comment by oskay** [comment]
There was not such a link.

(I have a utility (Drop DMG) that can bundle the DMG with with the background, click-through GPL license, and properly signed. I'd be happy to manage that process here, but it's something that would have to be done manually for each significant release, not as part of the build process.)

**Comment by derchrisuk** [comment]
I actually added a link with the last uploaded version.

**Comment by oskay** [comment]
Ah! Please allow me to suggest editing the tag or text when you upload a new release (0.9rc4.1?) so that the rest of us will know to grab the new version. :)

**Comment by derchrisuk** [comment]
But know.
For some reason Github did not upload the updated DMG
