### ISSUE TITLE
Hang when trying to flash the firmware on Mac.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#199]
0.9 RC4, AYAB-launcher dated June 10th 2017
MacBook Air El Capitan
910 (also tried 930)
EMSL board
(This works on 0.9 RC4 Windows.)

Plug in the hardware, launch AYAB.
Tools, Load Firmware
910, Uno, 0.8
Flash.
Nothing happens, no flashing light on the Arduino.
Force quit.
From the log:

<after the usual launch stuff>
running app
Loading AYAB from normal package structure.
Loading AYAB from normal package structure.
Plugin AYAB activated
Set enabled_plugin as <yapsy.PluginInfo.PluginInfo object at 0x111f508d0> - AYAB
/Applications/AYAB-Launcher.app/Contents/Resources/ayab/plugins/ayab_plugin/firmware/avrdude_mac -p atmega328p -c arduino -P /dev/cu.SLAB_USBtoUART -b115200 -D -Uflash:w:"/Applications/AYAB-Launcher.app/Contents/Resources/ayab/plugins/ayab_plugin/firmware/uno/kh910_uno_0-80.hex":i 
b'dyld: Library not loaded: /usr/local/opt/libusb/lib/libusb-1.0.0.dylib\n'
b'  Referenced from: /Applications/AYAB-Launcher.app/Contents/Resources/ayab/plugins/ayab_plugin/firmware/avrdude_bin\n'
b'  Reason: no suitable image found.  Did find:\n'
b'\t/Applications/AYAB-Launcher.app/Contents/Resources/ayab/plugins/ayab_plugin/firmware/./lib//libusb-1.0.0.dylib: mach-o, but wrong architecture\n'
b''
b''
b''
b''
b''
b''
b''
<Repeated thousands of times>
b''
b''
b''
/Applications/AYAB-Launcher.app/Contents/Resources/script: line 49:  2900 Terminated: 15          AYAB.app/Contents/MacOS/main.sh

**Comment by oskay** [comment]
I've just tested on my computer and it appears to be working well. It appears to be the case that it is finding the right file (already installed) on my computer but not yours. 

I'm attaching a different version of the library here. Please download, unzip, and copy the resulting file (libusb-1.0.0.dylib) to:

/Applications/AYAB-Launcher.app/Contents/Resources/ayab/plugins/ayab_plugin/firmware/lib

You can open this location in the finder by selecting from the menu Go > Go to folder... and pasting that location there.

Then, please try again. If it still fails, we may need to replace one or more additional files.

**Comment by Adrienne200** [comment]
Still fails.

**Comment by oskay** [comment]
Can you please post the current log?

**Comment by derchrisuk** [comment]
I don't have the HW to test on my side.
There might be a chance that I can manage to plug in a "dummy" i.e. an Arduino and test with that.

**Comment by Adrienne200** [comment]
Log attached.
[bug199 RC5.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1090493/bug199.RC5.txt)

**Comment by oskay** [comment]
@Adrienne200 It looks as though either the file didn't get replaced or maybe you upgraded to the new version-- I'll have to try some tests here to see if I can reproduce this on another computer.

**Comment by derchrisuk** [comment]
I think the problem here is the architecture.
The lib might be i386, but x86_64 is required.
I can try to build a new DMG which has a x86_64 version of this lib included.

**Comment by oskay** [comment]
That's correct.

**Comment by derchrisuk** [comment]
This should be fixed by a4e587a2161961a2e27ac9ecef53beb5d8568174
Here is a new libusb-1.0.0.dylib. Unzip.
This need to go into the following folder:
`/Applications/AYAB-Launcher.app/Contents/Resource/ayab/plugins/ayab_plugin/firmware/lib/`
Will be included in the next RC.
[libusb-1.0.0.dylib.zip](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1092161/libusb-1.0.0.dylib.zip)

**Comment by Adrienne200** [comment]
Not yet. The wrong architecture error has gone, but now I seem to be missing an ftdi library

running app
Loading AYAB from normal package structure.
Loading AYAB from normal package structure.
Plugin AYAB activated
Set enabled_plugin as <yapsy.PluginInfo.PluginInfo object at 0x112487438> - AYAB
/Applications/AYAB-Launcher.app/Contents/Resources/ayab/plugins/ayab_plugin/firmware/avrdude_mac -p atmega328p -c arduino -P /dev/cu.SLAB_USBtoUART -b115200 -D -Uflash:w:"/Applications/AYAB-Launcher.app/Contents/Resources/ayab/plugins/ayab_plugin/firmware/uno/kh930_uno_0-80.hex":i 
b'dyld: Library not loaded: /usr/local/opt/libftdi0/lib/libftdi.1.dylib\n'
b'  Referenced from: /Applications/AYAB-Launcher.app/Contents/Resources/ayab/plugins/ayab_plugin/firmware/avrdude_bin\n'
b'  Reason: image not found\n'
b''
b''

**Comment by derchrisuk** [comment]
Yes, I can confirm this now.
Will have a look at what else the avrdude_mac app requires to start.

**Comment by derchrisuk** [comment]
I have tested this now on my side, and flashing seems to work now.
The changes are included in the latest RC6.
Can you please test on your side?

**Comment by oskay** [comment]
I don't think that I have access to RC6.

**Comment by derchrisuk** [comment]
It will be ready in the next hours.
We are including some more fixes in it.

**Comment by Adrienne200** [comment]
Works now, thanks.
0.9 RC6, MacBook Air on El Capitan
