### ISSUE TITLE
implement bit sequence out of pattern for ayab arduino

### ISSUE THREAD

**Issue by niccokunzmann** [AllYarnsAreBeautiful/ayab-desktop#20]

**Comment by chris007de** [comment]
Check [cnfLine Method of ayab_control.py](https://bitbucket.org/chris007de/ayab-apparat/src/a4fc476fb1cbce721c3514fe87bee1f4cca2068e/software/python/ayab/plugins/ayab_plugin/ayab_control.py?at=master&fileviewer=file-view-default#ayab_control.py-369) for the current implementation

**Comment by niccokunzmann** [comment]
#45

**Comment by niccokunzmann** [comment]
- [ ] create a class for handling kh910
- [ ] see which instructions can be made by kh910
- [ ] create a instruction stream for each row
- [ ] convert instruction stream to bit sequence
- [ ] use serial protocol to talk to ayab shield
- [ ] split the knitting pattern from this
