### ISSUE TITLE
Sign OSX App and DMG of Final v0.9

### ISSUE THREAD

**Issue by derchrisuk** [AllYarnsAreBeautiful/ayab-desktop#201]
This issue is a placeholder for signing the final v0.9 for OSX once done.

- [ ] Sign OSX App
- [ ] Sign DMG image

**Comment by oskay** [comment]
Draft here, using 0.9rc5 -- for testing signing.

(Uploading here since I don't have permission to do so elsewhere, and a zipped DMG, because DMG files aren't allowed as file attachments.)
[AYAB-0.9-DMG-ZIP.zip](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1098819/AYAB-0.9-DMG-ZIP.zip)

**Comment by derchrisuk** [comment]
Both DMG and App are signed.
The Window of the DMG is a little bit too small though at the bottom.

**Comment by oskay** [comment]
Just tested on another computer here-- enlarged bg at the bottom and repackaging right now. :)

**Comment by oskay** [comment]
Second draft of final packaging. (Still with RC5)
[AYAB-0.9.zip](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1098873/AYAB-0.9.zip)

**Comment by derchrisuk** [comment]
Still too small on my side.

**Comment by oskay** [comment]
Can you please post a screenshot of what the window looks like? 
(There is no fixed standard of how the finder displays these.)

**Comment by oskay** [comment]
Trying one more here--

**Comment by oskay** [comment]
Draft 3.
[AYAB-0.9.zip](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1098895/AYAB-0.9.zip)

**Comment by derchrisuk** [comment]
This one is ok.

**Comment by oskay** [comment]
Great-- here it is with the 0.9rc6 and the same packaging scripts
[AYAB-0.9rc6.zip](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1099091/AYAB-0.9rc6.zip)

**Comment by derchrisuk** [comment]
Do we actually need to sign both the DMG and the App?
And can we automate the process?
I don't know if a Signing key just for AYAB can be created.

**Comment by oskay** [comment]
There are separate signatures for the two-- without a signature, some users will get a "damaged" message about the DMG. 

Automating the process would require that the person building it would have a Mac, and have a certificate granted by a paying member of Apple's developer program installed on their computer. I maintain an active subscription, and could potentially grant a certificate to someone else on the team (it signs as Evil Mad Science LLC), or the team could get its own dedicated developer account to do it. 

I'm certainly happy to run the script to sign the latest release here, whenever needed.

**Comment by oskay** [comment]
Actually, looks like I *might* be able to create a separate AYAB signing key-- looking into it.

**Comment by oskay** [comment]
Here is a signed version of rc8.

[AYAB-0.9rc8.zip](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1118231/AYAB-0.9rc8.zip)

**Comment by derchrisuk** [comment]
We have now a OSX running which we use for the CI tests/builds.
Ideally we would like to get it signed during that same process, so we don't have to worry about it.

**Comment by oskay** [comment]
Is this running on your computer?

**Comment by derchrisuk** [comment]
I made a VM of my own OSX for the CI setup.
It is only accessible to Gitlab as a CI runner and only I have access to the actual VM.

**Comment by oskay** [comment]
Let's talk by e-mail; should be able to set something up.

**Comment by oskay** [comment]
[AYAB-0.9rc9.zip](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1123392/AYAB-0.9rc9.zip)

**Comment by Adrienne200** [comment]
Mac signing seems to be working. This could be closed, or left open until final.
