### ISSUE TITLE
AYAB-Launcher.app shows version number 0.8 in the finder

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#202]
As of 0.9rc5 (Mac).

**Comment by derchrisuk** [comment]
Shows with current version on my side.
But this is with the last test version.
Try with this one: https://ayab-debug.s3.amazonaws.com/AYAB-OSX-v0.9rc5-48-g8515aa0.dmg

**Comment by oskay** [comment]
Possibly bad link.

**Comment by derchrisuk** [comment]
No, but I clear the S3 before any new build, and there had been 2 since I posted ;)

**Comment by oskay** [comment]
Link gives me an S3 "The specified key does not exist." error.

Here is what the finder info shows on the last RC5 version posted in releases:
<img width="408" alt="screen shot 2017-06-23 at 12 34 50 pm" src="https://user-images.githubusercontent.com/1009180/27497627-7b20ba94-5810-11e7-9131-3f33b5ceafb0.png">

If that's fixed by now, please feel free to close this.

**Comment by derchrisuk** [comment]
Check with the latest 0.9rc6, it has the fixes included.

**Comment by oskay** [comment]
0.9rc6 has this fixed.
