### ISSUE TITLE
Fix remaining Firmware Issues

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#203]
- [x] The double-beep at the end of a pattern is not clearly different from the single beep https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/8
Test some other settings for the beeper with EMSL and Arduino Shield

- [x] The last row of a pattern is selected twice. https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/7
Re-check if needles are reset after last Line. Alternative solution: Send blank line after last line (would have the flexibility to decide wether all-on or all-off has to be chosen, depending on single or DBJ operation)

- [x] #219

**Comment by chris007de** [comment]
Fixes implemented, will integrate a new firmware release candidate in the next GUI release candidate.

**Comment by Adrienne200** [comment]
The two firmware fixes are good, at least enough to expand the testing and get some more opinions.
