### ISSUE TITLE
Crash if you select 3-color and circular

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#205]
Logging separately from #204 because I don't think there's any need to ever implement circular with more than 2 colors. 
Select 3-color, circular, any pattern (with or without 3 colors) set it up and start. After the carriage crosses the turn mark for the first time, crash.
Can the UI prevent this combination?  If you have selected 3 or more colors, gray out the option for Circular?

**Comment by chris007de** [comment]
Now yielding a warning when more than 2 colors are configured with circular. Not the prettiest solution, but it does the job.

**Comment by Adrienne200** [comment]
RC11, now gives an error message that circular only supports 2 colors
