### ISSUE TITLE
Play sound files in case of start, end of line, end of knitting

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#208]
Instead of using the beeper, play sound files on the computer to indicate the start of knitting, end of line and end of knitting to the user.

**Comment by chris007de** [comment]
https://pypi.org/project/playsound/

**Comment by chris007de** [comment]
playsound library causes problems on Windows and macOS, try https://simpleaudio.readthedocs.io/en/latest/

**Comment by chris007de** [comment]
Currently (https://github.com/AllYarnsAreBeautiful/ayab-desktop/commit/6ede3488f6c03b10574e950c1f8c05774707c785), we are only playing a sound when starting and when finished.
I know from some users who do not like the hardware beeper (or it is too quiet), so being able to have an (optional) sound on each line would be desirable, I would say.

**Comment by t0mpr1c3** [comment]
Looks like we have a new line sound ready to go :) It is a bell sound like an old-fashioned typewriter.

I can implement this easily enough. We already have a "quiet mode" setting that turns off all the sounds, do we need an extra setting just for the new line sound?

**Comment by chris007de** [comment]
> I can implement this easily enough. We already have a "quiet mode" setting that turns off all the sounds, do we need an extra setting just for the new line sound?

I think it is not necessary to control this separately. So when not quiet, I'd play all sounds (start, newline, finish). Let's see how many people get annoyed by this ;)

**Comment by t0mpr1c3** [comment]
That sounds fine to me.

I might create a new thread to play the sounds to avoid blocking the UI thread while sounds are playing.
