### ISSUE TITLE
GUI needs to list the 0.9 firmware

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#209]
0.9RC8, Mac and Windows.
A new 0.9 firmware exists, but there's no way to select it from the Load AYAB Firmware page. It should add "0.9 (latest)" to the top of the list.

**Comment by chris007de** [comment]
Forgot to commit the changes...*sigh*. Will be included in the next RC...

**Comment by chris007de** [comment]
Here's the commit: 7880e1d1159dbcb9b1c14eafb61787f347be51f7, so new firmware should come in the next RC

**Comment by Adrienne200** [comment]
0.9 firmware flashing is available, Mac and Windows, RC9.
