### ISSUE TITLE
Crash if you try to open a file that isn't a supported image

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#212]
0.9RC8
Load Image File lets you select any kind of file to open as your image. If you select any unsupported file type such as a text file, it crashes.   In 0.8 it just did nothing, ignored the selection.
It should either:
 - error if you select an unsupported file type. Doing nothing is OK too, an error is better.
 - gray out all files except the supported types

**Comment by chris007de** [comment]
We can tell the file dialogue to only show files of certain type(s), so we should probably limit it to *.png.
Any other file formats which should be shown?
Some people are working with JPG, but because of the compression it was never recommended to do so.

**Comment by oskay** [comment]
Do the jpg compression artifacts cause glitches?

A file name filter will need to support .png and .PNG, as well as (if jpeg is included) .jpg, .JPG, .jpeg, and .JPEG.

**Comment by derchrisuk** [comment]
I will include this with the changes in #211

**Comment by derchrisuk** [comment]
I modified the file dialog to only allow png, jpg,jpeg, both lowercase/uppercase

**Comment by Adrienne200** [comment]
Please include .bmp/BMP as well. MSPaint has the ability to save as Monochrome bitmap, which works with AYAB, I have tried it. I think I saw it suggested in someone's tutorial.
The AYAB GUI currently opens gif and tiff as well. I haven't tried making a simple black/white image for either of these, seems unlikely that anyone is using them.

**Comment by derchrisuk** [comment]
I have added bmp/gif/tiff to the file dialog

**Comment by Adrienne200** [comment]
Please include .tif/.TIF as well, just to be complete.

**Comment by Adrienne200** [comment]
.tif/.TIF included now in RC11, Mac and Windows
