### ISSUE TITLE
The sample patterns

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#213]
Some ideas to tidy up the samples in the Patterns folder:
 - the Space Invader is 800x800 and not knittable as it stands. What size did you intend it to be?
 - Please add my attached “Triangles_60x10.png”  I may use it in a future tutorial.
 - I find it useful to to include the size in the name. Suggested changes:
 testPatterns1@40Wide.png to TestPattern_40x40.png
 testPatterns1@96Wide.png to TestPattern_96x40.png
 testPatterns1@200Wide.png to TestPattern_200x40.png
 mushroom_36x36.png
 stirnband_160x20.png 
 uc3_30x15.png
 space_invader(whatever size and type it ends up)

![triangles_60x10](https://user-images.githubusercontent.com/24358225/27818733-c49d1c88-604b-11e7-8924-fa93c5894138.png)

**Comment by derchrisuk** [comment]
I added your triangles sample, and made filename changes to all but spave_invader.jpg, until we found the correct size info.

**Comment by chris007de** [comment]
space invader was a test file for the resizing option (which was removed for now), so we either remove the pattern or just resize it to a sensible value.

**Comment by Adrienne200** [comment]
Contents of the patterns folder looking good in RC10.
Here's a suggested new version of the invaders.
![space_invader_33x32](https://user-images.githubusercontent.com/24358225/27991329-fd019074-6427-11e7-97eb-0a9860c605c3.png)

**Comment by chris007de** [comment]
Added the your new version (eba53cb6ff1d4263d4cbfa83086179c0ce2c3be2).
I guess that's all for now, closing,
