### ISSUE TITLE
Win7 install version not showing in Programs and Features

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#214]
See screenshot; it says PACKAGE_VERSION.
<img width="817" alt="win 7 install version" src="https://user-images.githubusercontent.com/24358225/27819355-b0ef2a8e-604e-11e7-8152-c2cc39ab4a66.PNG">

**Comment by derchrisuk** [comment]
5efa4d335b7878f5d26c42ee06b699a8f20a62de will fix this.
Included in the next RC

**Comment by Adrienne200** [comment]
OK now, fixed in RC9 on Win7-64
