### ISSUE TITLE
XP install?

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#215]
I think you said that the 0.9 release will be 64-bit only for Windows? The only 32-bit Windows that I have available to check that on is XP. So I ran the RC8 Win7 installer. The install completed apparently correctly, but unsurprisingly the product doesn't launch. Neither does the non-install version.
It would be nice if the installer could check if it's on an unsupported system (32-bit, and/or XP) and not install. Though it is named Win7 to give you a clue that it might not work  on XP.

![win7installonxp32](https://user-images.githubusercontent.com/24358225/27819737-6f084478-6050-11e7-8903-1b1ef2102c62.PNG)

**Comment by derchrisuk** [comment]
I added a check to the install script.
But I don't have a Win XP to test with.
Can you try and test with the attached version?
[AYAB-Windows7-0.9rc8-6-g129dcb5-Setup.exe.zip](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1123226/AYAB-Windows7-0.9rc8-6-g129dcb5-Setup.exe.zip)

**Comment by derchrisuk** [comment]
I received a XP VM, and can confirm install not possible on Windows XP anymore.

**Comment by derchrisuk** [comment]
Fixed in 129dcb53f77f5c1757a3ab02b814987f802dfcc1

**Comment by Adrienne200** [comment]
Can't install the Win7 or Win10 installers on XP-32, with message. Closing.
