### ISSUE TITLE
Log file reports wrong firmware version

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#219]
0.9RC11
I have flashed the 0.9Rc1 firmware, but the logfile reports it as version 0.8.

Windows:
DEBUG:root:called onknit on AyabPluginControl
INFO:root:API v4, FW v0.80
INFO:root:Notification: Please init machine. (Set the carriage to mode KC-I or KC-II and move the carriage over the left turn mark).
INFO:root:Notification: Please Knit

Mac:
called onknit on AyabPluginControl
API v4, FW v0.80
Notification: Please init machine. (Set the carriage to mode KC-I or KC-II and move the carriage over the left turn mark).

**Comment by chris007de** [comment]
Fixed with https://github.com/AllYarnsAreBeautiful/ayab-firmware/commit/d736336f91c8c987261cb50dd6ab9729ddf51410
