### ISSUE TITLE
Crash if the image is outside 200 needles

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#220]
0.9RC11 Mac and Windows
Open a wide image and arrange the selection asymmetrically so that the image extends beyond the end of the available 200 needles.  For example the stirnband image set to Orange 10 and Green 80. All default settings
Click Configure, Knit
Move the carriage over the left turn mark.
Crash.
![image over the end](https://user-images.githubusercontent.com/24358225/28237463-24a7ba5a-68f5-11e7-9e3a-a2503ab6b3c5.png)
[Log image over edge.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1150157/Log.image.over.edge.txt)
[Crash image over edge.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1150159/Crash.image.over.edge.txt)

**Comment by chris007de** [comment]
Fixed, will be included in rc12

**Comment by Adrienne200** [comment]
No crash now, verified in RC11Post5.
