### ISSUE TITLE
Clean Mac install takes two attempts, then works.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#221]
I installed Sierra (10.12.5 from the App Store) on an external drive. Booted from that drive and unmounted the main drive. So this is a brand new OS, no Xcode, no extras of any kind.
Launched AYAB-0.9rc11-osx-signed2.dmg, dragged to Applications.

(First try of Ayab-launcher, I had forgotten to connect to Wifi, no surprise that that didn’t get far)
Connect to the internet.
Ayab-launcher

It gave these 4 lines of log and sat there doing nothing for almost 10 minutes:
xcode-select: error: unable to get active developer directory, use `sudo xcode-select --switch path/to/Xcode.app` to set one (or see `man xcode-select`)
install xcode command line tools
Software Update Tool

However during those 10 minutes the App Store told me that there’s an update waiting, one of which is the XCode Command Line Tools. I was about to cancel out when the Ayab-launcher log came back to life and installed the command line tools on its own. (Possibly the long delay was only because this was a brand new OS install, an already-in-use system might have found the command line tools immediately?)
 Then it continued with the rest of the downloads and installs; pyenv looks to have succeeded, pip not so much, and errors from there ending in fail, see attached log1.

However, I launched again, and this time it successfully upgraded pip from 7.1.2 to 9.0.1, PyQT5 then worked, and the AYAB GUI launched.

So I can't easily tell whether other new users without XCode etc will have this two-step behavior or whether it will work first time.
[AYAB install log2 success.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1150890/AYAB.install.log2.success.txt)
[AYAB Mac install log1 fail.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1150891/AYAB.Mac.install.log1.fail.txt)

**Comment by derchrisuk** [comment]
From the log, it looks like it did not fail because of the Xcode install.
I can see timeouts for pip install.
Also just tried a fresh install on my end, which seem to work on first try.
Unless this is reproducible I would say this was just a one-off.

**Comment by oskay** [comment]
I had a user try it out and was unable to launch after two tries.

```
​xcode command line tools already installed
pyenv already installed
install python
pyenv: /Users/RedactedUserName/.pyenv/versions/3.5.0 already exists
/Users/RedactedUserName/.pyenv/libexec/pyenv-version-file-write: line 21: .python-version: Read-only file system
/Volumes/AYAB-0.9 1/AYAB-Launcher.app/Contents/Resources/script: line 38: /Users/RedactedUserName/.pyenv/shims/pip3: No such file or directory
[...] (Many other lines of failure)
```

**Comment by derchrisuk** [comment]
From that bit it looks like he tried to run the app from the DMG:

`/Volumes/AYAB-0.9 1/AYAB-Launcher.app/Contents/Resources/script: line 38: /Users/RedactedUserName/.pyenv/shims/pip3: No such file or directory`

**Comment by derchrisuk** [comment]
Let me see if I can add some kind of check that it will never try to start from the DMG.

**Comment by oskay** [comment]
Actually yes-- We caught that and asked him to try again from the Applications folder. (Sorry-- copy and pasted from the wrong message).

He was apparently, even after copying it to /Applications and running it from there, getting the same failure message `/Users/RedactedUserName/.pyenv/shims/pip3: No such file or directory`

**Comment by derchrisuk** [comment]
I just added a check and waiting for the build to finish.
The problem is related to running it from the DMG, some required files could not be written to link to the installed python.
Deleting the .pyenv folder and running it again from the /Applications folder should fix this.
But I would wait until I have the changes build into a DMG first.

**Comment by oskay** [comment]
Interesting. If that is the case, then yes, I suspect that ensuring it's not on the DMG is a good approach.

**Comment by derchrisuk** [comment]
Here is one with the check included

http://ayab-debug.s3-website.eu-central-1.amazonaws.com/AYAB-0.9rc11.post2-osx.dmg

**Comment by Adrienne200** [comment]
I'm getting a 404 error from the above link

**Comment by derchrisuk** [comment]
We had more builds since I posted this. Go to the root folder of the URL, there you can find the latest release

**Comment by Adrienne200** [comment]
I tried this again yesterday with AYAB-0.9rc12-Mac-Signed.dmg.  Essentially the same experience, it failed first time, succeeded second time. Though I now have a better understanding of what it's doing about the XCode Command Line Tools, and why. See #234 for a suggestion to improve the flow for that part.
My other failure was a timeout; my wireless is being very slow this weekend so that might be all that's wrong.

**Comment by Adrienne200** [comment]
So it turns out that if I wait a really really long time, the install does work. The lack of feedback made me think it was hung, when in fact it was doing a long slow download. Other people's experience should mostly be faster.
See comment today in #234, I think it's OK to ship it as is and see what improvements we need for next release.
