### ISSUE TITLE
Write Release notes for 0.9

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#222]
here's my first draft, please comment/edit.
Release notes 0.9:
 - Mac install is signed, Windows still isn’t. 
     Mac users can set Gatekeeper to “Mac App Store and identified developers”
 - Windows is 64-bit only. [what else to say?]
 - Mac install no longer requires Xcode and Homebrew
 - you can now flash the firmware from Mac
 - firmware flash on Windows now works if there is a space in the path
 - on opening an image it selects needles to match the image width
 - Smart Resize has been removed from the menu.
 - only allowed to open files that are images
 - The sample patterns are in C:\AYAB\Patterns on Windows, and in /Documents/AYAB/patterns on Mac
 - Infinite Repeat in DBJ (ribber) and Circular now knits all the way through the file before restarting
 - the row numbering has changed. There is no row zero any more. The row number shown is the one being _selected_ (or about to be selected)  not the one being knitted.
 - boards that use the SiLabs driver no longer hang when you cancel on Mac. There should rarely be any need to reset the Arduino.
 - you can now enter a start line greater than 256
 - an underlying technology called QT has been updated. This has no visible effects but lays the groundwork for the next phase, and for fixing display issues on some Windows machines.

Firmware fixes 0.9:
 - in non-infinite-repeat knitting, the long beep to warn that you’re at the last row is more obvious.
 - in non-infinite-repeat knitting, the last row is no longer selected twice. Previously if you canceled the carriage pattern settings at the correct time all was well but it was too easy to accidentally repeat the last row. Now, the long beep that signifies the end of the image comes _before_ you knit the last row: the new rule is to keep knitting in pattern until no more needles are selected, which is one row _after_ the last sound.

**Comment by chris007de** [comment]
We already have a Changelog/Release Note as work in progress:
https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/v0.9/CHANGELOG.rst
Feel free to add the points you mentioned above, I just added writing permissions to the repository for you.
