### ISSUE TITLE
Should not install on 32-bit Windows

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#223]
It lets you install on 32-bit Windows. But as it's a 64-bit app it fails to launch. I have tried Vista-32 and 10-32. 
Launching from the shortcut gives the usual blue Windows dialog, or the launch at the end of the install gives the other error shown in the Windows10 screenshot.
Maybe the fix for #215 wasn’t quite the right approach, instead of checking for XP, it should check for 32 bits?
Or there may be enough pushback that it becomes necessary to build 32-bit after all.
![rc11 on 10-32](https://user-images.githubusercontent.com/24358225/28452774-11c07b6c-6da9-11e7-872d-398451ee79b7.png)

**Comment by derchrisuk** [comment]
The Windows 7 version is actually 32bit. Only the Windows 10 is 64bit only.
I can add another check for Windows Vista.
But we should not put too much effort into this, as we already say Win7/10 only.

**Comment by derchrisuk** [comment]
Just added an additional check for Windows Vista

**Comment by derchrisuk** [comment]
Here you can find a test version with the additional check included:

https://ayab-debug.derchris.eu

**Comment by Adrienne200** [comment]
I verified that 0.9-RC12 is rejected from installing on Vista, and does install and launch on Win7-32. (I didn't install Arduino drivers and hook up an AYAB board on 7-32, but that should just work.)
