### ISSUE TITLE
Update ayab-knitting.com

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#224]
- [x]  - on the Ayab Interface page http://ayab-knitting.com/ayab-interface/ please remove the sentence starting "Attention:" which claims that European users of the EMSL board will need to buy a power supply. Not true, the one supplied is multi-voltage. They only need a shape-changer plug.
- [ ]  - the current Mac install instructions are buried under Shield Software but Windows is on a different page, Mac needs to move as well as be changed.
- [ ]  - the instructions end with “follow the instructions on the screen” For the first experience, better to step the user through a bit further.
- [x]  - a Links page would be good, the ones that are there are a bit scattered. With notes pointing out places where older tutorials are out of date.
- [ ]  - update the FAQ
- [ ]  - most or all of the site should be in German as well as English.
- [x]  - update the "How to get AYAB" page. Include the open-source EMSL info, and list the various sources where you can currently purchase ready-mades and kits. 
- [ ] This page could include a picture of each one with its name/source, and a link to its Arduino driver. Including the ones from Thinkstack and Tinkersoup that are no longer available.

**Comment by chris007de** [comment]
I made your post a checklist, so we can better track progress.
If you want to, I would really appreciate your help for this issue. In case you are not used to work with git/github, it's possible to work directly on the homepage in the browser using the github editor:
https://github.com/AllYarnsAreBeautiful/allyarnsarebeautiful.github.io 
Changing existing pages is pretty easy this way. In case you want to add new pages or change the structure/menu, just call for help :)

**Comment by chris007de** [comment]
@Adrienne200 I did some changes and ticked them of in your initial post: https://github.com/AllYarnsAreBeautiful/allyarnsarebeautiful.github.io/pull/2
I also merged them to master so you see which structural changes I made -> http://ayab-knitting.com - how do you like them?

**Comment by jonathanperret** [comment]
I'd like to close this issue — at the very least it now would apply to https://github.com/AllYarnsAreBeautiful/allyarnsarebeautiful.github.io and not this repository (I realize there were not as many separate repositories back when it was created).

It is also very old and most of the remaining items seem either not relevant anymore, or could be entered as individual issues. In any case, there doesn't seem to be anything here that should be a blocker for the 1.0 release.

@Adrienne200 @dl1com what do you think?

**Comment by dl1com** [comment]
Fine for me, let's close and continue in the other repo with up to date issues.
