### ISSUE TITLE
Display the row number larger

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#225]
While knitting it is often important to know which row you're on, but the row number is in a small font at the bottom of the screen. It would be nice to repeat it larger somewhere so it can be read from further away without having to peer at the screen.  
I'm not sure where I want to put it, needs some design thought. Maybe just a larger font where it is is enough, but I don't want to make that lower bar take up any more space.

**Comment by Adrienne200** [comment]
The larger number is good in the new Continuous Status mode in 0.95. But (as of post61) that mode is still slow and would only be used for occasional troubleshooting, I'd still like to see a larger number visible in normal mode. 
I'm not sure where to put it though. Is it possible to right-justify the Knit and Cancel buttons and leave space to repeat the row number in a larger font? It would need to be enough space for 3 digits, maybe 4. But it doesn't need to include the second half, for row 12 of 20 it can just show 12, not the /20 part. Though if we localize those buttons they may need more space?

**Comment by chris007de** [comment]
I would propose to simply increase the font size of the progress notification below the pattern window, as the right-hand area of the GUI is already fully packed with information.

**Comment by Adrienne200** [comment]
This now says Line 1/10 in nice large font.  Much better, but if you could change it to say "Row" rather than "Line" please. Knitters call them rows, even though they are lines in the file.

**Comment by chris007de** [comment]
https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/v0.95rc4

**Comment by Adrienne200** [comment]
Good now. 0.95RC4
