### ISSUE TITLE
Include the sub-row numbers and color-changer button number when knitting DBJ

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#226]
When knitting DBJ and circular it take multiple passes to knit one row. Currently it just displays the same row number until that row is finished.
It would be nice if it displayed which pass you're on, and which color-changer button.
For example, 3-color DBJ which takes 6 passes per row:
 Row - Pass - CC
1 - 1 - 1
1 - 2 - 1
1 - 3 - 2
1 - 4 - 2
1 - 5 - 3
1 - 6 - 3
That's rather cryptic, maybe there's a better design, but that's the idea.

**Comment by Adrienne200** [comment]
This is mostly implemented now, (0.95 RC3) thanks. But some ideas:
 - when using single bed, it says "Color A/B" all the time. While this is true, I'm not sure it adds much value. Most people do the majority of their knitting single bed, and having this text sitting there all the time might be considered clutter. Don't know, maybe it's OK.
 - it's very very useful with DBJ though. At first I found the time where it changes color to be a bit of a surprise, but actually it's correct, and essentially the same as Brother did it. For 2-color classic, as you turn around on the right it switches to telling you which color comes next, and stays there until you're on the right again. So on the way into the changer it's telling you which button to press, and as you leave you can confirm that you did it right. Perfect, exactly what I wanted.
But on the various 3-color DBJ's, it often says "Color: Blank" This has some value for understanding what the selection is doing (and probably for debugging) but I think this field should be only for the actual color that will be changed next, (or has just been changed to) regardless of whether it's doing a selection or non-selection row. While testing I often had to wait for the next beep to confirm which color I needed next.
 - at the very beginning of a piece, it sometimes displays the wrong color. I think it doesn't know for sure which color until after the triple-beep when you start. Better to display nothing than a random color left over from the last pattern. Maybe it could clear this field when you click Configure? Or if it does know, can it display it sooner?

**Comment by chris007de** [comment]
> - when using single bed, it says "Color A/B" all the time. While this is true, I'm not sure it adds much value. Most people do the majority of their knitting single bed, and having this text sitting there all the time might be considered clutter. Don't know, maybe it's OK.

Let's remove it.

> - it's very very useful with DBJ though. At first I found the time where it changes color to be a bit of a surprise, but actually it's correct, and essentially the same as Brother did it. For 2-color classic, as you turn around on the right it switches to telling you which color comes next, and stays there until you're on the right again. So on the way into the changer it's telling you which button to press, and as you leave you can confirm that you did it right. Perfect, exactly what I wanted.
But on the various 3-color DBJ's, it often says "Color: Blank" This has some value for understanding what the selection is doing (and probably for debugging) but I think this field should be only for the actual color that will be changed next, (or has just been changed to) regardless of whether it's doing a selection or non-selection row. While testing I often had to wait for the next beep to confirm which color I needed next.

Removing this also.

> - at the very beginning of a piece, it sometimes displays the wrong color. I think it doesn't know for sure which color until after the triple-beep when you start. Better to display nothing than a random color left over from the last pattern. Maybe it could clear this field when you click Configure? Or if it does know, can it display it sooner?

Clearing this field when clicking configure for now, displaying it sooner (before starting to knit) will be possible after refactoring of image handling.

**Comment by chris007de** [comment]
https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/v0.95rc4

**Comment by chris007de** [comment]
https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/v0.95rc4

**Comment by Adrienne200** [comment]
Verified on RC4, these two items are good now: 
single bed no longer says Color A/B
no color is displayed before the triple-beep.

However, not quite there with the removal of the word Blank. All the Blanks are gone, but they've been replaced with the previous color where I think it should be the next color.   I think I want it to always change during the beep on the right, so that on the R-L pass as you enter the color changer you are ready to press the correct button, and as you leave the color changer you can check that you did it right.
The color shown is always correct while you're actually in the color-changer, but the point where it changes is inconsistent. With 3 and 4 colors, some prompts only shows for one pass, another for 3.
For example, 4-color Classic.  When changing to A or D, the next prompt happens on the right as I want it. Changing to B or C you have to wait until you’re already on the left before it tells you what to change to.

And Circular. It previously said  A, Blank, A, Blank. Now it's A all the time, should alternate colors A and B. (Not critical, hardly anyone uses circular and you just alternate colors so it's not difficult to track on your own.)

**Comment by chris007de** [comment]
Printing the next color instead of the previous color is easier after refactoring of the image processing, therefore I'd say we go with the current implementation and improve it in the next version.

**Comment by chris007de** [comment]
@t0mpr1c3 Please close if this is fixed by #334

**Comment by t0mpr1c3** [comment]
It's not fixed yet, single bed fair isle still displays "Color A/B".
