### ISSUE TITLE
AYAB Desktop crash on macOS when disconnecting USB while knitting

### ISSUE THREAD

**Issue by jessedonaldson** [AllYarnsAreBeautiful/ayab-desktop#228]
I stopped knitting by disconnecting the USB cable without clicking "Cancel Knitting" first, and AYAB crashed.  Crash report attached.  
This is on macOS 10.12.6.

[AYAB Crash.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1202888/AYAB.Crash.txt)

**Comment by chris007de** [comment]
duplicate of #194
