### ISSUE TITLE
Delay the row-beep to help ensure correct color changes

### ISSUE THREAD

**Issue by still-optimistic** [AllYarnsAreBeautiful/ayab-desktop#233]
I knit a 50x750 pattern today in DBJ... about 600 rows in, I failed to pull the carriage quite far enough for a correct color change (I think).  It took the yarn, but it popped out as soon as it hit a needle... and I proceeded to drop 3/4 of my stitches.  This was a good learning experience, I guess, but it also gave me an idea:

When using a color changer, could we delay the "row beep" when knitting to the left until the carriage has moved far enough that the new yarn will not be dropped?  I think this would help me ensure correct color changes, and avert tragedies like the one today.

**Comment by chris007de** [comment]
Some questions:
- Is there "the" color changer or are several models which we would have to distinguish?
- Can we just assume the usage of a color changer if somebody knits with more than two colors in DBJ or would it be something which the user should configure manually?
- When in the correct position for color changing, is the carriage still locked into the carriage belt or does it leave to carriage belt when moving it to the far left into the color changer? If it has no more contact to the belt, we cannot identify the current position anymore.

**Comment by still-optimistic** [comment]
There are different color changers available... mine is the KRC-830.  I'm not sure if the carriage positions would be different for the different models.  It's possible.  Also, the maximum distance would be different depending on how many colors were in use.  The KRC-830 is a 4 color changer, and you have to pull the carriage past the color you are selecting... but I usually only use two colors, so it's not necessary to push it all the way back.  But it is _safe_ to push it all the way back, so maybe that's the best choice anyways.

**Comment by still-optimistic** [comment]
It seems okay to me to assume the use of a color changer when knitting even with two colors in DBJ (because the ribber sinker plate won't handle two colors, right?).   But... I am a novice.  Maybe other folks have their own ways to switch the colors without a changer.

At least when switching between the two frontmost colors on the KRC-830, the carriage does not disconnect from the timing belt.  I'm not sure if it can reach the 4th color without disconnecting.  I'll check.

**Comment by still-optimistic** [comment]
The third color is pretty close to the  end of the timing belt, and the fourth is just past it.  So, I guess the best we could do is to delay the beep to the end of the timing belt?  Or maintain different targets depending on the number of colors in use.  Is it more trouble than it's worth at that point?  Maybe I should just form better habits. :-)  I'd be interested to hear if anyone else thought this might be helpful.

**Comment by chris007de** [comment]
I guess this would need some investigation with an actual color changer. I am not 100 % sure whether we could reliably identify each color position, but it's worth a try.
Please understand that we have some other issues to work on for the next version which have higher priority. But this issue is filed and we will come back to it when other things have been solved.
Sooner or later, we want to add a needle position display in the software - when this is the case, you could support us by testing if it shows distinct needle positions when moving the carriage to the different positions in the color changer - if yes, then implementing the feature you requested should not be a big deal.

**Comment by still-optimistic** [comment]
That is totally fine -- I filed this issue because I thought it seemed like an interesting idea.  I agree other things are higher priority.

**Comment by Adrienne200** [comment]
This was an interesting discussion, but I don't think it would be right to implement the idea. It's fine the way it is, it's up to the user to manage the color changing themselves and moving the row beep wouldn't help much, if at all.
