### ISSUE TITLE
Improve the feedback during Mac install and launch

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#234]
During first launch, which is where most of the install happens, the text in the log file is too sparse in some places, too verbose in others, and contains some unnecessary errors and warnings.
To see all this, repeat the test with an external drive or separate clean partition, described in the first few lines of #221

  [ ] if you don’t have Xcode installed, the very first thing in the log is this error message, but it is apparently not really an error, the install continues  anyway.
​xcode-select: error: unable to get active developer directory, use `sudo xcode-select --switch path/to/Xcode.app` to set one (or see `man xcode-select`)

  [ ] if you don’t have the Xcode Command Line Tools already, the installer hangs at “Software Update Tool”  I suppose it is trying to tell you that you have to go to the App Store, the Update tab, and install the Command Line tools from there. Note that this includes accepting a license agreement with Apple, so it needs UI to do it.
 Instead of the cryptic “Software Update Tool” it could say “Please cancel and quit, and use the Update tab of the App Store to install the Xcode Command Line Tools. Then restart AYAB-Launcher”

  [ ] when installing pyenv, it shows this warning. The user does not need to do anything, would be better if you could suppress the warning.
WARNING: seems you still have not added 'pyenv' to the load path.
Load pyenv automatically by adding
the following to ~/.bash_profile:
export PATH="/Users/sierraexternal/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

 [ ] during downloads and installs there’s no progress indication, on a slow connection it's hard to tell that it’s doing anything

 [ ] pyobjc is too verbose, has dozens of entries almost identical to each other, such as these.
      Collecting pyobjc
    Downloading pyobjc-3.2.1.tar.gz
  Collecting pyobjc-core==3.2.1 (from pyobjc)
    Downloading pyobjc_core-3.2.1-cp35-cp35m-macosx_10_6_intel.whl (493kB)
  Collecting pyobjc_framework-AVKit==3.2.1 (from pyobjc)
    Downloading pyobjc_framework_AVKit-3.2.1-cp35-cp35m-macosx_10_6_intel.whl
  Collecting pyobjc_framework-AVFoundation==3.2.1 (from pyobjc)
on and on.

  [ ] then when pyobjc is almost finished, it tells us about everything it installed, starting like this, and much more. Though maybe this is OK as it's just once.
Installing collected packages: pyobjc-core, pyobjc-framework-Cocoa, pyobjc-framework-Quartz, pyobjc-framework-AVKit, pyobjc-framework-AVFoundation, pyobjc-framework-Accounts, pyobjc-framework-AddressBook, pyobjc-framework-AppleScriptKit, pyobjc-framework-AppleScriptObjC, pyobjc-framework-ApplicationServices, pyobjc-framework-Automator, pyobjc-framework-CFNetwork,

During every launch:
 [ ] a whole slew of “Requirement already satisfied:”  That’s fine for most components, each one reports once. But when it gets to pyobjc, there are dozens of lines almost the same, very cluttered.

 [ ] Every launch ends with these last two lines. It would be nice to suppress the second line, so it finishes by saying that AYAB has been activated, without the geeky detail.
 Plugin AYAB activated
 Set enabled_plugin as <yapsy.PluginInfo.PluginInfo object at 0x113d27588> - AYAB

**Comment by derchrisuk** [comment]
Most of the items are debug stuff.
And most of that is 3rd party, which we have no control over how it is doing debug.
But we can think about redirecting all of it to a different log file, for the setup phase.

For the Xcode Developer Tools.
Just tried on my VM, where I reset to the snapshot I did right after the initial install, so no tools installed at all.
Here is a snippet of how it went:

```
derchriss-Mac:~ derchris$ git
xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
derchriss-Mac:~ derchris$ touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
derchriss-Mac:~ derchris$ PROD=$(softwareupdate -l | grep "\*.*Command Line" | head -n 1 | awk -F"*" '{print $2}' | sed -e 's/^ *//' | tr -d '\n')
derchriss-Mac:~ derchris$ softwareupdate -i "$PROD";
Software Update Tool


Downloading Command Line Tools (macOS Sierra version 10.12) for Xcode
Downloaded Command Line Tools (macOS Sierra version 10.12) for Xcode
Installing Command Line Tools (macOS Sierra version 10.12) for Xcode
Done with Command Line Tools (macOS Sierra version 10.12) for Xcode
Done.
derchriss-Mac:~ derchris$ git --version
git version 2.11.0 (Apple Git-81)
```

I used git as an example of one of the tools which require the developer tools.
First start will show a Dialog box telling you to install them, I canceled it as I wanted to install it from CLI.
As you can see it finds, downloads and installs the developer tools without any GUI interactions.
These 3 lines are exactly the same I use in the AYAB script.
The softwareupdate is kinda the App Store for CLI.
So I don't know why it is failing on your end.

May I ask if you can try 2x additional runs using the following 5 lines in a terminal:

```
touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
PROD=$(softwareupdate -l | grep "\*.*Command Line" | head -n 1 | awk -F"*" '{print $2}' | sed -e 's/^ *//' | tr -d '\n')
echo "$PROD"
softwareupdate -i "$PROD";
git --version
```

For the first run, just use the terminal and let it run and wait.
And for the second run, open the App Store once, let it do its configuration like Apple ID and stuff, then close it before doing this from the terminal.
At the end you should see the git version number.
If it failed you should see a Dialog box asking to install Developer tools.

**Comment by Adrienne200** [comment]
I tried the test almost as described, I had the App Store launched but not signed in. That worked, after a long wait.
I also did the actual install again which also worked, though it took most of an hour altogether, with waits of well over 10 minutes at a time with no feedback. In the case of the Command Line Tools it sits at that non-informative “SoftwareUpdateTool” which doesn’t inform the user that they are waiting for a download. 
So let's ship this as it is, with instructions. And leave this case open and see if we need to improve the feedback in a future release.

**Comment by Adrienne200** [comment]
The real 0.9 release is much improved, thank you. 
Only the first item still happens, the spurious error. All the other extra text is gone, making for a much better install experience for the non-techy person. 
And the new warning to be patient is good, thanks.
Could still use some feedback that it's downloading the command line tools, but overall much improved from the last release candidate.

**Comment by derchrisuk** [comment]
The first error is unavoidable, unless the Xcode tools already installed.
As the download process is done using Apples SW download, there is no way we can show a progress, unless they offer one, which they do not.
