### ISSUE TITLE
Checkbox showing whether the image is mirrored or not

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#236]
This is related to #229, regarding the fact that AYAB automatically mirrors all images. This is a useful feature for many images such as photographs and text, but isn't always what you want.
 - for lace, we usually copy an existing Brother pattern; these patterns assume non-mirror, and do not work properly if knitted "backwards"; the transfers move in the wrong direction.
 - many patterns, including lace, you can't easily tell by looking at it which way round it is, so even after making the change for #229, this will still be an issue.
 - after #229 is changed, it will be handy to have a quick way to flip the image for review, then put it back to mirrored for the actual knitting.

I'm thinking of a "Mirror" checkbox, maybe beside the Infinite Repeat, that has the same effect as the Mirror item in the menu. It would normally be checked when opening an image, showing that the image has been mirrored automatically. So it's right there to remind you if you want to un-mirror it.

**Comment by sandrina2** [comment]
it would be lovely to have the automatic mirroring removed from lace patterns

**Comment by chris007de** [comment]
Mirroring can be enabled/disabled with a checkbox now, thanks to Tom (#316)

But I am still a bit puzzled if our default behavior matches the expectation of the user (i.e. our "non-mirrored" image is in fact understood as "mirrored" by the user).
Please clarify if we have to invert our behavior.

**Comment by t0mpr1c3** [comment]
In PR https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/420 I renamed the option "Wrong side image" which I thought was a more helpful description, and added orange / green background to the knit progress window as a visual cue to the orientation of the image respective to the knitting machine.

**Comment by t0mpr1c3** [comment]
Would it be helpful to call the option something like "wrong side image" rather than mirror image, given that checking the "mirror image" option does not make anything actually appear different on the screen?

**Comment by sandrina2** [comment]
the question that comes up in punchcard and electronic knitting is whether the image appears as drawn on the purl side, facing the knitter, or reversed on the knit side, away from the knitter. What of stating that simply as image appears as drawn on the purl side, or on the knit side as opposed to “wrong”?

**Comment by t0mpr1c3** [comment]
> the question that comes up in punchcard and electronic knitting is whether the image appears as drawn on the purl side, facing the knitter, or reversed on the knit side, away from the knitter. What of stating that simply as image appears as drawn on the purl side, or on the knit side as opposed to “wrong”?

Yes, I think that could be good.

**Comment by Adrienne200** [comment]
With build test230626 I have successfully used the Knit Side Image to cause a lace pattern copied directly from a Brother pattern to knit correctly. So functionally this checkbox is now correct, but I'm still considering the wording of the checkbox.  As well as the larger questions brought up in #229.
