### ISSUE TITLE
DBJ should do the white yarn first

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#237]
As currently implemented, 3 or more color DBJ (the "ribber" setting) does the black first, then the green, then the white. Was there a reason to do it in that order? I think white, black, green would make for a more intuitive flow, for most images.

It's the same with 2-color DBJ, it does black first. As you usually cast on in white, if you want to start your pattern immediately it would be easier if white came first.

**Comment by chris007de** [comment]
There was not really an intention behind the ordering of the colors, we can change it to improve the workflow.
We were also thinking of telling the user which color is currently active - but let's file that in a separate issue.

**Comment by Adrienne200** [comment]
Chris's point about telling the user which color is currently active is covered in #226

**Comment by sandrina2** [comment]
if the assumption is that one is creating 2 color images for download, I think the Brother native difference in starting color does not matter as long as software users are told which color to start with, and which color to change to after first reaching the color changer. Their black and white image serves as the roadmap to color placement. I have not experimented with more than 2 colors built in separation, but there again, give the order for the separation in use, and it should not matter. Having said that, it would make sense if DBJ in 2 color starts with black, followed by white, then  for 3 color to start with black followed by white followed by green

**Comment by Adrienne200** [comment]
AFAICT almost everyone who has tried this has expressed surprise that it's black first, they were expecting white, which seems to be the standard. White first also makes for a simpler cast-on process; you usually want to cast on in your background color, then use it for the first pass of the pattern. While we could certainly do a better job of documenting that it's currently black first, my vote is to just change it to white first, for both 2-color and 3+ colors.

**Comment by X-sam** [comment]
I am gonna close this as addressed, as we now have clear indication what color is to be knit.
