### ISSUE TITLE
Save a set of user preferences

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#238]
When working on a project, I'll be using the same settings every time I open an image. It would be nice if it remembered a set of Favorites or Preferences so I don't have to set them every time.
 - mirrored or not
 - 3 or more colors
 - single/ribber/circular
 - infinite repeat
 - alignment
 - anything else?
And a Reset to put them all back to default.

**Comment by chris007de** [comment]
As we are operating on multiple platforms, we need a versatile solution for this.
Portability/backupability would be a plus, so just storing a .ini file in the user folder would probably a  viable solution (configparser?).
Alternatively, PyQt provides QSettings, which handles storage of settings transparently (registry for Windows, hidden config file for Linux).
Aside from how it is solved under the hood, I propose to implement a helper class as an abstraction layer (AYABPreferences).

**Comment by t0mpr1c3** [comment]
I can have a go -- assign to me?

**Comment by chris007de** [comment]
Tested on Windows 10 with https://github.com/AllYarnsAreBeautiful/ayab-desktop/actions/runs/140183655:
Infinite Repeat and Mirroring are shown as enabled on first start of the software. When altering the values in the Preferences dialogue, the values are written to the Registry. After restarting the software, they are checked again, so it seems that they are not properly read from Registry.
The values for Alignment and Knitting mode are working as expected, so only the boolean values are having this issue.

**Comment by t0mpr1c3** [comment]
I remember having a problem with boolean values being written to `ayab.conf` in lower case ("true","false") but on reading are expected to be title case ("True","False"). Can you check what values are actually written to the registry?

**Comment by chris007de** [comment]
Every value in the registry is written lowercase.

**Comment by chris007de** [comment]
Still have to test if this is working properly on Windows and macOS now.

**Comment by t0mpr1c3** [comment]
Works OK on Windows, I think. I just made a small change to catch type errors in the saved settings (https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/378).

**Comment by t0mpr1c3** [comment]
Chris, I can run some checks on a Mac in a couple of weeks when I will have access to a MacBook.

**Comment by t0mpr1c3** [comment]
I suggest that this issue can be closed if Mac users are not reporting any issues.

**Comment by t0mpr1c3** [comment]
Are there outstanding issues, or can this be closed?
