### ISSUE TITLE
Explore other ways of doing 3-color DBJ

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#239]
As currently implemented in AYAB, you do 6 passes of the carriage to do one row of the pattern. Even using the birdseye feature on the ribber, that's 3 rows on the back to one on the front, resulting in the front stitch being very stretched and the other colors showing through.

The other classic way of doing DBJ is for those 6 passes to do two rows on the front; both rows must be the same. It stretches the pattern a bit more, but  gives better coverage and a nicer fabric.

Then there is a way of doing 3-color that is 4 passes per single row. I read about it here in this blog:
http://heartofpluto.co/2017/04/02/algorithms-of-multi-coloured-knitting/
The one the author liked best "Offset every first and last colour method" - as I understand it, it works like this:
 Colors 1 and 3 behave like 2-color DBJ (each color fills in its part of the old row then knits its part of the new row, in an ABBA sequence) 
 Color 2 takes two passes per row, as usual in 3+color DBJ. One pass is blank (that is, ribber-only) while setting up to knit and the return pass knits.

**Comment by chris007de** [comment]
Would you like to have several DBJ methods to choose from in the software?
That's possible, of course.
For each new technique, we just need a description how the image lines relate to the date we send to the machine.
E.g. for the current 2 color DBJ:
```
                # 0 0 1 1 2 2 3 3 4 4 .. (imgRow)
                # 0 1 2 3 4 5 6 7 8 9 .. (lineNumber)
                # | |  X  | |  X  | |
                # 0 1 3 2 4 5 7 6 8 9 .. (imageExpanded)
                # A B B A A B B A A B .. (color)
```
Note: imageExpanded describes the image in an "exploded" representation. For each row of the pattern, it as as much rows as the image got colors. So a 2 color pattern with 10 rows has 20 rows in the "imageExpanded" representation. The data inside looks like this:
Line 0 Color A
Line 0 Color B
Line 1 Color A
Line 1 Color B
Line 2 Color A
[...]

If you can provide such a "recipe" for the methods you mentioned, implementation should not be a big deal.

**Comment by Adrienne200** [comment]
I don’t have it in the diagram form that you requested, but here’s how the heartofpluto 3-color method works. The part that the code does is the "select for" column.
It takes 8 passes to knit two rows.
You set the ribber to knit in birdseye on every row. So the rows where it says to “knit blank” are knitting on the ribber only.
For the very first pass, no needles are pre-selected, it knits only a ribber birdseye row. On subsequent cycles it will look like this:
Change to Color A on left
Pass 1 L-R	: Knit previous Row 2 Color A	select for row 1 Color A	Color A [finishes row 2 of the previous cycle]
Pass 2 R-L	: Knit Row 1 Color A		select for row 1 Color B	Color A
Change to Color B on left
Pass 3 L-R: Knit Row 1 Color B		select blank (all to B)		Color B
Pass 4 R-L: Knit blank			select for row 1 color C	Color B
Change to Color C on left
Pass 5 L-R	: Knit Row 1 Color C		select for row 2 Color C	Color C [Row 1 is finished]
Pass 6 R-L	: Knit Row 2 Color C		select for row 2 Color B	Color C
Change to Color B on left
Pass 7 L-R: Knit Row 2 Color B		select blank			Color B
Pass 8 R-L	: Knit blank			select for row 2 Color A	Color B
Repeat for the next set of two rows. Each set of 8 passes is self-contained, no setup row needed.
To finish, the best place to stop the carriage is probably after pass 1 or 5 on the right. AYAB would stop selecting after pass 8 or 4.
The method could be extended to 4 colors or more. Think of Color C as Color “Last”, you could have multiple middle colors (color 2, 3, 4, 5) until your knitting is impossibly thick.

Here’s a sample:
<img width="377" alt="issue 247 3-color dbj 2" src="https://user-images.githubusercontent.com/24358225/41079161-616cd45c-69d5-11e8-9720-4dcad09b4e19.png">
Color A white (selection shown in pink in the diagram so you can see it)
         B green
         C black
We’re knitting the image that’s inside the blue frame. The first 6 rows are expanded in the lower half. The start of each set of 8 passes which knits two rows is marked. Notice that row 1 includes two green passes, even though green does not appear in this row.

**Comment by Adrienne200** [comment]
The first, I think. Either would work on the front, I think having B always appear before C would make the backing look more even. But either would be OK.
And yes, I think it’s a new type; some people like the existing method as it is for 3 colors. We may need to discuss the UI and terminology, but for a first try let’s just number them, such as:
Ribber 1  (the existing method, one row in front for 6 passes)
Ribber 2  (leave this for #262 which is the other standard way of doing it, two rows the same on the front for 6 passes.)
Ribber 3  (this ABbCCBbA method.)

**Comment by duncan-d** [comment]
I think I've got the "Recipe" figured out if anyone wants a look. I haven't looked through the code enough to see how to implement a new Machine Type so it's taking over the colors>2 ribber knitting right now.

https://github.com/duncan-d/ayab-desktop/blob/0d9f39ed7083bfc19106c5c0ac8c15364ce8cda1/ayab/plugins/ayab_plugin/ayab_control.py#L486

This will do A-B-CDD-C-BA. 
I found it far more intuitive when using the color changer on my machine to think of the colors as going back and forth so When doing 3 colors they both end up being 
0 1 2 1 0 1 2 1 0
but when you go up to 4 colors it's
0 1 2 3 2 1 0 1 2 3
instead of 
0 1 2 3 1 2 0 1 2 3

**Comment by chris007de** [comment]
@duncan-d Thanks! :tada: 
I'll include this as another machine type, just like described by @Adrienne200.
But I would ask one of you to write some documentation how to use this new mode. For now, we'll place it on the website (so please create a pull request for the website content), later on we should include it to the software (see #269)

**Comment by duncan-d** [comment]
I'd be happy to, would it go in the tips n tricks page? 
Should it be written as if it was starting with color 0/White to plan ahead for the change proposed in #237 or just as is?
Should it be thorough enough to serve as general DBJ documentation or just to clarify the specifics of this version?

**Comment by chris007de** [comment]
@duncan-d I suggest to write starting with color 0 (taking #237 into account), but add a disclaimer at the very beginning that in 0.95, it is still starting with black.
Would be great if you would do a general DBJ documentation, we do not have anything in this direction currently.
We could add it to the tips and tricks page or add another page which contains knitting instructions.

**Comment by Adrienne200** [comment]
Before we finalize this, I have to make a change to how I characterized it. When heartofpluto showed her Star tapestry in August 2018 I dived in again to make sure I really knew how she did it. I went through her Python code and realized that what I had written here was not how she did it at all! I just wrote up a separate issue about how her algorithm actually works, #271. It’s a lot more sophisticated than this, but both methods have their pros and cons.
So about this one, I may have actually invented it myself by misunderstanding what Sarah did. Most likely it has been done before, but it isn’t in any documentation that I have found so far. Anyway it needs a name that doesn’t attribute it to heartofpluto, I’m going to ask you to change your comment in the code. The name I have come up with so far is Middle-Colors-Twice. (Or colours of course, both spellings are correct)
So now we have:
Ribber 1: the existing method.
Ribber 2: leave this for #262, pairs of two rows the same
Ribber 3: Middle-Colours-Twice
Ribber 4: HeartofPluto. (Or we may think up a descriptive name for it)
I’ll leave it to you to decide whether 2-colour is actually a subset of all of them. Or even if that’s true, if it’s set to 2 colors should it just be #1 and #2 with the other choices greyed out for simplicity? The point of these later methods is for 3+ colors.

**Comment by duncan-d** [comment]
@Adrienne200 I don't think it's too long at all! If I'm remembering correctly your post is actually what got me to finally understand how to do DBJ. I think your post combined with instructions for casting on would provide a thorough start for people who aren't familiar. 
What would you think of an abbreviated version for people who just needed a reminder at the top with links to anchors for detailed instructions for that step below?

**Comment by duncan-d** [comment]
I'll change my notes to reflect that it's actually Middle-Colours-Twice and switch it around so that it starts with white. It just occurred to me yesterday that this should be able to replace the current code for 
`            elif self.__machineType == 'ribber' \
and self.__numColors == 2:`
as well since it basically expands on and includes how that functions.
I'll check that this is true while doing some swatching and photos for documentation.

**Comment by duncan-d** [comment]
It also works for 2 colors and ends up doing ABBA starting with white. If it also took over for the 2 color ribber code it would resolve https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/237 for 2 color DBJ as well.
I did wonder if having "Middle-colors-twice" doing 2 colors would confuse users though, since there's no middle color to speak of.

**Comment by chris007de** [comment]
@duncan-d @Adrienne200 
I created a repository for the AYAB user manual at https://github.com/AllYarnsAreBeautiful/ayab-manual
It uses mkdocs, which relies on markdown, so adding content should be pretty straight forward.
I'll give both of you access to the repository, so you can directly commit and do not need to create pull requests.

**Comment by Adrienne200** [comment]
This is working well now, thanks.  The 4-color version distorts the fabric more than I expected, the 3-color works well, looks similar to other methods. So does 2-color; it gives a slightly tighter row gauge than 2-color classic, I haven't figured out why yet, I expected it would be the same.
One more tweak though, see my comment in #226, the places where it says "Color:Blank" are not so useful, here and in HoP.

**Comment by clholgat** [comment]
We have Heart of Pluto support now. I'm going to close this because it accomplished it's original goal.

If there are other techniques y'all'd like to see, please open a new ticket.
