### ISSUE TITLE
Put information/tutorial for circular knitting on homepage

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#240]
On facebook, people are asking for info about the circular knitting mode. Currently it is only documented in this ravelry thread: http://www.ravelry.com/discuss/ayab/3346844/

We should add the instructions from this thread and some pictures on the homepage to explain what circular knitting does.

@Adrienne200 would you mind to take this task? I guess it's more reasonable to be written by somebody who knows how to knit ;)

**Comment by Adrienne200** [comment]
I added a whole lot more to the Ravelry thread in November. Too much detail, needs to be edited down, but the main instructions are in post 12 on the Ravelry thread.

**Comment by chris007de** [comment]
Let's put this also to the manual (see #269)

**Comment by Adrienne200** [comment]
Yes, please do that. That was the idea, that the Ravelry threads were a temporary place to put this sort of thing until we made a proper manual. Same with post 1 of the DBJ thread.

**Comment by chris007de** [comment]
Circular knitting: https://github.com/AllYarnsAreBeautiful/ayab-manual/commit/17f37ba7975a3faa521a0066caf8a8e580562185

**Comment by chris007de** [comment]
2-color DBJ: https://github.com/AllYarnsAreBeautiful/ayab-manual/commit/edbad3c3f929865793da3f09c8e629d171cf8cd4
