### ISSUE TITLE
Switch between view of loaded image file and how it gets interpreted by the software

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#242]
Currently, the AYAB software shows the original image file loaded by the user on the canvas. Due to e.g. compression, the software might intepret a grey value not as expected by the user. Therefore, we should include a possibility to show how the software decided on the color for each pixel after loading the image.

**Comment by t0mpr1c3** [comment]
The new internal representation does not compress the image to greyscale. Instead it retains the full information from a restricted palette of colours. (https://github.com/AllYarnsAreBeautiful/ayab-desktop/commit/d1e6308d6697da88549404cc9cfcb0d173d212f0)

**Comment by chris007de** [comment]
@t0mpr1c3 I guess this can be closed due to #308, right?
