### ISSUE TITLE
Make it faster turning around for the next row

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#246]
Knitting with AYAB is noticeably slower than in native mode, where you can just turn the carriage straight around and knit back immediately. Anyone who has used Brother machines before has to consciously slow down to wait for the beep. (Not always a bad thing, knitting too fast means you fail to catch mistakes before they turn into disasters.) It would be nice if you could shave a few more milliseconds off the turnaround time. 
Also it may be too slow for reliable use with the Brother motor, which turns around faster than AYAB does.  It can probably be done with careful attention to where to tell the motor to turn around, I haven't tested in detail.  (And the noise of the motor drowns out the beep, case #208 will be useful here too.)

**Comment by chris007de** [comment]
Yes, changing direction of the carriage definitely takes too much time currently. We have to investigate where we are spending the time and become faster.

**Comment by oskay** [comment]
One part of this is (was) here: https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/14

**Comment by chris007de** [comment]
Now its here: https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/9

**Comment by Adrienne200** [comment]
Much improved with the change to 12 on both sides in https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/9. There is barely any perceptible delay, it would be almost impossible to turn around too fast.
My remaining question was a proposal by Brian Parker on Facebook, Nov 17, 2018. He said "Instead of waiting a full second and hoping the full packet is ready, [it should read] the first command byte to figure out how many bytes are needed then read that many. The delay is gone so you don't need to pause and wait for the beep."
Did you already incorporate a fix like this? Or is it unnecessary now? It seems like it should work this way anyway, just cleaner.

**Comment by chris007de** [comment]
The serial protocol overhaul includes implementation of the SLIP protocol, which provides packet start and end markers. So both the GUI and the firmware on the Arduino are able to recognize packet borders, so no more dummy delay and hoping for complete packets.
Including packet sizes in the packet header would have been another way to solve this issue, it's just tomato or tomatoe.
I'd say this issue is fixed.
