### ISSUE TITLE
Start from the right hand end of the machine.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#247]
Most Brother instructions have you starting from the left, but it also works starting from the right. Their instructions for restarting after a mistake allow restarting from either end. The CK35 manual says you can start from either end. Instructions for using the single-bed color changer have you doing the setup row starting from the right; starting from the right would be useful for case #204.

**Comment by chris007de** [comment]
@Adrienne200 Is this also the case for the L and G carriages?
In other words: Should we enable starting from either side for every carriage?

**Comment by Adrienne200** [comment]
Yes, for all carriages please.
Some use cases:
 - the single bed color changer goes on the left, so it’s convenient to do a set-up row from right to left. Workaround is to organize your AYAB pattern to do the initial setup row in row 2.
 - when recovering from a mistake, it’s nice to be able to rip back and restart from either side.  
 - for lace, there are experiments in early March 2018 by Sandy (Alessandrina.com) who was doing lots of samples with using two patterning carriages together. The carriages take turns, two or four passes each then park on the side so the other carriage can use the belt. This already works if both carriages make their initial start from the left, then later park on the right. But if the pattern requires the second patterning carriage (usually the Lace carriage, but could be a second K carriage) to first appear from the right, it fails to select on that first row, and selects random needles on later passes.
 - the garter carriage’s cast on and cast off only work from right to left, they must start from the right. Actual garter carriage knitting can start from either end, so a first try would be OK starting from the left only, but both sides would be needed eventually. When fixing a mistake, unraveling a row is more troublesome when using the garter carriage, nice to be able to restart on either side.

**Comment by sandrina2** [comment]
In the unaltered 910 I have created all my production pieces requiring color changes every 2 rows by knitting with 2 carriages, each selecting the next row of pattern correctly. I have not been able to duplicate that with 2 knit carriages, or as stated, with the knit carriage operating from the left, and the lace carriage from the right. Patterns that require for first row preselection from the right may be used by starting the first set up row on the very last row of pattern within the software, or moving the last row to design row 1 position within the pattern repeat. I prefer editing the repeats themselves to get them to produce the results I want.

**Comment by chris007de** [comment]
We've learned from the garter integration that the KH-910 is not able to detect the L magnet on the right sensor.
So the hardware restricts to start/park L and KG (which has a combindation of K and L magnets to identify KG) on the right side with KH-910.

We can implement a detection of K, L and KG on both sides, but on KH-910 (and probably others I am not aware currently) it will simply not work. But for KH-930, it should do.

**Comment by sandrina2** [comment]
I have actually knit lace using the lace carriage parked on the right using ayab <http://alessandrina.com/2018/01/02/lace-punchcards-meet-ayab/>. The problems I have encountered have been the knit carriage was no longer used to knit plain stitches, but rather for its own selection using slip stitch for automatic shaping of the lace. The process works fine with knit carriage on right, lace carriage on left, as seen in the auto shaped lace trims <http://alessandrina.com/2018/03/05/lace-edgings-on-brother-machines/>, so selection with 2 carriages is possible, but I have not been able to keep a continuous pattern with 2 _knit_ carriages in use selecting needles. Am puzzled by the inconsistency

**Comment by Adrienne200** [comment]
This is strange. Using AYAB’s test mode on my 910, I see the same thing as Chris reports; on the right I’m only getting a response from the K-carriage (North) and not the L (South), but both work on the left. But everywhere I look regarding how it worked in native mode, including the service manuals, it says that the right turn mark behaves the same as the left, for all carriages. Pages 20-22 of the 910 Mk1 service manual walks you through how to adjust the right sensor for the lace carriage. So even in the earliest model of the 910, they intended the lace carriage to work from both sides, and it did. 
http://machineknittingetc.com/brother-kh910-service-manual-1167.html
But anyway I'll be happy to see it on the 930 first, and leave this mystery for further investigation.

**Comment by sandrina2** [comment]
I have now been able to knit several swatches using 2 **knit** carriages selecting needles properly in fabrics where they were operating set to different functions from either sides, and for varied numbers of rows. With care, the technique appears doable in the software as is.

**Comment by Adrienne200** [comment]
Every way I look at these machines in their original mode, I find that the right Hall sensor appears to work exactly the same as the left, so I still think it should be possible to have AYAB start from the right. Even on the oldest first-generation 910 machines, with one exception. 
I think Chris may either have had a faulty machine, or you tripped up on the one exception.
That exception is that a first-generation 910 with its original electronics does not detect the S-N magnet of a garter carriage. But as far as I can tell, the sensor itself can detect the South for the L carriage as well as North for K, but the first generation of the original hardware could not recognize the S-N sequence as a garter carriage.
The first-generation 910 is the one with two AA batteries under a flap at the left end of the bed. It did not support the garter carriage. The good news is, it only took replacing the electronics unit with the second generation to get the g-carriage to work, no other hardware changes. So AYAB should support a garter carriage even on the very oldest 910s, and I think it should be able to read the right magnets as well as the left.

**Comment by chris007de** [comment]
As it seems that it's a matter of our machine here, we'll just implement the logic for the right hall sensor also and see how it performs at the users' machines :)

**Comment by t0mpr1c3** [comment]
Am I right in thinking that currently AYAB assumes that the carriage is on the left at start up? 

Can we detect the starting position of the carriage, or is it the case that we can only detect the position of the carriage once it is in motion?

If we can only detect the carriage when it is in motion, does that mean that the user would need to inform AYAB of the starting position of the carriage, i.e. whether it is on the left or the right? This could be implemented in the GUI, but I am not 100% sure from this discussion what the consensus is.

**Comment by chris007de** [comment]
> Am I right in thinking that currently AYAB assumes that the carriage is on the left at start up?

Yes, but that's in fact a firmware issue. During intialization, we are expecting to see a change at the left hall sensor to calibrate the position of the carriage. But it should(TM) just "copy & paste" of this logic to have this enabled on the right hand side of the machine also.

> Can we detect the starting position of the carriage, or is it the case that we can only detect the position of the carriage once it is in motion?

For initial location of the carriage, it has to pass the left hall sensor (currently) or either one of the hall sensors (if we integrate the requested change). After this initialization, we know the carriage position by detecting the movement of the metal band and "counting holes".


What I don't know: whether choosing the starting side freely has any implications on the pattern handling, or if it just behaves like starting from the left :shrug:. I can imagine that it might have implications for multicolor/ribber knitting? But @Adrienne200 wrote already that it's obviously allowed for many cases to chose either side.

**Comment by sandrina2** [comment]
The default behavior in starting from the left is a requirement in 2 colors per row DBJ only when using the built in KRC color separation only. At present the workaround in Ayab has been to start on a row other than the first design row for the first preselection row from the left. It would be a huge convenience to be able to start patterning from the right as well. 
Any patterns that requires color changes every two rows, ie commonly done with slip and tuck, on the original 910, were simply started from the right toward the color changer. I have also done a lot of knitting with 2 knit carriages selecting from opposite sides on the original 910 and 930 with img2track, was not able to do so with Ayab.

**Comment by t0mpr1c3** [comment]
OK. I'd like to help make the changes. I haven't really engaged with the firmware yet, but I should probably look to see what the proposed firmware changes are to see what needs to happen on the computer end.

**Comment by sandrina2** [comment]
That would be awesome. Please let me know if I can help in any way including supplying you with some test repeats

**Comment by t0mpr1c3** [comment]
The firmware side of this has been addressed in PR https://github.com/AllYarnsAreBeautiful/ayab-firmware/pull/38#event-3686534297

**Comment by t0mpr1c3** [comment]
> > Can we detect the starting position of the carriage, or is it the case that we can only detect the position of the carriage once it is in motion?
> 
> For initial location of the carriage, it has to pass the left hall sensor (currently) or either one of the hall sensors (if we integrate the requested change). After this initialization, we know the carriage position by detecting the movement of the metal band and "counting holes".

Am I right in thinking that the carriage and direction are reported in the `indState` message prior to `reqStart`, so the host (desktop software) should know from that message which side the carriage is starting on?

**Comment by t0mpr1c3** [comment]
I have made pull requests to effect the changes to the firmware that should allow the carriage to start on the right, and corresponding changes to the desktop software that should identify which side that carriage is starting on.

The next changes that need to be made are to the knitting modes. What do these changes enable in terms of knitting that could not be done before?

**Comment by sandrina2** [comment]
I am not certain I understand the question
> The next changes that need to be made are to the knitting modes. What do these changes enable in terms of knitting that could not be done before?
> 
the modes are self explanatory, I think they already cover most knitters’ needs
btw, HoP is bloody awesome
your option for knitting the  second color twice is a mystery to me in terms of future use 
additional modes are likely to be on wish lists only for folks interested in complex knit structures
it is too bad that there are not more shares in forums of finished work using the program and that there are issues that are no fault of the software, but rather hardware, that can make patterning unpredictable 
such shares would increase interest in using ayab and pushing its limitations 

several of the original users that produced great work early on ie Claire Williams work have gone quiet 

are you looking to add more varieties of modes? there certainly are some other color separations that could be useful, especially with a start from the right

one such is the separation that knits each color in each row twice. Knitters don’t like it for standard dbj because it causes elongation of the design on the knit side, but it can work for other fabrics 

the separation for mosaic knitting is pretty straightforward and a colossal pain to do by hand

there is always room for more ;-)

**Comment by t0mpr1c3** [comment]
Thanks for your reply! I am interested that you mentioned mosaic knitting. That is perhaps something that I might think about trying to implement in the future.

I was really trying to ask a question more specifically about the issue of starting the carriage on the right. The way that the existing knitting modes are set up has assumed that the carriage will start on the left. I am wondering what exactly will need to change to accommodate starting on the right.

There may well be new knitting modes that are enabled by starting on the right but I haven't even got around to thinking about that yet!

**Comment by sandrina2** [comment]
traditional KRC DBJ built in separations for DBJ is the only fabric I can think of that actually requires a start on the left 
nearly any other fabric using the color changer, including dbj where each color in each row knits twice traditionally are started with the preselection row from left to right
to work those fabrics in ayab with a left start one has to fiddle with the starting row of the pattern by changing the row selection in the program. I tend to do any of that row stuff in the design before uploading it to avoid remembering to do make the change should I return to knitting the same repeat at a later date/ fewer operator errors

the lace carriage always stars from the left on most machines (Toyota is an exception)
punchcard machines automatically produce whatever the design on the purl side, so if text is used, the image would need to be mirrored to work correctly, ayab takes care of that
lace works a bit differently however, so if punchcard repeats are programmed in ayab they need to be flipped horizontally if I remember correctly, prior to knitting them for lace carriage use from the left

in terms of a start from the right: could you offer single mode A from left and single mode B from right? I can provide you with some repeats that would work using B if that would help 

I think the onus is on the knitter to understand what is required of the fabric that they are trying to produce.

left start for ribber, and hop modes is fine
single bed for fair isle can work with start from either side

**Comment by t0mpr1c3** [comment]
That's all very helpful. I will need to unpack the detail and it might take several iterations, so please bear with me.

Let's just consider the knit carriage for the time being. I have not really got to grips with lace yet.

I hear what you are saying when you say that the onus is on the knitter to know what they are trying to do. The user should know if they are going to start on the left or the right.

If I understand you right, we need to provide a single bed (2 color) mode starting on the right, in addition to the current mode starting on the left. If you could provide some repeats that would work with that I would find that very helpful.

The one mode that cannot start on the right, is that what AYAB calls classic ribber mode with 2 colors?

**Comment by sandrina2** [comment]
Hi Tom:  clear yes to 
> The one mode that cannot start on the right, is that what AYAB calls classic ribber mode with 2 colors?
> 

I will gladly accumulate some data and images for you on when a start on the right is helpful. It may take a bit of time since I am dealing with some issues at the moment that can eat up hours out of my life daily.  

I have been intending to set up my 910 again within range of my computer, at the moment it is not yet, so immediately I am not certain how soon I can explore knitting ideas using it

Perhaps the start from right ideas can be explored as a work in progress blog post

another option in knitting by the way is using 2 separate knit carriages, one operating on from the left, one from the right, enabling things like using yarns in different weights at different tensions, plied ones that don’t get along with the color changer, operating with the use of different cam buttons in each carriage instead of having to hand switch them.

I wrote several ayab blogposts in the past, mostly using the previous ayab release, exploring every fabric I could think of. Some links to them  https://alessandrina.com/2020/08/07/a-return-to-ayab-knitting/ <https://alessandrina.com/2020/08/07/a-return-to-ayab-knitting/>

> If I understand you right, we need to provide a single bed (2 color) mode starting on the right, in addition to the current mode starting on the left. If you could provide some repeats that would work with that I would find that very helpful
> 

the machine has no clue as to what carriages settings are or what fabrics are being created. The option to start from the right could also work for ribber fabrics where the knitter provides an appropriate hand drawn color separation 

Later, 
Sandy

**Comment by t0mpr1c3** [comment]
No time pressure on the patterns. And thanks again for your insights, and for the links to your blog posts, which are tremendously informative.

**Comment by Adrienne200** [comment]
First question would be, can the K carriage do the usual basics such as fair isle, when starting from the right? Any image, nothing special needed, though it should be asymmetrical so you can see if it's mirrored. It might just work, possibly with the image being mirrored. Or you'll be able to see where it stalls and where you might need to tell it to work in reverse.

Once that is working, I'd just want to experiment and try other things. Such as restarting after a mistake or ripping back a row, it would be nice to be able to restart from either side. But I agree that it's mostly about the person knowing what they want to do and how it works.

The various DBJ techniques work pretty well as they are, starting from the left, but there may be a case for starting some techniques from the right, I won't really know until I can try it.

And if/when the garter carriage ever works, starting from either side will be useful there. 
Are you able to build working firmware yet, or are you still only working with the simulation? Either way another test build would be useful.

**Comment by t0mpr1c3** [comment]
Yeah, I need to just try it out I think.

Restarting on either side, and in the middle of multi-line rows, is
definitely on the radar but is a little further down the line.

I'm pretty close to having new firmware, this is about the last thing I am
adding in. I'll try for an unofficial test version next week, if I can get
it working at all.

**Comment by X-sam** [comment]
there's a handful of tickets about this
