### ISSUE TITLE
Fix the lace sample patterns

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#249]
There's a set of 910 lace samples installed with AYAB 0.9 
<user>/Documents/AYAB/patterns/kh910
But the lace patterns weren't copied correctly. With lace the empty space is important, these patterns were intended to be used with two blank rows at the end, and some of them also needed some blank columns.  I'll remake the files with the following rows/columns added. In the meantime, users should add these before selecting the whole unit to copy/paste.

8-29: 23 sts wide, 80 rows high. (1 blank column on the right, 2 blank rows at the top.)
8-30: 24 sts wide, 60 rows high. (Width is correct, 2 blank rows at the top.)
8-31: 25 sts wide, 88 rows high. (1 blank column on the right, 2 blank rows at the top.)
9-32: 60 sts wide, 150 rows high. (Width is correct, 2 blank rows at the top.)
10-33: 22 sts wide, 70 rows high. (1 blank column on the right, 2 blank rows at the top.)
10-34: 22 sts wide, 60 rows high. (4 blank columns on the left, 2 blank rows at the top.)
10-35: 10 sts wide, 30 rows high. (1 blank column on the right, 2 blank rows at the top.)
10-36: 38 sts wide, 72 rows high. (1 blank column on the left, 2 blank rows at the top.)

**Comment by chris007de** [comment]
Fixed in 98c335002cbe6acbac3554dd242cc00483c14044
