### ISSUE TITLE
everything set up but still it doesn't work

### ISSUE THREAD

**Issue by loginanzu** [AllYarnsAreBeautiful/ayab-desktop#252]
Hi, I hope it's not OT: I've just installed the AYAB shield, and AYABmac on my computer, it seems everything set up but when I press KNIT, the needles don't move. 
Doubts:1) I haven't turned on the original switch as it's written in the instructions, correct? 2) there's a plug that is not plugged anywhere (the one with the orange, brown, black, red and blue wires). is it correct, right? 
What's wrong?

**Comment by Adrienne200** [comment]
If you bought the AYAB interface from the Evil Mad Scientists, you use the power unit that came with it, and do not use the machine's power. 
If you are using a standard Arduino and a shield, the shield should have a set of thick wires at one end which take the machine's power plug, and the machine's power needs to be on. What knitting machine do you have?

**Comment by loginanzu** [comment]
thanks! now it works :) (I didn't run correctly the ayab launcher)
