### ISSUE TITLE
Show in the UI which carriage is in use, and which direction it is travelling.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#254]
A letter K, G, or L, and an arrow.  
Where? Maybe in the top right gray bar above the main window. Or below, near the (enlarged) row number.

**Comment by chris007de** [comment]
I think that's a good idea - to be able to do this, we have to implement the continuous status reporting first (https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/257)

**Comment by chris007de** [comment]
> Ability to have some sort of memo for color changes, changing cam buttons, and maybe more would be very convenient, but in what form would merit more discussion.
please see https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/250

**Comment by chris007de** [comment]
Handling this issue within #257
