### ISSUE TITLE
Review the "Image Transmission Finished" message.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#255]
Currently (0.9 sw and 0.9 fw) when you are one row ahead of the last selection you get:
 The row numbers disappear 
"Image Transmission finished. Please knit until you hear the double-beep sound"
 The marker on the image jumps down to the beginning.
You knit across and it does the selection for the last row and gives the long-beep sound. But you then need to knit one more row to actually knit that selection. Then it has selected all to B, you cancel your settings and you're done. Users generally know this, it's how Brother patterning works. But the message could be a bit more informative.
Suggestions:
It could show the last row number as well as the text, to remind you where you are. 
The marker should stay at the top until after the last row has been selected.
The wording is OK as it is, or consider something like: 
<row#> "Selection will be finished when you hear the long beep."
(We can ask the community for suggestions)
I don't think it should try to actually tell you that you need to knit back one more time after the long beep. The message needs to be short. But mentioning selection rather than knitting gives a hint.

**Comment by sandrina2** [comment]
written text is only visible if the computer screen is within easy view, which may not be practical or even possible, depending on constraints of set up space. Having a quick start info sheet that tells the user when needles go flat you are done, would also be helpful.

**Comment by chris007de** [comment]
@t0mpr1c3 Do you think this issue is still relevant for v1.0.0?
I would say we have a different behavior now and it should be re-evaluated if the new situation is acceptable for the users.

**Comment by t0mpr1c3** [comment]
Agreed.
