### ISSUE TITLE
Behavior when the computer sleeps

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#258]
If the computer goes to sleep, after a while the patterning stops working.

Should it tell the OS that it is active every time it communicates with the Arduino?

Mac, Sierra.
For testing, set Prefs->Energy Saver-> Turn display off after 1 minute.
Start knitting. 
 (I used the Triangles 60x10.png sample, set to infinite repeat. Other settings at default.)
After a minute the display goes dark, you can continue to knit successfully for a little while.
Around row 40 of my test, it stopped beeping, and continued to select the same row over again. No new rows were coming down from the computer.
I experimented with the settings "Prevent computer from sleeping automatically when display is off" and "Enable power nap when on battery power", didn't make much difference.

Windows 7.
Windows seems to be more tolerant, continues to knit with the display off. 
It will eventually hibernate, default 6 hours. That's OK, after that long powering down is a good thing. I didn't try yet if Mac will do the same.

**Comment by sandrina2** [comment]
I am working using hight Sierra, set the energy saver to turn the display off after a longer period than the default, depending on how long I expect to be working, witch it back when I am "done" knitting. There has been no need to change other settings.

**Comment by chris007de** [comment]
This is a highly OS-specific topic. We have no influence on how Windows, Mac, Linux handles the running applications and used interfaces when it enters energy saving modes.
Simply switching off the screen normally does no harm to any running programs, so AYAB should continue to do it's job.
When coming back from hibernation, I doubt that the state of the serial interface is properly restored, restarting the knitting process is probably the best thing. (Additionally, in some energy saving modes, the USB is powered down, so the Arduino will lose its current state - so it will know nothing about the current state of knitting when coming back from energy saving.)
