### ISSUE TITLE
improper row advancement 

### ISSUE THREAD

**Issue by sandrina2** [AllYarnsAreBeautiful/ayab-desktop#260]
I am using an EMS kit, have found that movement of the carriage on the same side of the needle bed ie to unravel stitches, fix yarn  loop, etc, has been enough to advance a row in the pattern, while continuing selection. This behavior was never an issue in an unaltered 910, but built into punchcard operation. There the card advancement and reader noise gave an easily recognized clue, with an easy enough fix. Things get more complicated to accomplish same using the software

**Comment by chris007de** [comment]
I do not really get the point of that issue.
Do you mean something like https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/244 ?

**Comment by sandrina2** [comment]
yes
