### ISSUE TITLE
Double width and height of patterns

### ISSUE THREAD

**Issue by sandrina2** [AllYarnsAreBeautiful/ayab-desktop#261]
it would be lovely to have actions for twice as long, twice as wide added, allowing for experimentation without having to redesign and reprogram motifs

**Comment by oskay** [comment]
Is this the same as the changes just added?
https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/251/commits/cff39c1ad9d62838d38dc313adeee548871d825a

**Comment by sandrina2** [comment]
this shows original functions or "actions" in the original 910

<img width="308" alt="actions" src="https://user-images.githubusercontent.com/38115007/38471898-ac0e0b5c-3b45-11e8-93be-6bad68132161.png"> ones that appear to be missing from ayab are marked with X
here is a single shape as it would be entered on the far left, then altered by the machine to twice as wide, or original again, to twice as tall 
<img width="291" alt="twice as wide tall" src="https://user-images.githubusercontent.com/38115007/38471926-ffeedfd0-3b45-11e8-8095-e5e25e3c66a5.png">
the mirror image would probably be rarely used

**Comment by Adrienne200** [comment]
Windell, as you can tell from Sandrina2’s sample images, the feature being requested is to double-width and double-height all the pixels individually, as opposed to repeating the whole image. If you turn both features on at once you get an “8-bit graphics” look, 4 stitches knitted for each pixel.

As Sandrina2 says, these two are the only features left from the set of seven switches/buttons that the machines had in native mode that aren't already represented.

**Comment by chris007de** [comment]
When refactoring the image processing part of the software, we can easily add this functionality.

But to be complete, it's not only double-width and double-height, it's also "reflection" which is currently missing, right? We could add this also.
It's just adding a 180° rotated copy on top of the current pattern?

**Comment by sandrina2** [comment]
yes, 180 would work, then in turn combining the 2 designs, making a second repeat, which would then be used for "infinite". In the 910 none of the buttons could be combined if the KRC button was going to be used. If the image can be loaded and altered using actions and then separated for knitting ie using "ribber" setting, then ayab would offer a feature never in the original machine. This would be the _new repeat_ from the image used above. 
<img width="45" alt="screen shot 2018-04-09 at 7 06 55 am" src="https://user-images.githubusercontent.com/38115007/38494939-bfd2b2fc-3bc5-11e8-92c1-cf11bffd0e3c.png">

**Comment by chris007de** [comment]
Thanks to @t0mpr1c3 we now got the "stretch" feature.

Still to do: Reflection

**Comment by t0mpr1c3** [comment]
So, there are various possible ways to reflect: as if the mirror were above, below, to the left, or to the right. It seems we might as well implement all of these, rather than just one.

e.g.
reflect left ">" = "<>"
reflect right ">" = "><"

It is also possible to do multiple reflections at the same time. For example, reflecting both left and right would transform ">" to "<><" and performing all 4 reflection at once would give

<><
<><
<><

This could be implemented by allowing multiple choice instead of mutually exclusive options.

**Comment by t0mpr1c3** [comment]
I decided to implement the more complex multiple choice option, but if desired that can be downgraded to the simpler option without difficulty.

**Comment by X-sam** [comment]
Implemented, still needs documentation as part of #318
