### ISSUE TITLE
test default instructions

### ISSUE THREAD

**Issue by niccokunzmann** [AllYarnsAreBeautiful/ayab-desktop#27]
the default insrtcutions of the library should be tested for
- mesh consumption
- mesh production
- description text

**Comment by niccokunzmann** [comment]
This should be a test case that tests if description is present and if the numbers are right

**Comment by niccokunzmann** [comment]
[Branch](https://github.com/AllYarnsAreBeautiful/knittingpattern/tree/test-default-instructions)
- todo: one test

**Comment by kirstin** [comment]
Test all instructions are tested.

**Comment by niccokunzmann** [comment]
@kirstin you can take over again
