### ISSUE TITLE
Implement the HeartofPluto method for DBJ

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#271]
In Issue #239 I wrote up what I originally thought was the DBJ method designed by Sarah at heartofpluto.co. But after she showed her magnificent Stargazing Tapestry in August 2018, I revisited the topic in more detail. This time I ran her actual code and studied in detail how it worked, and realized that I had previously entirely missed the point, I had not understood her method at all. (Well, as part of my misunderstanding I came up with the different and valid idea in #239, which now needs a new name, such as middle-colors-twice.)
I wrote several looong posts on [Ravelry](https://www.ravelry.com/discuss/machine-knitting/828238/476-500#489) describing in laborious detail how I now think it works, and comparing it to the conventional two-rows-the-same (issue 262). (If you don't want to join Ravelry I can copy it somewhere else.)

Sarah’s code is [here](https://github.com/chixor/knitting_machine) and her not-very-detailed blog post introducing it is [here.](http://heartofpluto.co/2017/04/02/algorithms-of-multi-coloured-knitting/#more-215)

In her algorithm the 3 yarns knit in AABBCC sequence as always, so the backing is the same, and left-right passes select as usual. But the key difference is that before each right-left pass is knitted, it queries as to whether the previous row is complete yet. If not, it always assumes that there might be a conflict and does not knit any pattern on that row, just knits on the ribber. (conflict: a place where it is filling in color X of row 2, but color Y hasn’t knitted row 1 on that needle yet) Note that it doesn’t check for actual conflicts, just always assumes that there could be a conflict. If the previous row has had all 3 colors knitted already, then it can pattern on this R-L row as usual.

One effect is that a pair of rows is no longer a self-contained unit, as is the case in most DBJ methods. You have knitted 6 passes (a set of 2 passes of each color)  but row 2 isn’t complete yet. To have a set of rows complete evenly, I think the pattern needs to be a multiple of 6 rows.

**Comment by duncan-d** [comment]
If I'm understanding this correctly it almost seems like it takes the opportunity to advance to the next image row as soon as possible. So if you're doing AABBCC the opportunity to advance sort of walks backwards down the color sequence. i,e on the first AABBCC set you advance to image row 2 on color C but on the second set you can advance to image row 3 on color B. I hand made a 4 color separation of how I think this goes. Does that look right to you @Adrienne200?
![1](https://user-images.githubusercontent.com/44714893/50385612-0e897680-069e-11e9-8cf3-edef5095fe75.png)
![2](https://user-images.githubusercontent.com/44714893/50385615-11846700-069e-11e9-9323-81f25c03aeb3.png)
![3](https://user-images.githubusercontent.com/44714893/50385617-134e2a80-069e-11e9-8f74-82a74e443c49.png)
Sorry I'm doing a 4 color example again, it just helps me riddle out the issues more easily.

**Comment by duncan-d** [comment]
Did the color separation get reversed? I thought I had figured this out but it knit black first

**Comment by duncan-d** [comment]
I think I've got the basics sorted out
https://github.com/duncan-d/ayab-desktop/blob/0ab2e57c10be0ac298533d367dab8737b15165d8/src/main/python/ayab/plugins/ayab_plugin/ayab_control.py#L527
It took me awhile for my brain to accept that while the color sequence happens over 8 passes you still get a complete image row every 6 passes. In my image above I made my color separation match what @chixor 's code generated. There are 3 blank lines over the first 6 rows, but in reality you can shift the first set of white/color 0/color A stitches up a row so you knit them on the first right to left pass.
So in the end you don't need any special multiple of image rows for it to complete evenly you just might not end on your highest color, in this instance black/color 3/color D
Here's how the middle-colors-twice compare
![pluto v mct](https://user-images.githubusercontent.com/44714893/50548961-c547a280-0c1a-11e9-8533-4e30b3dbe23d.jpg)
(pluto on top mct on the bottom)
I'm not sure why but the last update seems to have flipped color 0 to black so the color sequences are reversed but I think you can still see whats happening. Sorry the light gray for middle-colors-twice looks so close to the white.

**Comment by duncan-d** [comment]
I think I've got it squared away except figuring out the lastLine flag. I went ahead and flipped the middle-colors-twice to start with white as well. I'm not sure when I forgot what color order the separated image was in, but it feels like white should be color 0. Partially since it's getting knitted first I would expect to see Color A. I also was expecting color 0 to be white since it feels like the background and when setting the bitarray to do extra needles outside of the start and stop needles I expected them to be selected for the white, not black pixels. The first one is probably just a matter of getting used to something that wasn't what I expected but I think the color == 0 should maybe be changed to check for color == self.__numColors - 1. I left it alone for now since I suspect it's doing the correct thing currently for 2 color Ribber: Classic

**Comment by chris007de** [comment]
Currently, ayab_image.py stores black as color 0 (https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/master/src/main/python/ayab/plugins/ayab_plugin/ayab_image.py#L99).
So I think on the long term, it should be fixed there so all knitting modes in ayab_control.py can rely on Color 0 = White.
But as I am planning to do a severe refactoring of the whole image handling functionality in ayab_image.py (e.g. to enable to show the current color in a color box on the GUI) in the release after v0.95, I propose to use your fixes for now (v0.95).

**Comment by duncan-d** [comment]
Sounds awesome! I'll get the lastLine flag sorted out and go ahead with checking for color == self.__numColors - 1 when using middle colors twice or pluto.

**Comment by duncan-d** [comment]
I think it's all set. I also noticed that depending on if an image had an even or odd number of rows the middle-colors-twice lastLine flag was wrong and I fixed that in here as well.
https://github.com/duncan-d/ayab-desktop/blob/9e9c8e515b8d9157a798b9e752ecc39e93b0dfe2/src/main/python/ayab/plugins/ayab_plugin/ayab_control.py#L592
I won't have time to test thoroughly for a few days but air knitting small images is doing what I'd expect. I definitely want to make sure infinite repeats work as expected and the block handling since I went sideways with both of those before.

**Comment by chris007de** [comment]
@duncan-d Ok, then I will wait with merging until you finished testing. My personal target to release v0.95 still in 2018 was not met anyway, so it's definitely worth waiting for your changes, no hurry.
Happy new year, by the way! :tada:

**Comment by duncan-d** [comment]
Happy new year to you!
I did some swatching this morning and the block handling and infinite repeats work worked as expected. 
Restarting the heart of pluto during a long run of infinite repeats can cause you to lose the color sequence in the backing. I think until there's a way for users to set what repeat they're on or their exact line number it's just the way it is and can be solved by using an image editor to repeat your image as many times as your project needs. I'll be sure to explain that in the documentation.

**Comment by chris007de** [comment]
Ok, sounds great. I'll do the merge.

**Comment by chris007de** [comment]
-> https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/v0.95rc3

**Comment by Adrienne200** [comment]
I have done some sampling this week, a 3-color HoP samples look good, thank you for your work on this. 
But my 4-color sample, I'm not so sure that it did it correctly. See the way that the black is doubled up on row 5, and the set of whites goes from 7 to 3 without a row were there's 5. It happened on more than one sample, I don't think it's operator error.  (The middle-twice sample looks a bit similar, but on close inspection it's just distortion of the fabric by the multiple passes, all the right stitches actually are in the right place.)
I haven't tried running this sample through Sarah's original code yet, I'll see if I can get to that this week.
![chevron 4-color 84x14](https://user-images.githubusercontent.com/24358225/50755041-97f78780-120c-11e9-8aa8-88592eb34e4c.png)
![img_0895 4-color hop](https://user-images.githubusercontent.com/24358225/50755058-a5ad0d00-120c-11e9-92f5-34def65b7385.jpg)

**Comment by chris007de** [comment]
@Adrienne200 As there should be some experience now...does this feature work as expected?

**Comment by X-sam** [comment]
@Adrienne200  thinks it miiiight be funny with 5+ colors, but we're gonna call that out of scope for 1.0.0
