### ISSUE TITLE
The Mac patterns are buried inside the ayab.app package

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#276]
Previous versions created an AYAB folder in Documents and put the patterns there. Now you have to drill into the package contents. is that a necessary side-effect of the drag-drop install? We could just document that you have to copy the folder out.

**Comment by chris007de** [comment]
For now, the quickest solution is to document the current state. :-/

Then, we have to think of a convenient way to handle this, e.g.:
* Providing the pattern as a separate archive to download on the homepage, so Mac users can download it and save it to their documents folder. In the future, the software will remember the last pattern folder location even after restarting the program, so after choosing the Documents folder (or any other), you'll not start inside the package contents again.
* Alternatively, we could evaluate if it is possible to include the pattern folder into the DMG, next to the AYAB app, so users can drag-and-drop it out of the DMG and drop it to a custom location, just like the AYAB app. Perhaps it is even possible to add the user's Documents folder as drop location, just as the Applications folder is normally shown as drop-location for the app.

**Comment by t0mpr1c3** [comment]
Proposed solution https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/289
