### ISSUE TITLE
add default instructions

### ISSUE THREAD

**Issue by niccokunzmann** [AllYarnsAreBeautiful/ayab-desktop#28]
add the default instructions form the wiki to the knittingpattern library
also add bindoff and knitstart

**Comment by niccokunzmann** [comment]
working on it in branch [add-default-instructions](https://github.com/AllYarnsAreBeautiful/knittingpattern/tree/add-default-instructions). 
TODO:

- [ ] one most common bindoff
- [ ] one knitstart instruction

**Comment by kirstin** [comment]
I added bind off and cast on to the instructions and tested them.
