### ISSUE TITLE
Maintain translation files for German

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#281]
The translation files for German are badly out of date. Some labels in the UI are not prepared for translation.

**Comment by t0mpr1c3** [comment]
I'm afraid that my recent additions have not helped matters, because the new UI stuff is written as Python instead of Qt XML.

**Comment by chris007de** [comment]
I'd say this is solved by the new translator feature by @t0mpr1c3
