### ISSUE TITLE
On Mac, the Knit button remains grey

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#282]
On Mac, after you click Configure, the Knit button doesn't come alive, it remains greyed out. You can click it and it does what it's supposed to, it's just that the visual is wrong. On Windows the button comes alive as expected.
Mac is also a bit finicky about the UI coming alive after you cancel knitting. Again, everything is functional, it's just the visuals.
0.95 RC3 and earlier

**Comment by chris007de** [comment]
https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/v0.95rc4

**Comment by chris007de** [comment]
I do not know if this solved the issue, had no time to test it on macOS so far. But that's the most obvious reason why this may happen.

**Comment by Adrienne200** [comment]
No, button is usually still grey. And the Cancel Knitting button has changed. Cancel still works, you can choose a new image and change settings, but on Mac the display now doesn't say Knitting Cancelled.

**Comment by chris007de** [comment]
This needs more investigation...and I dont' have an idea what causes the issue, yet.
Therefore, we'll document is at "known issue" in v0.95.

**Comment by t0mpr1c3** [comment]
Closed for 1.0.0 release, because the Configure button has been removed.
