### ISSUE TITLE
Windows Defender claims that AYAB contains a trojan.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#284]
A Windows Defender scan decided that AYAB.exe is a Trojan and quarantined it. I restored it and all is well; subsequent scans are not complaining, but I think that's because I allowed it before.
The supposed Trojan is called Cloxer.D!cl. Looking it up on Microsoft's site, it just goes to a generic page describing their AI virus-detector, implying that this isn't a real known trojan, it just got flagged by their automated system. There's a system to send in your exe to get it verified as clean. 
<img width="460" alt="trojan2" src="https://user-images.githubusercontent.com/24358225/50951803-5876a880-1463-11e9-93e4-431fad541281.PNG">
<img width="475" alt="trojan1" src="https://user-images.githubusercontent.com/24358225/50951804-5876a880-1463-11e9-9d50-7689c45d273e.PNG">

**Comment by chris007de** [comment]
Ok, if this occurs in the final build also, we will submit it to their page to prove it's clean.

**Comment by t0mpr1c3** [comment]
Closed for 1.0.0 release
