### ISSUE TITLE
Windows installer doesn't make a shortcut on the desktop

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#285]
Previous versions of the installer offered to make a shortcut. Now it doesn't. We could just document how to make a shortcut, or pin to the taskbar.

**Comment by chris007de** [comment]
https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/v0.95rc4

**Comment by Adrienne200** [comment]
Works in 0.95 RC4.
