### ISSUE TITLE
Windows 0.95RC4 uninstall deletes everything in the AYAB folder, including user files

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#287]
Windows uninstalls generally leave behind any files that were not placed there by the install, or had been updated by the program or the user since the install. 
At 0.9 we could do this on Win10:
1. Copy a pattern file of your own into C:\AYAB\Patterns
2. Knit something, or at least configure and start, so there's activity in the log file.
3. Uninstall
C:\AYAB is still there, containing ayablog.txt and the hand-copied pattern file.

But with 0.95
1. Install 0.95RC4
2. Copy a pattern file of your own into C:\AYAB\Patterns
3. Knit something, or at least configure and start, so there's activity in the log file.
4. Uninstall
The entire C:\AYAB folder is gone, including the log file and any user files.

**Comment by chris007de** [comment]
As it is not a good style to store user data in the program folder anyway (and if you are storing it in C:/Program Files or Program Files (x86) Windows does not allow it per default), we should pursue to store patterns in the user's home directory on the long term (#289)
The log file should be stored in the %AppData% folder.
-> Handling this in documentation right now.

**Comment by chris007de** [comment]
Will be solved within #289
