### ISSUE TITLE
Windows dirty install from 0.9 to 0.95

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#288]
If you install 0.95RC4 without uninstalling 0.9, things sort of work, but sometimes it doesn't start to knit, or fails to click up to row 2, or other indeterminate behavior. 

Steps, Windows 10:
1. Uninstall all AYABs
2. Install 0.9
3. Start up, load an image, click Configure
(I had 0.95 firmware loaded, so it's expected that it failed to knit here, not important for this test)
4. Close AYAB, but do not uninstall 0.9.
5. Run the installer for 0.95RC4
6. Flash the 0.95 firmware if you haven't already
7. Load an image and start to knit. Just 2-color single bed.
I saw various weirdnesses here:
failure to respond to crossing the magnet, no triple-beep
or if it did respond, it might not select row 1
or select row 1 but not click up to row 2 until I crossed the right magnet.
or sometimes it behaved correctly.

And we have both versions listed in Control Panel/Uninstall. Not a surprise, we changed to a different install mechanism so it has a new GUID.
<img width="640" alt="dirty install 0-9 to 0-95rc4" src="https://user-images.githubusercontent.com/24358225/51806336-bfe77300-222d-11e9-9a58-038eca2f3f54.PNG">

What to do?
Document it - instructions that tell users to uninstall the old version, or
Have the installer check for the old version and:
 pop a message telling the user to uninstall
 do the uninstall automatically? (only if it can leave behind any user files)
Or if it used the same GUID as the old one, would it do the right thing automatically?

**Comment by chris007de** [comment]
I never thought of this :D 
I think as this is only a problem of limited period (and I do not have an easy/reliable technical solution for this at hand), we'll handle this by documentation.
I'll add static information about this at the first page of the installer, hoping that people are reading it.
