### ISSUE TITLE
Store patterns in the home directory

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#289]
Check if it is possible to create a pattern directory in the user's home directory and use this by default, so the users are not tempted to store their patterns in the program folder.

- [x] Linux
- [x] WIndows
- [x] macOS

**Comment by t0mpr1c3** [comment]
When we implement a Windows installer, perhaps we can have the installer suggest a new folder where the default patterns can be installed and new patterns saved.

**Comment by t0mpr1c3** [comment]
e.g. ```os.path.join(os.path.expanduser('~'),'ayab`)```

**Comment by t0mpr1c3** [comment]
This action should probably be part of the `setup-environment.sh` script, I think.

**Comment by chris007de** [comment]
> This action should probably be part of the `setup-environment.sh` script, I think. (#375)

Not sure if this works...as far as I understand our current structure, the setup-environment.sh script has to be run after git clone to get a working environment (generate files etc.). But when using the Windows Setup or macOS App, the program files are copied to a certain place on the computer and setup-environment.sh is never called (it's not even part of the distributable).
So I think the pattern folder in the user directory should be maintained either by the setup (which is not existing for macOS), or by the runtime itself...please correct me if I'm on the wrong track.

**Comment by t0mpr1c3** [comment]
> > This action should probably be part of the `setup-environment.sh` script, I think. (#375)
> 
> Not sure if this works...as far as I understand our current structure, the setup-environment.sh script has to be run after git clone to get a working environment (generate files etc.). But when using the Windows Setup or macOS App, the program files are copied to a certain place on the computer and setup-environment.sh is never called (it's not even part of the distributable).
> So I think the pattern folder in the user directory should be maintained either by the setup (which is not existing for macOS), or by the runtime itself...please correct me if I'm on the wrong track.

Yes, you are right.

Perhaps it is easiest to do this inside the application when initializing the app context (i.e. in `main.py`).

**Comment by chris007de** [comment]
Nice to have the patterns automatically copied to the home folder when starting for the first time. (introduced with #397).

But how to handle situations when we have an updated version which brings new/altered patterns? Currently, in this case, nothing would happen because the ~/AYAB folder already exists.
Is that desired? Or do we want to perform a copy in this case to update the patterns?

**Comment by t0mpr1c3** [comment]
Yes, the check is very crude at the moment. It would be better to have a proper method of updating.
