### ISSUE TITLE
machine problem brother kh_910, 

### ISSUE THREAD

**Issue by funckychickie** [AllYarnsAreBeautiful/ayab-desktop#291]
I've got a problem with the machine itself.

i knit with a brother  kh910.
When you hit the knit button in the ayabsoftware, you have to init the machine. By moving the carriage sometimes AYAB says knit, sometimes it won't click. Sometimes it starts working immediately, sometimes it takes several moves past the left mark.
Unsure what causes this problem and how to solve it.

Seems to be a problem with the brother machine and the carriage.
Software works fine.
Anyone a suggestion what it might be?

**Comment by DerAndere1** [comment]
It might help to wait for 3 seconds after moving the carriage past the left Hall sensor. If not, you could check if the carriage sensor magnet in the carriage is still placed correctly. Maybe the Service manual or  http://hannahnapier.co.uk/2015/02/understanding-the-brother-electronic-knitting-machine/manual helps.

**Comment by DerAndere1** [comment]
You may also want to verify that there is an intact electical connection (intact insulation, no bad contacts) between the AYAB hardware and the left Hall sensor (the cable labeled "S7").

**Comment by DerAndere1** [comment]
@funckychickie :  the [service manual can be downloaded here](http://machineknittingetc.com/brother-kh910-service-manual.html?fbclid=IwAR07C8h6YGx4jEiyWAorqU7ThHIcd73vexKaSbFRgOLEZ5eifY8JM2vMRZo). Check voltages of L&R position sensors as described on p24 - adjust the voltage until it fits the specifications by turning the small blue potentiometers that are mounted on the hall sensor circuit boards.

**Comment by chris007de** [comment]
@funckychickie Any news on this issue?

**Comment by Rixstaa** [comment]
Is there a Arduino compatible hall sensor for s7 on ayab? That will work? Could ky-024 be used?
Thanks

**Comment by t0mpr1c3** [comment]
AYAB works with the original Hall sensors, so you're on your own with that
project.
