### ISSUE TITLE
crashes on MAC while knitting - crash with DBJ with 5 or 6 colors

### ISSUE THREAD

**Issue by dyqally** [AllYarnsAreBeautiful/ayab-desktop#292]
was trying double bed 6 color knitting, knitting first row and everything was fine, but when it comes to Color E, the software crashed and quit accidentally.

**Comment by chris007de** [comment]
Hi, sorry for the late reply...could you please supply the pattern file you used for knitting and the exact settings you used?

**Comment by Adrienne200** [comment]
I just tried this - oh, I must have had never tried more than 4 colors. 
On Mac or Windows: Set AYAB to Ribber-classic and 6 colors, give it any image of 2 or more colors and start air-knitting. 6 colors is 12 passes just to do the first row, and as soon as it gets to Color E the program crashes.  I'll put together a 6-color sample, but I don't think you need it to see the crash.

(Personally I don't think I'd ever knit more than 4 colors, that's already 8 passes per row in classic, and 4 makes a thick fabric, 6 would be like making cardboard, and be impossibly slow. Though I have seen one person post a 6-color sample (not AYAB) so I could be wrong, maybe there's a use for it.)

**Comment by Adrienne200** [comment]
This crash appears to be gone. I have briefly tested 5 and 6 color DBJ in the 1.0 Mac build from June 26th, 2023, and the Windows build Aug 8th 2023. No crash.
