### ISSUE TITLE
KH-920 + KG-93 + AYAB = won't working

### ISSUE THREAD

**Issue by Ilushock** [AllYarnsAreBeautiful/ayab-desktop#293]
Hi! Image doesn't upload to the machine on the right turn. The shield doesn't "beep" at this moment.

Maybe I can use AYAB shield as BrotherLink cable to connect with DesignaKnit software? If it's possible, what I have to do?

**Comment by Adrienne200** [comment]
AYAB does not work with the garter carriage (KG) yet. See
https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/2
Is the patterning working for you otherwise?

There is no way that I know of to connect AYAB to DAK.

**Comment by Ilushock** [comment]
>> Is the patterning working for you otherwise?
That's OK. But we want more-more-more )))

**Comment by chris007de** [comment]
Duplicate of https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/2
