### ISSUE TITLE
Serial communication problem

### ISSUE THREAD

**Issue by san3** [AllYarnsAreBeautiful/ayab-desktop#295]
Hi,

I recently tried to update to the .95 version coming from something around 0.90. (Using win10, atmega2560 clone and selfbuilt shield with kh-910) But neither my own compile nor the precompiled firmware seem to be able to communicate with ayab-desktop: it remains stuck at the "Connecting to machine..." message, waiting to receive the cnfInfo of the arduino.
Tried a few other shieldless atemga2560 with the same results.
Any ideas ?

Regards,
san

**Comment by chris007de** [comment]
Did it work with 0.90 with the same setup (Win10, same Arduino)?
Do you have an Arduino Uno at hand to test if it works with it?
Do you have any possibility to test the serial communication between your computer and the Arduino (e.g. running the Serial Example from Arduino IDE)?

**Comment by san3** [comment]
Thanks for your reply. 
Version 0.90 was and is working in the same setup - i reverted to it after setup of 0.95 failed. Initially (~5 years ago) I modified the shield slightly to work with the atmega2560 (the pins utilized for I2C are located elsewhere if i remember correctly), therefore I am unable to test with the uno - at least for now. Normal serial communication seems to work fine though - I am able to knit with version 0.90. To me it seems as if the problem is somehow associated with packetserial  - maybe with a timeout issue ? I don't seem to be able to run the basic "PacketSerialReverseEcho"-example of packetserial on any of my atmega2560. 
(Not sure if it helps: While trying to initiate ayab desktop with the knitting machine I found a strange glitch:  by fiddling with the RX/TX pins on the arduino-board while the ayab-desktop constantly tries to connect occasionally there is a correct answer from the firmware("API v5, FW v0.95")  leading to a correct initiation)

**Comment by chris007de** [comment]
Thanks for the explanation - I guess your presumption goes in the right direction. From 0.90 to 0.95, we changed the code for the serial communication. The intention was to make it faster and more reliable, but perhaps you found an issue with the new implementation.

> (Not sure if it helps: While trying to initiate ayab desktop with the knitting machine I found a strange glitch: by fiddling with the RX/TX pins on the arduino-board while the ayab-desktop constantly tries to connect occasionally there is a correct answer from the firmware("API v5, FW v0.95") leading to a correct initiation)

This might point into an direction...obviously the serial buffer is not read until you are "accidentially" creating additional characters. I'll have a look into the code, perhaps I'll find the reason, or I can provoke the error.
In the mean time: Do you have some experience with python and could play around with the serial [timeout value](https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/master/src/main/python/ayab/plugins/ayab_plugin/ayab_communication.py#L54)?

**Comment by san3** [comment]
I will have a look at it.

**Comment by chris007de** [comment]
Thanks a lot for the feedback. Very interesting that a timeout of 0.1 works on most(?) systems and on your system (and probably others) it's too hard.
Do you experience a lag during knitting when setting the timeout to higher values or is it ok with i.e. 1sec?
And I guess setting timeout to 0 also does not work on your setup, right?

> But even a timeout of 5.0 s requires two attempts.

That's expected, as the Arduino restart every time the Serial connection is re-opened (it uses RTS/DTR for auto-reset), it needs a short time to boot until it is able to reply. In an older version of ayab-desktop we had a delay after opening the Serial connection to take this into account and send the reqInfo message after 1 sec or something, but as the Arduino might already be ready after 0.x seconds, we removed this delay and poll until it is available.

**Comment by san3** [comment]
Sorry to report: I just tried to knit with the new timeout settings and there seems to be something more amiss. Even when using the "most conservative" timeout settings of 5 sec, the software gives me the error: "Device not ready, configure and try again" after crossing the left hall-sensor.
