### ISSUE TITLE
View and load DAK files

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#298]
A partial disassembly of the Silverknit Utility has resulted in some code to convert .stp files into .png format, at least where the stitch pattern is uniform: https://github.com/gbl/D7CReader

It should not be a huge job to extend this code to the simpler D4C/D46 .pat formats.

This could be the basis for a new feature to be able to view and load DAK files directly into AYAB without first converting to an image file.

**Comment by t0mpr1c3** [comment]
The same also goes for the other file formats that Silverknit Utility supports.

**Comment by chris007de** [comment]
Let's see how we could include this converter into AYAB...currently it's written in Java, it may be worth to port it to Python for easier integration into the AYAB-Desktop software.

**Comment by t0mpr1c3** [comment]
Yes I agree

**Comment by Adrienne200** [comment]
Do you have permission from the folks at DAK for this? I don't think it's a good idea to incorporate an active hack of someone else's proprietary file format into AYAB, and IMO we should not do it. 
The machine knitting community is small and connected, and DAK has a loyal fan base. I foresee a big argument developing, which we could avoid by not doing this. Arguments about copyright and intellectual property get very ugly.
Of course if you have permission, or if this format is public domain and I didn't know, then cool, go right ahead.

**Comment by oskay** [comment]
It's an excellent point to raise.

**Comment by t0mpr1c3** [comment]
I have no particular knowledge of intellectual property law. AFAIK the code originates from a disassembly (hack) of Silverknit Utility which is distributed by a Dutch company presumably owned by Jos Timmermans. I don't know if Silverknit Utility is patented in Europe or anywhere else. But if there is any permission required I would guess that it would be required from him and not from SoftByte, the British distributors of DAK.

**Comment by t0mpr1c3** [comment]
In any case a better way of achieving the same goal might be to ask SoftByte to provide specifications of these file formats for the purpose of achieving software compatibility. A case can be made that it is in their own interest to do so.

**Comment by t0mpr1c3** [comment]
e.g.

For the attention of Matthew Bragg, Proprietor

Dear Sir

I am writing on behalf of AYAB, a collaborative open source project that aims to allow the owners of knitting machines to control them by electronic means (https://ayab-knitting.com/). We have written software that allows users to convert digital image files into machine instructions via a hardware interface.

We would like to extend this functionality to .pat and .stp files created by your Designaknit software, so that AYAB users can create patterns using Designaknit and export them directly into the AYAB software. Designaknit users are currently performing tedious workarounds involving screen shots and image manipulation to accomplish this goal. We feel that this lack of interoperability diminishes the usefulness of both Designaknit and AYAB.

We would like to request that you provide us with some limited specification of the .pat and .stp file formats sufficient to allow patterns in these formats to be rendered as colour images. We note that freely distributed software available from a third party (Pattern Explorer, http://www.silverknit.nl/download/) already provides this functionality.

Cordially...

**Comment by t0mpr1c3** [comment]
A third option might be to package open source file conversion software entirely separately from AYAB. This diminishes the prospects for complete interoperability but hives off potentially contentious issues to a separate project.

**Comment by t0mpr1c3** [comment]
This third option already exists albeit in the currently inconvenient form of the D7CReader repo

**Comment by t0mpr1c3** [comment]
This blog post discusses how to turn captured images into digital files suitable for AYAB/img2track http://alessandrina.com/2018/07/02/numbers-to-gimp-to-create-images-for-electronic-download/

**Comment by chris007de** [comment]
I share Tom's view on the "copyright" issue - but I am not a lawyer also. I think supporting this format does not do any harm to the company and the sales of their software - and I do not think AYAB is a "competitor" to the company anyway.
For my understanding, supporting a foreign format is not an illegal act per se. Otherwise, Open/LibreOffice might not be able to open files in Microsoft formats (I guess there are many other examples for such a situation).
When porting this converter to python, it should be done in a separate library anyway, so we have a comfortable way to leave it out of the main software if problems arise.
But well, as this is a community driven project, we all have to be ok with this...so feel free to veto.

**Comment by oskay** [comment]
https://stackoverflow.com/questions/121208/is-it-legal-to-reverse-engineer-binary-file-formats

>  In the EU it is specifically permitted (article 6 EU software convention) to "reverse engineer file formats for the purpose of interoperability"

> If you live in the US, the DMCA generally prohibits reverse engineering if you have to circumvent a "copy protection technology" to do so, but it makes specific exception for cirucumventing it for the purpose of making something compatiable with the format.

So (and IANAL as well...) in the EU, this looks obviously OK.

A valid question (for US people) then is whether the encryption in the DAK file format is regarded as "copy protection."  My instinct on it is that this is "market protection" rather than copy protection, as it is an impediment to easy interchange, but that the encryption does not prevent access to use or copy (and overriding does not grant access to use or copy) the DAK software.


https://en.wikipedia.org/wiki/Proprietary_format

> [...] reverse engineering of file formats for the purposes of interoperability is generally believed to be legal by those who practice it. Legal positions differ according to each country's laws related to, among other things, software patents.

As @t0mpr1c3 noted, patents are a potential obstacle, if the file format were patented (I haven't checked.) But otherwise, it looks to me like reverse engineering a *file format alone* for the sole purpose of interoperability is generally acceptable.

**Comment by t0mpr1c3** [comment]
I can't find any patents, Windell, but I haven't looked exhaustively. I'd trust your legal intuition over mine.

Adrienne raised a second point relating to keeping neighbourly community relations, which I think we should also consider. In my view, SoftByte shows more concern to protect their market position than update their product for the benefit of knitters. So I could care less about yanking their chain. Silverknit seems more innovative. Does anybody know Jos Timmermans?

**Comment by t0mpr1c3** [comment]
I've hacked out some Python code to convert .PAT files to .PNG. I'll have a go at converting the Java code for .STP files, too. Both bits of code are useful only to view colourwork. Neither recognise different stitches.

**Comment by t0mpr1c3** [comment]
I'm developing the code at https://github.com/t0mpr1c3/DAKReader. The basic STP/PAT -> PNG conversions more or less work. In the repo there is also an IDA database with my annotations of the decompiled Silverknit code. It's all very rough. I don't really know how to go about putting it in a form that would be useful for AYAB and would welcome any comments or suggestions that you may have.

**Comment by chris007de** [comment]
> I'm developing the code at https://github.com/t0mpr1c3/DAKReader

Wow, looks like a bunch of work...

> I don't really know how to go about putting it in a form that would be useful for AYAB and would welcome any comments or suggestions that you may have.

I would propose to add a method like "get_xxx()", where xxx is an object/array/buffer which can be fed into one of the Pillow image construction methods (see https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.fromarray and following).
As we are handling knitting pattern as PIL image internally https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/3a6a320a9e60eec5149a879dff25d73e5ba9dd9e/src/main/python/ayab/ayab.py#L371 we could call your module here instead, which would enable us to use the data from the DAK files directly in our existing code.

**Comment by t0mpr1c3** [comment]
Thanks -- that's very helpful indeed.

It was my first time decompiling something. It took me a while because I was not familiar with x64 assembly code.

I'm not familiar with Pillow either, but I'll have a go at it.

By the way, where in Germany are you?

**Comment by t0mpr1c3** [comment]
Another question: apart from .pat and .stp files, what other formats that SilverKnit can handle are worth converting? I figure .bmp is easy enough. I also see .txt, .dat, .stc, .pbm, ... but I don't really know what other formats people actually use.

**Comment by t0mpr1c3** [comment]
Chris, I renamed the repo https://github.com/t0mpr1c3/DAK2im. The DAK2im class has two methods pat2im and stp2im which read a DAK file and return a PIL.Image object.

**Comment by chris007de** [comment]
Ok, so what is left to do is to include your library and check for the file extension when loading a file, then call the appropriate method to get a PIL object.
Feel free to implement, I'll set up a `v1.0-dev` branch for this. (yes, we are on our way to something like a "1.0")

**Comment by t0mpr1c3** [comment]
Chris, I've package the code in PyPi and had a go at making the necessary changes in requirements.txt and ayab.py (https://github.com/t0mpr1c3/ayab-desktop/commit/b12655d0a5982d802d2e3cd80e7c2dd046369fb0). Could you give me some quick pointers on how to do the build so that I can test it. Thanks.

**Comment by chris007de** [comment]
You can run the software with `python3 -m fbs run` when in the root folder of the repository.
To build an executable, please see `linux-build/build.sh` (or mac-build/ oder windows-build)

**Comment by t0mpr1c3** [comment]
Tested working on linux, new pull request https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/305

**Comment by chris007de** [comment]
Thanks a lot for the PR :partying_face:
