### ISSUE TITLE
Add "Simulation" mode

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#300]
Currently, the only way to test the behavior during knitting is to actually knit or use an Arduino with a special firmware.
To ease testing of the software, and to enable "dry-runs" for the users, it should be possible to "simulate" knitting.
To achieve this, the serial communication module shall be replaced by a mockup communication module in the case of simulation.
The mockup communication module anwers the commands as if the machine was connected.
There should be some kind of delay parameter which delays the send of reqLine messages, so the simulation speed can be throttled.

**Comment by chris007de** [comment]
Add an additional entry in the serial port list: "Simulation" which will run the knitting without a machine connected.
Currently it just runs as fast as it can so we can evaluate the output of the knitting data in the log file.
We could think about throttling it by pressing a key to advance to the next rows so the user is able to check if everything would happen as expected... @Adrienne200 ?

**Comment by Adrienne200** [comment]
Is there a build that contains this fix?

**Comment by chris007de** [comment]
> Is there a build that contains this fix?

Hi Adrienne, there is no build containing this fix, yet. I'll trigger a build during this weekend.

**Comment by t0mpr1c3** [comment]
What exactly does the test firmware do -- serial communication only?

**Comment by chris007de** [comment]
> What exactly does the test firmware do -- serial communication only?

The test firmware for the Arduino offers the possibility to advance a row by pressing a button attached to the Arduino. No machine is needed for this.
This simulation feature eliminates the need for a Arduino completely. The AYAB GUI sends its serial commands to a serial mockup library which behaves like an Arduino. Row advances are currently done automatically with no delay, so it just runs through the pattern until the "knitting" is finished and you can check the log output if everything has happened correctly (or if the program would have crashed during knitting).

**Comment by t0mpr1c3** [comment]
I suggest that the AYABCommunicationMockup class should inherit from AYABCommunication. I have requested this change as part of https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/328.

**Comment by t0mpr1c3** [comment]
Currently I am implementing a Knitting Progress window that shows the yarn colour and needle positions for each pass of the carriage. For the purposes of debugging the GUI, it is useful to have the simulation delay during initialization and between lines. I suggest that this is a useful feature and that we could keep as an option.

**Comment by chris007de** [comment]
As we are using this excessively during development, I'll close this as fixed.
