### ISSUE TITLE
Refactor/Implement unit tests for ayab_control::__cnfLine

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#301]
To start out with the refactoring of the code and implementation of unit tests, we should make the cnfLine() method testable, as it is the heart of the software and yields a lot of possibilities for bugs and malfunctions.

**Comment by t0mpr1c3** [comment]
__cnfline() really needs to be broken up into smaller component functions. These would be much easier to test, and would facilitate code reuse.
