### ISSUE TITLE
Fix github security alerts

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#302]
Currently, we have security alerts for PyInstaller and pillow.
Update the dependencies to the latest versions, but at least to the recommended versions.

**Comment by t0mpr1c3** [comment]
I'm not getting these alerts for the 1.0.0-dev branch. Does this mean that the dependency issues are resolved going forward?

**Comment by chris007de** [comment]
> I'm not getting these alerts for the 1.0.0-dev branch. Does this mean that the dependency issues are resolved going forward?

I updated most of the dependencies in e8f3b4fce70e67462f1cae708996b83cac7ce21c on 1.0.0-dev, which should have silenced these warnings for that branch (for now).
