### ISSUE TITLE
Set up Github actions for building AYAB

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#310]
- [x] Linux
    Github Runner: 18.04, 20.04
- [x] Windows
    Github Runner: Windows Server 2019
- [x] macOS
    Github Runner: macOS 10.15

https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners

Notes:
- We have to check if build under Windows Server 2019 is executable under Windows 10 properly.
- If we build under macOS 10.15, the system we will run the software has to be at least 10.15 also. Therefore, we might want to set up a custom runner with an older version of macOS for better compatibility with older devices.

**Comment by t0mpr1c3** [comment]
I really don't know a whole lot about this, but if you give me some pointers I could start on the Linux.

**Comment by chris007de** [comment]
In general, Github actions work a lot like Travis CI, Appveyor etc.
There is one more more a "workflow" files which describes what happens when certain actions occur in the repository.

Here you can find our workflow file for the automatic run of the pytests on each PR or push to a branch: https://github.com/AllYarnsAreBeautiful/ayab-desktop/actions/runs/138826515/workflow
So basically the yml file describes the triggers and what happens subsequently. It is stored in the repo under .github/workflows

Here, I began setting up the action for the Windows build:
https://github.com/AllYarnsAreBeautiful/ayab-desktop/actions/runs/137632800/workflow

For each OS, the basic flow is the same:
- checkout the code
- install prerequisites
- run `python -m fbs freeze` to build binary
- build installer with `python -m fbs installer` (Builds a Setup for Windows, the App for macOS, to be skipped for linux)
- deploy artifacts
- If commit was tagged: create a github release and attach the artifacts to the release
  - bonus: upload to pypi

For the 0.95 release, we used Gitlab pipelines with self-hosted Gitlab runners (virtual machines on my computer) to do this (see gitlab.yml and the build scripts in the linux-build, macos-build and windows-build folders) in the root folder), but as Github added actions as a feature in the mean time, we may switch over to Github actions. So we would be no longer depending on my Gitlab/Virtual Machine runner setup :)

**Comment by t0mpr1c3** [comment]
I really don't know much devops, but the documentation looks pretty good. I would imagine Windows is the highest priority. Although I do I have a Windows 10 box I haven't attempted a build yet.

Off topic but I think the GUI looks better in Ubuntu than Windows.

**Comment by chris007de** [comment]
The Windows build works.

In general, I still have to find out how to attach the artifacts to a Github release automatically, in case pushed commit was tagged (with Travis, this was very easy...).

What do we want to "build" for Linux? Does a binary/frozen version even make sense here?
Or deploy to PyPi? Or pursue #278 ?

macOS will take me some time, because I have to set up a 10.15 environment for testing first...

**Comment by t0mpr1c3** [comment]
That's awesome. Windows is 80% of people. Eventually it would be nice to have Mac support.

I'm not so bothered about Linux binary releases. Personally I would push to PyPi because it is easy and I would likely run it from the CLI anyway.

**Comment by t0mpr1c3** [comment]
Scripts done for Ubuntu and OSX. Still working on AppImage.

**Comment by t0mpr1c3** [comment]
> In general, I still have to find out how to attach the artifacts to a Github release automatically, in case pushed commit was tagged (with Travis, this was very easy...)

See https://github.com/trappitsch/fbs-release-github-actions

**Comment by t0mpr1c3** [comment]
By the way, what motivated the transition from Travis?

**Comment by chris007de** [comment]
> By the way, what motivated the transition from Travis?

Travis is a good tool, but they provide outdated software on their runners and are pretty slow in catching up to current versions.
Plus, they don't provide a runner for macOS.
I liked the idea to have a integrated solution on the Github platform, plus the extensibility provided by the Github actions, which makes it pretty versatile.

**Comment by chris007de** [comment]
lgtm, let's address any details in separate issues
