### ISSUE TITLE
Implement CRC8 for cnfLine message

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#311]
add a CRC8 on bytes 0-28 of the cnfLine message, so the Arduino can check if the line data is correct and re-request in case of failure (https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/v1.0-dev/src/ayab/serial_encoding.cpp#L129)

**Comment by t0mpr1c3** [comment]
Currently the device does not signal checksum errors, or any other kind of error, in cnfLine.

Nor does the host check for an error and repeat the reqLine message if an error is detected.

**Comment by dl1com** [comment]
Implementation is done, closing.
