### ISSUE TITLE
Restarting where you left off after cancelling knitting

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#337]
Would it be useful to be able to restart knitting where you left off, after cancelling? The action would essentially set AYABControl.__startLine to the last line that was actually completed plus one. It could be implemented by having the action of the "Cancel Knitting" button change to "Restart Knitting".

**Comment by chris007de** [comment]
May be related to #129

**Comment by t0mpr1c3** [comment]
OK, how about renaming the "Cancel knitting" button "Stop knitting". When you hit it, the button text changes to "Restart". Pressing "Restart" begins knitting the same pattern with `startLine` set to the last value of  `imgRow`. This would create a "Pause" function without adding a new button in the UI or too much overhead in the UI behaviour.

**Comment by chris007de** [comment]
> OK, how about renaming the "Cancel knitting" button "Stop knitting". When you hit it, the button text changes to "Restart". Pressing "Restart" begins knitting the same pattern with `startLine` set to the last value of `imgRow`. This would create a "Pause" function without adding a new button in the UI or too much overhead in the UI behaviour.

Sounds good. Although I am not a native speaker, wouldn't "continue knitting" be more exact than "restart knitting"? (restart sounds to me like start from the beginning)

**Comment by t0mpr1c3** [comment]
> > OK, how about renaming the "Cancel knitting" button "Stop knitting". When you hit it, the button text changes to "Restart". Pressing "Restart" begins knitting the same pattern with `startLine` set to the last value of `imgRow`. This would create a "Pause" function without adding a new button in the UI or too much overhead in the UI behaviour.
> 
> Sounds good. Although I am not a native speaker, wouldn't "continue knitting" be more exact than "restart knitting"? (restart sounds to me like start from the beginning)

Native speaker or not, you're probably right!

**Comment by t0mpr1c3** [comment]
Chris, you can merge this into https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/129 if you want.

**Comment by t0mpr1c3** [comment]
Closing as a duplicate of https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/129.
