### ISSUE TITLE
Two finite state machines?!

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#338]
There is one FSM specified in https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/1.0.0-dev/src/main/python/ayab/plugins/knitting_plugin.py and another one defined by `class KnittingState(Enum)` in https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/1.0.0-dev/src/main/python/ayab/plugins/ayab_plugin/ayab_control.py

The second one seems to have been introduced more recently. Can we get rid of it? It's confusing and complicates the program flow.

I suspect that doing so will help get rid of the various crashes and glitches that tend to occur after hitting Cancel, for example https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/334#issuecomment-645445528.

**Comment by chris007de** [comment]
They do not serve the same purpose, so they are not redundant.
The state machine in knitting_plugin is a high level FSM which accounts the overall state of the software (Configured, Knitting). The second FSM in ayab_control has recently been refactored, as it has been always there but was not really recognizable as an FSM. It controls the communication between the host and the Arduino while in the (super)state Knitting.
I agree that this can be optimized - probably we can also get rid of the FYSOM dependency, as building an FSM probably does not need a library ;-)

**Comment by t0mpr1c3** [comment]
If you count the Qt event handling machinery, there are arguably 3 FSMs going on ;-) I wonder if that is actually where the problem lies.

I'm not necessarily against `fysom`. It has the advantage that the behaviour is specified in a declarative way, instead of having to follow a tangle of `if .. else` clauses.

I'm also not against having a FSM for the sole purpose of handling the serial communication if it is well encapsulated. If you have recently refactored it, then it is probably in good shape -- I admit that I haven't followed all of the logic.

**Comment by t0mpr1c3** [comment]
The problem was that the FSM in `ayab_control.py` was not being reset after cancelling, and stayed in OPERATE. I've prevented that by making a new method `ayab_control.reset()` that sets the state back to SETUP. That seems to have fixed it for now, but I haven't tested exhaustively.

**Comment by t0mpr1c3** [comment]
Do you think the Qt Finite State Machine framework might be useful instead of `fysom`? We have state changes triggered by button presses. And it would be one less dependency.

**Comment by chris007de** [comment]
> Do you think the Qt Finite State Machine framework might be useful instead of `fysom`? We have state changes triggered by button presses. And it would be one less dependency.

I can't estimate the effort to switch over to the Qt framework...if it doesn't cost you a lot of time, feel free to go for it :) I'd say if it imposes some other/new technical burdens, we could either stay with fysom or implement the FSM without any external library at all.

**Comment by t0mpr1c3** [comment]
It sounds like you are not really a fan of `fysom`, and if we get rid of the Configure button that would be one less reason to keep it.

I think I'll tinker with the Qt FSM a little and see how it behaves.

**Comment by t0mpr1c3** [comment]
It turns out the `Qt` FSM is well-suited to handling what `fysom` did. Apart from fixing the bug on Cancel, I did not change the FSM in `AYABControl.knit()`.
