### ISSUE TITLE
Progress bar is misplaced or redundant

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#344]
Now that there is a graphical progress window, should we do something about the bar underneath that shows the color and row number?

Should we move it to another part of the screen? Get rid of it entirely?

**Comment by chris007de** [comment]
All of this information is contained in the progress window now, so I think we could get rid of those two labels.

![image](https://user-images.githubusercontent.com/1631996/85203044-2d0c1480-b30b-11ea-9f5a-886167164fc9.png)


@Adrienne200, any thoughts on this?

**Comment by t0mpr1c3** [comment]
Merged into #381
