### ISSUE TITLE
Remove the Configure button

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#345]
Could we get rid of the configure button, and just automatically configure when the knit button is pressed?

**Comment by chris007de** [comment]
> Could we get rid of the configure button, and just automatically configure when the knit button is pressed?

Definitely :) I don't see any benefits from it.

**Comment by t0mpr1c3** [comment]
Should be quite a straightforward change. First task was to straighten out the FSM which I did in https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/347.
