### ISSUE TITLE
What is the expected behaviour if the distance between start and stop needles is greater than the width of the image?

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#348]
Say, if the image is 20 pixels, but the start needle is 20 orange and the stop needle is 20 green. What is knit on the flanking needles - nothing? Background colour? Does it depend on the knitting mode? And should those flanking needles also be shown in the (new) knit progress window?

**Comment by chris007de** [comment]
Current behavior is to set the flanking needles to background color.
But there is a request to alter this behavior for DBJ (#231).
From my view (without that much knitting experience), it is not necessary to show these needles in the progress window.

**Comment by t0mpr1c3** [comment]
OK, thanks. I think I will add a flag or option to show the flanking needles. It might not be necessary for knitting, but it could be useful (for debugging etc.) to check that they correctly positioned and the right colour.
