### ISSUE TITLE
Support for languages other than English and German

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#353]
I have made a spreadsheet of words and phrases that appear on screen. Anybody with the link can edit the document. Please feel free to add translations into any language that you know. When we have a complete set of translations for a new language I can make a new set of `.ts` files. I'll raise a pull request to put a master copy of the document in text format under `src/main/resources/base/ayab/translation`

https://docs.google.com/spreadsheets/d/1zocG1AvWI_4_GcY3e3HRjNxDUbwjTgygPzEigDTrcyk/edit?usp=sharing

**Comment by t0mpr1c3** [comment]
We have Icelandic!

**Comment by chris007de** [comment]
What do you think about adding the possibility to chose the language in the preferences menu? Currently, the language is chosen automatically, but I think it would still be good to be able to chose it freely as well.

**Comment by t0mpr1c3** [comment]
Yes, I think that would be a good idea.

**Comment by chris007de** [comment]
I reviewed/updated the German translation in the spreadsheet.

**Comment by t0mpr1c3** [comment]
https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/352 implements all of this. 7 different languages so far!

**Comment by t0mpr1c3** [comment]
And now we have Spanish :)

**Comment by t0mpr1c3** [comment]
Korean language font needs to be fixed https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/409
