### ISSUE TITLE
Generate qm files during build

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#354]
As the Qt translation files (.qm) are binaries, these should not be stored in version control.
They shall be generated during the build process.
For Linux users which want to run the software from a cloned git repository, they have to perform this step manually before being able to start the software (we can probably also solve this with https://build-system.fman.io/manual/#custom-commands)

**Comment by t0mpr1c3** [comment]
Ditto for `.ts` files generated by `ayab_trans.pl`.

**Comment by t0mpr1c3** [comment]
Does `lrelease` come packaged with the python install of `qt5`? Under Ubuntu, it can be installed by `sudo apt install qttools5-dev-tools` but I am not sure if it is necessary.

**Comment by t0mpr1c3** [comment]
If we eventually decide to package this for PyPi, I think you can roll `.qm` files into the package using `pyrcc5`.

**Comment by chris007de** [comment]
> Does `lrelease` come packaged with the python install of `qt5`? Under Ubuntu, it can be installed by `sudo apt install qttools5-dev-tools` but I am not sure if it is necessary.

No, it's not contained in pyqt5, it has to be installed separately. We have to adapt the github action file accordingly, as the build fails currently: https://github.com/AllYarnsAreBeautiful/ayab-desktop/runs/824004141?check_suite_focus=true

**Comment by chris007de** [comment]
For the Windows build, we might want to use https://github.com/jurplel/install-qt-action to get lrelease.

**Comment by chris007de** [comment]
We've got lrelease available now, installation of Qt only takes less than a minute :)
But: Under Windows, we cannot just run `lrelease *.ts`...

```
  lrelease *.ts
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    GIT_TAG: v0.95-79-g38af761
    pythonLocation: C:\hostedtoolcache\windows\Python\3.7.7\x64
    Qt5_Dir: D:/a/ayab-desktop/Qt/5.14.2/msvc2017_64
    QT_PLUGIN_PATH: D:/a/ayab-desktop/Qt/5.14.2/msvc2017_64/plugins
    QML2_IMPORT_PATH: D:/a/ayab-desktop/Qt/5.14.2/msvc2017_64/qml
lrelease error: Cannot open *.ts: The filename, directory name, or volume label syntax is incorrect.
##[error]Process completed with exit code 1.
```

@t0mpr1c3 Would you mind adding the `lrelease *.ts` step to your perl script?

**Comment by t0mpr1c3** [comment]
Bug fixed
