### ISSUE TITLE
a couple of formatting issues

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#360]
I don't have a strong opinion on formatting issues generally, and most things can be automated, but there are a couple of areas where I think we could use some standardization.

1. There is a mixture of private attributes needing getter and setter methods and public attributes. Some getter methods have a `get_` prefix and some don't.
2. There is a mixture of camel and snake case. I generally prefer snake case for Python, but PyQt (being C++) uses camel case.

My own preferences are
1. Use the `@property` decorator and do away with getter and setter methods.
2. I am less bothered about this, but the current mixture is a bit untidy.

**Comment by chris007de** [comment]
> 1. Use the `@property` decorator and do away with getter and setter methods.

Agree.

> 2. I am less bothered about this, but the current mixture is a bit untidy.

I'd propose to stick to the PEP8 styleguide, so snake_case for functions, CamelCase for classes, etc.


Something else:
Would be good to consolidate class names. We have
- AYABControl
- ayabImage
- AyabPlugin
- etc.

I've got no preference on this, we should just pick a common way to write AYAB in class names :)

**Comment by t0mpr1c3** [comment]
> > 1. Use the `@property` decorator and do away with getter and setter methods.
> 
> Agree.
> 
> > 1. I am less bothered about this, but the current mixture is a bit untidy.
> 
> I'd propose to stick to the PEP8 styleguide, so snake_case for functions, CamelCase for classes, etc.

Agree

> Something else:
> Would be good to consolidate class names. We have
> 
> * AYABControl
> * ayabImage
> * AyabPlugin
> * etc.
> 
> I've got no preference on this, we should just pick a common way to write AYAB in class names :)

Let's go with Camel case with initial capital, so AyabControl, AyabImage, etc.

I'll make a pull request with the changes.
