### ISSUE TITLE
Menu bar looks wrong in Windows

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#379]
This is some platform-specific Qt behaviour. The problem was introduced by my recent changes. I'll try to track the problem down.

**Comment by t0mpr1c3** [comment]
While we're on the subject of the menu bar, I prefer the menu bar in Ubuntu with `setNativeMenuBar(False)`. The downside is that it takes up an entire row of the display instead of using the system menu bar. Any thoughts on this?

**Comment by chris007de** [comment]
> While we're on the subject of the menu bar, I prefer the menu bar in Ubuntu with `setNativeMenuBar(False)`. The downside is that it takes up an entire row of the display instead of using the system menu bar. Any thoughts on this?

Personally, I do not like the Ubuntu/macOS menubars as well, so setting this to false is _perfectly_ fine for me.

**Comment by t0mpr1c3** [comment]
> > While we're on the subject of the menu bar, I prefer the menu bar in Ubuntu with `setNativeMenuBar(False)`. The downside is that it takes up an entire row of the display instead of using the system menu bar. Any thoughts on this?
> 
> Personally, I do not like the Ubuntu/macOS menubars as well, so setting this to false is _perfectly_ fine for me.

OK, I will set the menubar behaviour to be the same on all platforms.
