### ISSUE TITLE
fbs requires Python 3.5/3.6, PyQt5.9.2

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#389]
See https://build-system.fman.io/troubleshooting. In 1.0.0-dev we use Python 3.7 and PyQt5 5.14.12. We should probably roll back the versions. I haven't found major glitches in the GUI, but it may affect building standalone apps.

The Windows build specifies Python 3.7 in the github workflow, but the user instructions in `README.md` specify 3.5.3.

**Comment by t0mpr1c3** [comment]
The rolled-back install also requires `pip==18`

**Comment by chris007de** [comment]
:facepalm: When updating the requirements file, I checked so many dependencies in our required modules that I overlooked these major requirements in fbs ;) (but it worked surprisingly well with python 3.7 and qt 5.14 so far ;) )
Thanks for double checking!

**Comment by t0mpr1c3** [comment]
I was under the impression that Debian bullseye repos have already migrated to Python 3.8, but I could be wrong.

I agree that using the unsupported versions has worked out pretty well so far.

According to [this comment](https://github.com/mherrmann/fbs/issues/61#issuecomment-535555156), `fbs freeze` is particularly version-sensitive. That is mainly why I am concerned to roll back to 3.6 right now. (By the way, I just got a Ubuntu/Debian installer building successfully on the github workflows.) Personally I would like to take things one step at a time and get the installers up and running first, and then try to roll forward to 3.7 if we need to.

**Comment by chris007de** [comment]
> I was under the impression that Debian bullseye repos have already migrated to Python 3.8, but I could be wrong.

Yes, you are right - 3.7 and 3.8 are available there.

> Personally I would like to take things one step at a time and get the installers up and running first, and then try to roll forward to 3.7 if we need to.

Sounds reasonable. Let's go with 3.6 and check if we can bump to 3.7 when everything is up and running.
