### ISSUE TITLE
Checklist for 1.0.0 release

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#401]
I feel we are approaching a decision point where it would be useful to consider which changes should be included in the 1.0.0 release and which can usefully be postponed or are no longer a priority.

I have gone through the open issues labelling issues with milestone 1.0.0 that I think we can get around to. Issues that we cannot get around to, but should document as known issues, I have marked with milestone 1.0.0 and the documentation label.

Amongst others, I would like to postpone changes to the pattern format #299, displaying memo data #250, automated changelog reader #392.

Known issues we should document include #142.

Issues I am not sure about include #128, #247.

**Comment by Adrienne200** [comment]
Thanks so much for all the hard work that's been happening recently. Is there a test build I could try? (Mac or Windows.) I think you've already addressed many of the issues on my fix list, then I can add my opinions about what's left.
I tried the current release link test-20202207j from 2 days ago, on Mac. But it wouldn't load an image so I didn't get far.

**Comment by t0mpr1c3** [comment]
Oh no! I'm sorry about that. I haven't tried out that Mac version at all. I should do some testing.

It would be really helpful if you could try out a new version. There have been a lot of changes. I pushed a new version https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/test-20202407

**Comment by t0mpr1c3** [comment]
@Adrienne200 by the way, I think the Mac OSX .dmg requires version 10.15.

**Comment by Adrienne200** [comment]
At first test-20202407 wasn't working anywhere. Then while experimenting with the command line on Catalina I got it to tell me that it was missing a resource called "patterns". So I created a folder Resources/patterns inside the package (which it let me do because it isn't signed yet) and then it started to work. The same hack got it going on Mojave (10.14.6) as well. It was the absence of the patterns folder that was causing it to not bring up the dialog for choosing an image.

Same on Windows10. My first try was as as a non-admin user and it wanted to install into AppData. Not a good idea, but we can leave that aside for now and work with Admin users. The default install path for an admin user is Program Files(x86)  But it's a 64-bit app, right? So I put it in Program Files. Running from the command line showed that it was complaining about the same thing; I hand-created a folder "Program Files\AYAB\patterns" and now it launches and runs.
I haven't hooked either computer up to a knitting machine, so no firmware or actual knitting has happened yet. Probably Saturday (I'm in Pacific time.) 
I see lots of good changes, loving the simulation. I'll have some comments of course, but the basics of the feature looks great. Other places too - nice new features and lots of rough edges.

**Comment by t0mpr1c3** [comment]
Great, Adrienne, thanks so much! I am thrilled you got it working. As you say, there are a lot of rough edges and it badly needs a fresh set of eyes on it.

**Comment by chris007de** [comment]
Note:
I think testing with real hardware is not possible currently, because the firmware is not ready yet (choosing machine type dynamically etc.).
We'll have to fix https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/29 first.

**Comment by chris007de** [comment]
> Issues I am not sure about include #128, #247.

I'd say #247 should be doable. I'll create an issue in the ayab-firmware repo.
Speaking of that, we should assess which changes we want to have in the firmware for 1.0.0 as well.
Most prominent: https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/29, https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/2, https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/2

**Comment by Adrienne200** [comment]
OK, I'll review what we have now, but without connecting to a machine.

And an aside - Tom, please check the Facebook group. You've been putting in a ton of work here but it appears that you've been neglecting your hardware business.

**Comment by t0mpr1c3** [comment]
> And an aside - Tom, please check the Facebook group. You've been putting in a ton of work here but it appears that you've been neglecting your hardware business.

Thanks for that!

**Comment by t0mpr1c3** [comment]
> > Issues I am not sure about include #128, #247.
> 
> I'd say #247 should be doable. I'll create an issue in the ayab-firmware repo.
> Speaking of that, we should assess which changes we want to have in the firmware for 1.0.0 as well.
> Most prominent: [AllYarnsAreBeautiful/ayab-firmware#29](https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/29), [AllYarnsAreBeautiful/ayab-firmware#2](https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/2), [AllYarnsAreBeautiful/ayab-firmware#2](https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/2)

I think I will switch my focus to the firmware now. At this point it seems like there is more to do on the firmware side than the desktop software.

**Comment by Adrienne200** [comment]
Tom, please check in on Facebook. People are still complaining that they've ordered boards from you and you haven't delivered.

**Comment by Adrienne200** [comment]
Looks like some great progress is being made, thank you. Even if the firmware isn't quite usable yet, could you turn a build of the desktop please and I'll have another go at commenting on what's done so far. I lost steam last time when it wasn't testable with an actual machine; even if that's still true it's time to be looking at what's already there.

**Comment by chris007de** [comment]
@t0mpr1c3 I've lost a bit track of the current state of the 1.0.0 - where are we standing right now, which tasks do we have for 1.0.0, are there any blockers?

**Comment by chris007de** [comment]
@t0mpr1c3 good to have you back in the boat :tada: - no worries, I can relate.

> and Windows.

As Win11 is new in the ring, we probably have gotten another task here...

> One sticking point is that I cannot test OSX

I guess we'll find some people in the community which can help.
But we'll probably have to decide/find out the oldest supportable OSX version. AYAB 0.95 was built with 10.12.
Our current Github CI runs nicely, but only supports OSX 10.15 and 11 (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). Currently we are building with 10.15.
Building for older versions of OSX would require to setup a build container somewhere (which is feasible indeed, but additional effort).
So I would propose to go ahead with 10.15 and newer for now and see if we can get more compatibility later on.

**Comment by dl1com** [comment]
This topic is handled by the GitHub Project for 1.0.0, respectively #446 

Therefore closing now
