### ISSUE TITLE
ayab for mac

### ISSUE THREAD

**Issue by Veerke** [AllYarnsAreBeautiful/ayab-desktop#416]
hello,
 I still frequentlly have problems running the ayab on my machine. I can make perfect drawings and put in in the ayab. But sometimes it does not select a part of the needles.

I think there is a problem with the ifrmware and installation of the port.
What is the best port, controller and firmware i have to choose?
I'm really a complete zero with this......

**Comment by dl1com** [comment]
This is an example for a "user-trouble" issue...It may be desirable to try Github Discussions to channelize such requests :-/
