### ISSUE TITLE
install bug ayab 0.95 on ubuntu

### ISSUE THREAD

**Issue by clairewiwi** [AllYarnsAreBeautiful/ayab-desktop#423]
Hi, is their any Linux/Ubuntu users who have successfully installed the 0.95 version?
It seems broken when I do the
$ pip3 install -r requirements.txt
It can't get requirements to build the wheel..
The terminal log is in the attached file if someone has any idea of how to fix it it would be most welcome.
Many thanks

$ pip3 install -r requirements.txt
Collecting fbs==0.2.8
  Using cached fbs-0.2.8.tar.gz (176 kB)
Collecting fysom==2.1.3
  Using cached fysom-2.1.3-py3-none-any.whl
Collecting Pillow==4.1.0
  Using cached Pillow-4.1.0-cp36-cp36m-manylinux1_x86_64.whl (5.7 MB)
Requirement already satisfied: olefile in /usr/lib/python3/dist-packages (from Pillow==4.1.0->-r requirements.txt (line 2)) (0.45.1)
Collecting playsound==1.2.2
  Using cached playsound-1.2.2-py2.py3-none-any.whl (6.0 kB)
Collecting PyInstaller==3.4
  Using cached PyInstaller-3.4.tar.gz (3.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/wiwi/Programmes/ayab-desktop/venv/bin/python3 /home/wiwi/Programmes/ayab-desktop/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp24ox83w1
       cwd: /tmp/pip-install-hwgztnxm/pyinstaller_4ed9c90e288e4e85ab687e7950a45f3e
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/wiwi/Programmes/ayab-desktop/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/wiwi/Programmes/ayab-desktop/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/wiwi/Programmes/ayab-desktop/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/wiwi/Programmes/ayab-desktop/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 99, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/wiwi/Programmes/ayab-desktop/venv/bin/python3 /home/wiwi/Programmes/ayab-desktop/venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp24ox83w1 Check the logs for full command output.

**Comment by t0mpr1c3** [comment]
I think you can fix this by editing `requirements.txt` and specifying a
more recent version of `setuptools`

**Comment by t0mpr1c3** [comment]
At least for Ubuntu installs, I recommend 

    python3 -m pip install --upgrade pip
    python3 -m pip install --upgrade setuptools

before

    python3 -m pip install -r requirements.txt

I have updated README.md in commit b9abee6 to reflect this.
