### ISSUE TITLE
Logfile is created in /Applications

### ISSUE THREAD

**Issue by rspeed** [AllYarnsAreBeautiful/ayab-desktop#424]
In macOS, the /Applications folder should be considered read-only. Writing a logfile there is poor behavior. Presumably, AYAB writes it to the user's home directory in Linux, which is better but still sub-optimal. I'm trying to figure out a good alternative, but it seems there aren't any obvious methods for getting the standard OS logging path in Python.

One alternative I can think of would be to create a temporary file using `tempfile.NamedTemporaryFile`, then pass that into `logging.basicConfig` instead of the filename. The downside to this is that the logfile wouldn't have a standard location. One possible way around this would be to add a simple feature that allows users to save the logfile to a specified location.

Let me know what you think. I'd be happy to whip up a PR.

**Comment by t0mpr1c3** [comment]
Good catch, Rob.

IIRC the current dev branch creates an AYAB folder in an OS appropriate location, where pattern files get written. I think it would make sense for the log files to be written to a subfolder if that does not currently happen.

**Comment by rspeed** [comment]
Okay, I'll take a look.

**Comment by jonathanperret** [comment]
AYAB currently writes its log file to `$HOME/AYAB/ayab_log.txt`. It's not really an "appropriate" location for macOS (`$HOME/Library/Logs/AYAB` would probably be better), but at least it's not in a read-only location. Good enough for 1.0 I think.
