### ISSUE TITLE
KG882 Firmware fixen

### ISSUE THREAD

**Issue by niccokunzmann** [AllYarnsAreBeautiful/ayab-desktop#43]
siehe #42, KG882 Option einfügen

**Comment by chris007de** [comment]
falsefully closed due to rebasing (duplicate issue # in commit messages)

**Comment by niccokunzmann** [comment]
@chris007de is this still open and should we move it to the firmware repository?

**Comment by chris007de** [comment]
This issue was moved to AllYarnsAreBeautiful/ayab-firmware#2
