### ISSUE TITLE
Wiki needs to be updated

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#431]
There are dead links e.g.
- Software and Hardware links from https://github.com/AllYarnsAreBeautiful/ayab-desktop/wiki/Development#development-information
- Zaubermerline Youtube videos no longer available from https://github.com/AllYarnsAreBeautiful/ayab-desktop/wiki/English

It could use some updating more generally.

**Comment by chris007de** [comment]
Well, I guess the Github Wiki was some kind of intermediate solution for documentation and was superseded by https://manual.ayab-knitting.com at some point in time. We did not turn it of as there is still some info which was not transferred to the manual page.
So from my view, we could probably also disable it to avoid confusion.
