### ISSUE TITLE
Open Image File action under main menu

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#432]
I suggest that in addition to having the button to open an image file, there should be an option on the File submenu activated by the keyboard shortcut Ctrl-O. 

We could think about having menu items for some of the other actions/options, too. Ctrl-C for cancel would be particularly useful -- sometimes I don't want to be hunting around for the mouse.

**Comment by dl1com** [comment]
Implemented, works.
