### ISSUE TITLE
new macOS update

### ISSUE THREAD

**Issue by Francoize** [AllYarnsAreBeautiful/ayab-desktop#438]
I have been using AYAB for a long time on a Brother KH910 via a macbook air. I updated the OS to Monterey and it no longer wants to use Ayab. Does anyone have a solution so I can use it again? The message I get when I want to open Ayab is the following: "cannot open Ayab because the developer cannot be verified". Thank!!!!

**Comment by omeliailiffe** [comment]
Hello,
This happens when Apple cannot verify the develop of the program, and is common with open source software as being verified costs a lot of money.

If you right click AYAB and select open it should give you the option **Open Anyway**
After you do this once it should open like normal.

Here is an Apple support page for more info: [Open a Mac app from an unidentified developer](https://support.apple.com/en-nz/guide/mac-help/mh40616/mac)

Let us know if that solves your issue.

**Comment by Francoize** [comment]
hello, thank you very much for your reply.
I tried following your advice but it is still impossible to open Ayab.
I contacted Apple support, they advised me to install an older version of my operating system but it doesn't work either...
I have the impression that the latest version of apple is too secure..

**Comment by oskay** [comment]
I will take a look at signing it.

**Comment by oskay** [comment]
In some quick tests, it looks like the software cannot be signed and notarized as is.

There is a critical error in that the targeted SDK is too old:
```
      "path": "AYAB.app.zip/AYAB.app/Contents/Resources/ayab/firmware/lib/libusb-0.1.4.dylib",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
```

**Comment by Francoize** [comment]
Good evening, I don't know where to find the terminal you are talking about...and it still does not work..

**Comment by omeliailiffe** [comment]
Terminal is an app you can open. It should be in launchpad with you other
apps. Sometimes it hides in the utilities folder.

☺️

**Comment by Francoize** [comment]
I'm not really good...
I don't understand at all how to do when I open terminal, I get the following message:

Last login: Fri Jul  1 21:36:48 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
MacBook-Air-de-Francoise:~ francoiselesage$ 



Where and how to type the lines of code?
Again, thank you...

**Comment by omeliailiffe** [comment]
Sorry thought I sent this but the email must have gotten lost.

No worries. You are doing great! 

Now that you have terminal open you can type in commands to control your computer!

When you type it should appear in the terminal. 

If you type the command '''cd /Applications/AYAB.app'''
Terminal will change directory/folder (cd) into the AYAB application.
Then type '''./Contents/MacOS/AYAB'''
This simple runs the AYAB app via the terminal. Ayab should now open. 

If that doesn't work let me know what it says in terminal and we will go from there.

**Comment by Francoize** [comment]
unbelievable. THAT WORKS!!!
if you think near me, I will embrace you. I can continue to knit. Thanks thanks thanks.

**Comment by CaterinaSantullo** [comment]
@omeliailiffe I found this thread and I just wanted to thank you a lot! I was really considering buying an old Windows eheh
