### ISSUE TITLE
output black and white png

### ISSUE THREAD

**Issue by niccokunzmann** [AllYarnsAreBeautiful/ayab-desktop#44]
To enable use with ayab, we can create a png graphic.

I.e. a heart

**Comment by niccokunzmann** [comment]
tests are pushed to the branch [png-rendering](https://github.com/AllYarnsAreBeautiful/knittingpattern/tree/png-rendering). @kirstin, you can review it.

**Comment by niccokunzmann** [comment]
This is a result of [block4x4.json](https://github.com/AllYarnsAreBeautiful/knittingpattern/blob/master/knittingpattern/convert/test/test_patterns/block4x4.json) ![tmp3xwdcbf3](https://cloud.githubusercontent.com/assets/564768/16207295/a78d8f36-372c-11e6-8e0b-a6f01ecf1a77.png)

**Comment by niccokunzmann** [comment]
![stirnband](https://cloud.githubusercontent.com/assets/564768/16207492/a34e6d2c-372d-11e6-9bbd-71c846ead7f9.png) converted to
[knitting pattern](https://gist.github.com/niccokunzmann/0d9ddb2017931928e9bbe44115bac010)
achieved by 
    
    knittingpattern.convert.image_to_knittingpattern.convert_image_to_knitting_pattern.path("C:\\ayab-windows-0.80\\patterns\\stirnband.png").temporary_path()

**Comment by niccokunzmann** [comment]
@kirstin please review and close

**Comment by kirstin** [comment]
Nice!
