### ISSUE TITLE
Proposal- 1.0 RC

### ISSUE THREAD

**Issue by X-sam** [AllYarnsAreBeautiful/ayab-desktop#446]
There have been many disparate discussions over the past few years on finding a path towards the release of a new version. #437 reflects my own experience coming in- there's no single source of truth and trying to hunt down the state of affairs is difficult. #401 seems to have been the last discussion around actually making this happen and [the resulting 1.0 milestone](https://github.com/AllYarnsAreBeautiful/ayab-desktop/milestone/14) is pretty useful (if not a bit hard to find in the modern github experience).  
Looking through that milestone, the vast majority of outstanding tickets are feature complete- and of those that aren't, they fit a few major themes- there's some outstanding documentation (e.g. #318,#224) , bugs that are no longer relevant (#161, #206), and several issues which feel unnecessary for cutting a release (#294,#204).  
It feels like putting out an official RC and migrating the not-strictly-necessary work to a `future` or `next` milestone would help to progress towards a final release, and make it easier for new folks to jump in with a clearer path towards new development.

**Comment by dl1com** [comment]
Hi @X-sam, thanks for putting up this issue/thread.
After getting some notifications of your activity yesterday, I also felt that we are at a point where it makes sense to go into consolidation (once again...) and see what is "really" needed for achieving an 1.0 RC.

I updated the milestone according to your proposal and removed/shifted some issues to "next" milestone.
Still, I think there is some work to do. For me, three big topics are not clear currently:

- What's the current state of the Desktop <-> Firmware interaction? Is it possible to knit with the latest state of the 1.0 desktop software and firmware?
- Are we able to build releases for the target operating systems(latest Win10, Win11, MacOS 13.2)?
What's the oldest MacOS version we want to support?
- How far are we away from being able to support KG carriage?

Once again, any help is appreciated. If somebody wants to step up and steer the project towards 1.0, I am happy to provide as much support as I can.
If it helps, we could also establish a more agile way of communication for project-level topics (Discord?) - also here, I am  open for ideas.

//cc @t0mpr1c3 @clholgat @Adrienne200 @oskay

**Comment by clholgat** [comment]
I set up a separate Discord. Feel free to invite anyone and let me know if anyone needs to be a moderator:

https://discord.gg/DGTndn5S

**Comment by dl1com** [comment]
> https://discord.gg/DGTndn5S

@t0mpr1c3 @jpcornil-git perhaps you want to join the Discord as well, if you want :)

**Comment by t0mpr1c3** [comment]
Thanks for the invitation! I'm happy to join the conversation. Not least to thank the recent contributors for all of their hard work.

From my point of view the major issue is standardizing the protocol for computer to shield communication, so that minor changes to the desktop do not require updating the firmware as well. Changes that require updating the firmware should be considered breaking, and carried forward to the next release (2.0, 3.0 etc.)

It follows that the important bugs to fix, and features to implement, for 1.0 are those that require changes to the communication protocol.

Documentation is very important, but can be postponed if necessary.

Just my personal opinions, though. Whatever gets us over the line is good!

**Comment by Adrienne200** [comment]
I disagree about the garter carriage, IMO it's an absolute must for 1.0. Users have been asking for it for years. And it's very close now, looking like it can happen.

My general criteria for a 1.0 release from a user perspective can be summarized as full parity with the original Brother features. That is - solidly reliable patterning with all three carriages, and the last couple of minor features that aren't in yet. I'll review all the open issues to prioritize them from my perspective, might be a few days.

And as discussed on Discord - I was wondering about Tom's emphasis on firmware compatibility as a priority. To me it seems OK if say Desktop v1.1 requires firmware 1.1 to go with it. Users can deal with that if necessary. But if the engineering team can make it work as Tom suggests and all 1.x releases will be backwards compatible with 1.0 firmware, of course that's even better.

**Comment by jpcornil-git** [comment]
My 2c here but API shouldn't be a real issue/can probably be made backward compatible most of the time; messages can be extended or added without breaking backward compatibility, e.g. (from https://ayab-knitting.com/development/):
- v5 and v4 are compatible except for the new machineType field that breaks compatibility
-> machineType should be the 3rd field/byte iso the 1st one; reqStart msg length can then be used by FW to set it to a sound default when connected to an old Desktop version (and a general warning issued with a new Desktop/old FW combination saying that FW should be upgraded/not all features may be supported)
- v4 and v3 are already compatible; for cnfInfo, Desktop  SW can differentiate based on msg reply length (payload is 1 iso 3) 

Note that I ust got a 910 machine with K/L/G carriages from my daugther and I'll have a look at the G carriage detection algo (on the master branch) in the next few days/update [ayab-firmware #51](https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/51).

**Comment by t0mpr1c3** [comment]
Adrienne, to clarify, my concern is not compliance with arbitrary rules about compatibility, it is to enable quicker version updates by not needing to tweak the firmware for every new feature.

From my point of view v1.0 means a stable codebase, not feature complete.

**Comment by clholgat** [comment]
Notes from the recent developer meeting: https://gist.github.com/clholgat/44bb9050e1c3f277ab31e18b2705eb76

**Comment by X-sam** [comment]
This is all being handled, go team!

**Comment by ghost** [comment]
I am currently using a Brother KH-920 with a single bed setup. I really want to knit with 3 colors without having to manually separate the design rows. When will AYAB support a built-in color separation feature for single bed multi-color knitting?

**Comment by X-sam** [comment]
> I am currently using a Brother KH-920 with a single bed setup. I really want to knit with 3 colors without having to manually separate the design rows. When will AYAB support a built-in color separation feature for single bed multi-color knitting?  

This is an inappropriate place for this question, please consider joining the discord and asking for help on the "help-threads" channel.
