### ISSUE TITLE
Github build workflow fails

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#451]
The build workflow for AYAB Desktop currently fails in multiple jobs:

- .deb file job was successful
- MacOS job was successful! :open_mouth: :tada: (Still to be tested if it works, posted to Discord for somebody to verify.)

- [x] Windows job: Writing the package_version to its file fails as the referred variable `${{steps.vars.outputs.tag}}` is empty. [Error](https://github.com/AllYarnsAreBeautiful/ayab-desktop/actions/runs/4715467172/jobs/8362476129#step:4:2)
- [x] AppImage job: Download of appimage tool fails, it only downloads a `index.html` file. [Error](https://github.com/AllYarnsAreBeautiful/ayab-desktop/actions/runs/4715467172/jobs/8362476164#step:16:29)
- [x] Generic issue:

```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

Test action run: https://github.com/AllYarnsAreBeautiful/ayab-desktop/actions/runs/4715467172

**Comment by t0mpr1c3** [comment]
I didn't even realise that we made a .deb

https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/452

**Comment by t0mpr1c3** [comment]
Remind me Chris, is there a reason that we are using Ubuntu-20.04 for the Github runners instead of Ubuntu-latest?

**Comment by dl1com** [comment]
Thanks for the PR!

> @dl1com Remind me Chris, is there a reason that we are using Ubuntu-20.04 for the Github runners instead of Ubuntu-latest? Is it something to do with the Python version?

Yes, it does not build on ubuntu-latest, as Python 3.6 is no longer contained in the repos of current distributions.
