### ISSUE TITLE
Do we need to make a .deb file

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#452]
The appimage should work for all Linux distros so I suggest deprecating the .deb file build. Any thoughts?

**Comment by t0mpr1c3** [comment]
relevant https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/375

**Comment by dl1com** [comment]
> The appimage should work for all Linux distros so I suggest deprecating the .deb file build. Any thoughts?

I second this.
The .deb file won't run properly on recent distributions, as the Python 3.6 dependency is no longer available.
AppImage hides these dependencies (although we should update to a more recent version of Python sooner or later), but I think it is a somewhat popular way of distributing software over several distributions, so I would vote for AppImage over .deb.

**Comment by t0mpr1c3** [comment]
Yes, free fbs traps us in permanent dependency hell and this is another argument for the AppImage installer, assuming that I can actually get it working!

**Comment by dl1com** [comment]
Fixed with #474
