### ISSUE TITLE
AppImage does not launch

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#454]
The most recent AppImage, built from tag https://github.com/AllYarnsAreBeautiful/ayab-desktop/tree/test230417 does not launch under Debian testing. I just yields

```
Traceback (most recent call last):
  File "opt/python3.6/bin/fbs", line 6, in <module>
    from fbs.__main__ import _main
ImportError: cannot import name '_main'
```

It seems like it is some fbs / AppImage packaging issue.

**Comment by t0mpr1c3** [comment]
Do you know which was the appimage build that worked OK? I can go back and have a look at the dependency versions and see what has changed.

**Comment by t0mpr1c3** [comment]
So I just downloaded to a more or less fresh out of the box Ubuntu 20.04 VM and the AppImage apparently ran OK after the usual chmod +x. (I didn't actually test any functionality, but the GUI came up without reporting any errors.)

**Comment by t0mpr1c3** [comment]
FWIW the .deb seemed to install fine as well (/opt/AYAB/AYAB opened the gui with no errors in the log).

**Comment by t0mpr1c3** [comment]
@dl1com might be helpful to try installing the .deb under Debian to see if that works?

**Comment by t0mpr1c3** [comment]
If anybody out there happens to run non-debian flavours of Linux I'd appreciate it if you could try out the AppImage as well :)

**Comment by dl1com** [comment]
Debian 11 is working as of test230514...so closing this for now.
