### ISSUE TITLE
AYAB wont init brother 965

### ISSUE THREAD

**Issue by tinofair** [AllYarnsAreBeautiful/ayab-desktop#455]
Hey ive been having some issues with my ayab shield would appreciate if anyone knows how i can get it working. Some details im using a brother 965 with the ayab shield version 1.4 on a windows computer. 

My device was working a couple weeks ago but initally there were issues with flashing the firmware. Could get the device working when i flash the firmware for the other devices then flashing the firmware for the 965. But it would usually knit most of the design before the buzzer would go off mulitple times per row making me cancell the knitting and restart. 

Ive had the soldiering of my shield checked for short circuits etc by someone who knows what they doing and knows about the ayab project so pretty sure that aint the issue but im not sure.

Just come back from not using the machine after a couple weeks and now my ayab wont let me init the machine(nothing happens when i pass the carrige over the left sensor. Ive tested it on both my laptop and pc that run different versions of windows and the issue is the same on both devices.

If you know how to help please feel free to ask any more questions about the device, issues ive encountered or about my setup.
Thanks,
Ayrton 

>

**Comment by dl1com** [comment]
Hi Ayrton, if the issue still persists, please join our Discord and ask for support in this matter.
https://discord.gg/zaK2kmcw
