### ISSUE TITLE
AYAB for Windows does not launch (Win10)

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#456]
Build: [[test230417](https://github.com/AllYarnsAreBeautiful/ayab-desktop/tree/test230417)](https://github.com/AllYarnsAreBeautiful/ayab-desktop/actions/runs/4718097272)

OS: Win10 21H2

Trying to launch AYAB.exe opens a black terminal for a moment and instantly closes. Calling it via a terminal shows the following error:

```
C:\Program Files (x86)\AYAB>ayab
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "ayab\ayab.py", line 29, in <module>
ModuleNotFoundError: No module named 'ayab.main_gui'
[1144] Failed to execute script main
```

**Comment by t0mpr1c3** [comment]
I can do some testing on Windows 11 next week.

**Comment by t0mpr1c3** [comment]
Chris do you think the git runner should be building on Windows 10 instead of windows-latest? I figure windows-latest should be better because backwards compatibility is more likely than forwards compatibility.

**Comment by t0mpr1c3** [comment]
Fixed in https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/462

**Comment by Bauschlumpf** [comment]
I have tested test230502 with Win10-64 (Windows 10 Pro 22H2) and get the same error.

**Comment by t0mpr1c3** [comment]
Oops. Should be fixed in https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/463

**Comment by Bauschlumpf** [comment]
Now it starts.

First start direct out of the installer crashed with the following message:

"C" konnte nicht gefunden werden. Stellen Sie sicher, dass Sie den Namen richtig eingegeben haben und wiederholen Sie den Vorgang.

Second start works fine.

**Comment by t0mpr1c3** [comment]
Yes, that's what I'm getting too. Probably something wrong with the NSIS script.

**Comment by t0mpr1c3** [comment]
It turns out this is a known bug in the fbs NSIS script which is fixed in the pro version: https://github.com/mherrmann/fbs/issues/255

It might be possible to patch the free version the same way.

**Comment by t0mpr1c3** [comment]
Fixed in https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/464/

**Comment by Bauschlumpf** [comment]
First start out of the installer works fine, too.
