### ISSUE TITLE
New issues 4/2023

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#457]
Adrienne's notes below

This was on an Intel Mac, Big Sur (11.7.5), KH910. With today's test Desktop build 22042023 and the firmware that clholgat loaded onto my interface board.

I tried Triangles_60x10 and testpattern_40x40. Everything at defaults, that is single bed, 2 color, centered, not infinite repeat, etc.

Results:

 

- [x] it only operated on a small subset of the needles, around left 10-20. Until the last row, then it selected more needles but in multiples of 16, not the multiples of 12 that both these patterns are.

- [x] painfully slow waiting for the next row. On the right, it beeped and gave the next row in the UI after about 10 seconds, without needing to cross the turn mark. On the left nothing happened at all without crossing the turn mark then waiting about 20 seconds.

- [x] the black line doesn't step up the image as you go

- Simulation mode (when not connected to the interface) doesn't start at all, just asks Please Start machine. Whereas the April 17th build did basically work in Simulate mode. --> Handled in https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/469

**Comment by t0mpr1c3** [comment]
Also this https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/62

**Comment by dl1com** [comment]
@Adrienne200 are the two open errors in the first post still happening in the latest build test230626? I assume not, we could close this then :)

**Comment by Adrienne200** [comment]
These were temporary issues with that build, fixed at the time.
