### ISSUE TITLE
Mac M1 support 

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#458]
I don't know much about Macs so perhaps someone more knowledgeable can comment. Does the current dev build work on newer Macs with the M1 chips, or do we need to port it somehow?

**Comment by VIPQualityPost** [comment]
I gave it a try this morning, one issue seems to be that there are no arm64 builds of python 3.6.*
If you use rosetta2 in terminal to install conda, then you can sucessfully create the environment. 
For Qt installation it should be made clear which components you need. I am not sure which things to install?
I tried Qt Design Studio, Qt 6.5.0 just macOS module, and Developer Designer Tools (all modules) but when trying to convert the .ui files I still get errors about missing `lrelease`. I don't want to install the whole Qt 6.5.0 because it is ~30GB.

**Comment by t0mpr1c3** [comment]
Thanks for documenting these issues. The Mac OSX build uses qt5.

You should find some pointers in `https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/1.0.0-dev/.github/workflows/build-multi-os.yml` and `https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/1.0.0-dev/setup-environment.sh`

IIRC `lrelease` is only used for translating foreign language files in `https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/1.0.0-dev/src/main/resources/base/ayab/translations/ayab_trans.pl`. Perhaps we should have some kind of build flag to get around that.

**Comment by VIPQualityPost** [comment]
OK, I was able to build, dig around in UI, everything seems OK so far. I don't have real hardware for this yet but I imagine if there was an issue that it should have happened by now.

Note that you can check if your terminal is set up right by running `arch`. By default this returns `arm64` but once you enable rosetta2 (right click terminal in /Applications/Utilities, Get Info, check box for "Open with Rosetta") it will return `i386` ( a bit dated😨 ) but afterwards, installing things will do so using x86_64 version.

I installed Qt 5 but still was getting `lrelease` errors so I just commented out the translation part in `setup_environment.sh`
What module specifically contains lrelease? I tried finding this online and it wasn't clear anywhere there either. I have Qt 5.15.2 macOS module and Source module.

**Comment by t0mpr1c3** [comment]
I believe one option is `pip install qt5-applications` and then replace instances of `lrelease` with `qt5-tools lrelease` using a soft linked shell script but YMMV.

**Comment by t0mpr1c3** [comment]
If you build successfully, please raise a PR and we (@X-sam ?) can think about how to get it working as a git action on a self-hosted runner  https://github.com/mas-cli/m1-github-actions-runner

**Comment by t0mpr1c3** [comment]
Caching is now implemented in 1.0.0-dev build so no need to install qt5.

**Comment by VIPQualityPost** [comment]
If you commented out the parts in setup_environment.sh then it skips the cached qt5 files- I don't think you would have needed them anyway, unless you want the text translated (maybe there are greater ramifications I have not found yet?)

Anyway: do you also have Arduino IDE installed? It's possible to flash without using this, I'm not sure what is implemented in AYAB desktop software, but you can try flashing direct from there and see if it still works (just to rule out that there is some issue with USB devices or your AYAB hardware). MacOS (especially M1 with different arch) can sometimes treat USB devices a little funny and not let them behave how they should.

**Comment by zelatyna** [comment]
> MacOS (especially M1 with different arch) can sometimes treat USB devices a little funny and not let them behave how they should.

I flashed the older version of firmware few days ago so there was no issues with port detection or USB and it was well detected in Arduino IDE.

Eventually, I managed to flash the firmware using local build of desktop from the `1.0.0-dev` branch and using the `ayab_monolithic_uno.hex` file from the [test20230529](https://github.com/AllYarnsAreBeautiful/ayab-firmware/releases/tag/test230529) firmware build. So at least I can do some test knitting tomorrow. 🥳 

I still have not figured out though why the flashing does not work in the test20230530. Any hint where I can find logs?

**Comment by t0mpr1c3** [comment]
usually $HOME/AYAB/ayab_log.txt

**Comment by VIPQualityPost** [comment]
I looked around and the way flashing works is with avrdude:
https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/1.0.0-dev/src/main/python/ayab/firmware_flash.py#L163

But this file was not touched between those two dates. It could be something else broke this.

**Comment by t0mpr1c3** [comment]
Yes you can flash the Arduino from the command line using avrdude. Use the output of `generate_command()` from the python file you linked.

**Comment by VIPQualityPost** [comment]
I mostly just meant that I don't think this has anything to do with using on M1 mac- avrdude works fine, there is something else wrong with the build. Maybe should be it's own github issue?

**Comment by t0mpr1c3** [comment]
The firmware flash dialog going to be rewritten anyway for version 1.0.0 so there's no need. For the same reason I'm reluctant to patch the existing code.

**Comment by zelatyna** [comment]
ok, I figured out the issue with flashing. My test ayab app is called AYAB 2 so the space is not handled properly in the generated command. 

```
/Applications/AYAB 2.app/Contents/Resources/ayab/firmware/avrdude_mac -p atmega328p -c arduino -P /dev/cu.usbserial-01F4C507 -b115200 -D -Uflash:w:"/Applications/AYAB 2.app/Contents/Resources/ayab/firmware/ayab_monolithic_uno.hex":i  -C "/Applications/AYAB 2.app/Contents/Resources/ayab/firmware/avrdude.conf"

-sh: /Applications/AYAB: No such file or directory
```

After renaming to AYAB_2 it worked
Just looking in the code if I can make a PR to fix it

**Comment by t0mpr1c3** [comment]
@VIPQualityPost you were right ;)

**Comment by t0mpr1c3** [comment]
@zelatyna Perhaps if you get a chance you could test #539.

**Comment by dl1com** [comment]
I lost a bit track of the topics in this issue...so we have the following here, right?

- Instructions to build the software for a M1 Mac -> add this information to the README? @VIPQualityPost or @zelatyna ?
- Flashing fails because of whitespace, addressed in #539, please to be tested by @zelatyna

**Comment by zelatyna** [comment]
> @zelatyna Perhaps if you get a chance you could test #539.

sorry for delay, but can only test it next Fri/Saturday

**Comment by dl1com** [comment]
Documentation merged, PR tested and merged...closing this issue
