### ISSUE TITLE
How up to date /documented is the API?

### ISSUE THREAD

**Issue by VIPQualityPost** [AllYarnsAreBeautiful/ayab-desktop#459]
I have been working on a knitting machine controller and recently discovered this project. 
I was thinking that it would be easier for me to write firmware to be compliant with your API than to do a front end myself (I don't have as much software development experience).
From the changelog, the most recent version I can tell implemented is v4 (released 2015). 
However on your website it shows that there is a v5 (https://ayab-knitting.com/development/#serial-communication)
Have there been more releases since? What is the most up to date API and where is the documentation for that interface?

**Comment by t0mpr1c3** [comment]
The most up-to-date is v6 on the 1.0.0-dev branch (https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/1.0.0-dev/src/main/python/ayab/engine/communication.py) but it is still under development and documentation is lacking at this point.

**Comment by dl1com** [comment]
@VIPQualityPost please check https://github.com/AllYarnsAreBeautiful/ayab-manual/pull/13
