### ISSUE TITLE
Software state broken after "Test AYAB Device"

### ISSUE THREAD

**Issue by VIPQualityPost** [AllYarnsAreBeautiful/ayab-desktop#461]
branch: 1.0.0-dev
os: macOS

Without any Arduino connected, if you open the hardware test panel, then close it, if you load an image you will be unable to use the controls on the side panel (all grey, clicking even while grey does not have any effect), the only way to restore operation to the software is closing and re-opening. I don't know if this happens with a device actually connected.

**Comment by t0mpr1c3** [comment]
Which release/commit were you using?

**Comment by t0mpr1c3** [comment]
This might be a bug in the FSM and/or API. Presumably the desired behaviour is that if contact with the device is lost or not established then after a period of time an error code should be emitted and the FSM should revert to the initial, disconnected state. This should also happen if the engine or test module closes without warning.

**Comment by t0mpr1c3** [comment]
I suggest a 10 second timeout as discussed here: https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/200

**Comment by dl1com** [comment]
Build: https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/test230515 in Windows 10

After starting the AYAB application and directly opening the Hardware Test without any hardware attached and Port set to "simulation", the Hardware Test Windows shows up but lags and is unresponsive. Only possibility to fix is to close the AYAB application completely.

Log shows:
```
2023-05-17 21:58:52,380 root     DEBUG    Entered state NO_IMAGE
2023-05-17 21:58:58,158 root     DEBUG    Entered state TESTING_NO_IMAGE
2023-05-17 21:58:58,159 Control  DEBUG    State CONNECT
2023-05-17 21:58:58,159 Control  DEBUG    Port name: Simulation
2023-05-17 21:58:58,159 Control  DEBUG    State VERSION_CHECK
2023-05-17 21:58:58,159 Control  DEBUG    State VERSION_CHECK
2023-05-17 21:58:58,160 Control  INFO     API v6, FW v1.0
2023-05-17 21:58:58,160 Control  DEBUG    State REQUEST_TEST
2023-05-17 21:58:58,160 Control  DEBUG    State CONFIRM_TEST
```

**Comment by t0mpr1c3** [comment]
In [test230518](https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/test230518) on Windows 11, the FSM gets stuck in state REQUEST_TEST and the dialog never loads.

**Comment by t0mpr1c3** [comment]
After patching up the mock communication protocol, the messages passed to and from the device seem correct but the HW test still crashes.

**Comment by t0mpr1c3** [comment]
One problem is that there are separate threads for knitting and testing, and there only needs to be a single thread because you can't do both at the same time.

**Comment by t0mpr1c3** [comment]
I think I've finally fixed it.

**Comment by Adrienne200** [comment]
In build test230530 we have:
In Simulation mode, the box opens and all the buttons do something. Though it's unclear if there's supposed to be any response from the commands. I can't tell if I'm supposed to be able to type commands into the box, I can't.
With actual hardware hooked up, try to open the DeviceTest box and nothing happens.

**Comment by Adrienne200** [comment]
This is still the same in build test230626. With hardware connected, nothing happens when you click Tools -> Test AYAB Device. I removed the Ready-Please Test label, it belongs back in the Todo pile.

**Comment by VIPQualityPost** [comment]
Maybe it's best to just remove the panel from the UI entirely, until the code is sorted out? 
I guess the shields are not tested before shipping (because they are not assembled) (are interfaces tested prior to shipping? can you still buy them online?). But if the test panel is not working that is probably more confusing to users than just having no panel.

**Comment by X-sam** [comment]
hardware test menu is not there in `1.0.0-rc4`... can we make a new ticket for fixing it and bringing it in to next?
@clholgat
