### ISSUE TITLE
Download and bundle firmware binaries in GitHub Workflow

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#466]
see #414

I propose to add a step in the GitHub build workflow which downloads the appropriate firmware release binaries from the firmware repo so they can bundled into the release assets.
To be able to control which firmware version which gets packed into the Desktop release, we should add a "manifest" file into the Desktop repo, which contains the release name to be downloaded from the firmware repo. The workflow reads this file and downloads the correct binaries.

@t0mpr1c3 what do you think?

**Comment by t0mpr1c3** [comment]
Sounds good, I made a PR in the firmware repo to create the release when a tag is pushed so that there is something to upload. https://github.com/AllYarnsAreBeautiful/ayab-firmware/pull/63

**Comment by t0mpr1c3** [comment]
I suggest that the manifest should use semantic versioning, so that if for example the manifest calls for "v1.0" it loads the most recent version matching v1.0.*

**Comment by t0mpr1c3** [comment]
@X-sam has been working on the desktop side: https://github.com/X-sam/ayab-desktop/tree/fetch-firmware-builds

**Comment by t0mpr1c3** [comment]
should the manifest go in src/main/resources/base/ayab/firmware?

**Comment by t0mpr1c3** [comment]
Change to workflow

https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/468/
