### ISSUE TITLE
`emit_audio_player` signal deadlocks

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#503]
When knitting operation starts:

```bash
Dead lock detected while activating a BlockingQueuedConnection: Sender is Observer(0x557b13c834d0), receiver is PyQtSlotProxy(0x557b140eaac0)```

**Comment by t0mpr1c3** [comment]
https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/504 is a temporary fix

**Comment by dl1com** [comment]
> #504 is a temporary fix

With this as a temporary fix, what is the perspective for a final fix of this issue?

**Comment by t0mpr1c3** [comment]
I'm trying to resolve various thread and signal issues at the moment. This one is slightly lower priority so I won't get around to it right away, but will still mess up any test releases in the interim. Put it in a different branch maybe?

**Comment by t0mpr1c3** [comment]
Closing as this issue did not actually arise in the `1.0.0-dev` branch, but in the `threads` branch after consolidating the knit and test threads.
