### ISSUE TITLE
Side bar is too long

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#511]
There is too much space below the Dock widget, so that you have to scroll down to see the Knit button even when the window is maximized.

**Comment by t0mpr1c3** [comment]
Also simplified the sidebar layout by removing horizontal lines, and aligning Knit and Cancel buttons horizontally instead on vertically.

**Comment by dl1com** [comment]
Looks good to me, close
