### ISSUE TITLE
Multiple-beep is delayed

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#524]
Build: test230530. Cross the left turn mark, no sound happens until about needle Left85.

Tested on:
 Build: Desktop test230530, which loads firmware 230529.
 Computer: Mac Intel, 11.7.7 Big Sur
 Knitting machine: KH910
 AYAB hardware: EMSL interface
(also tested on Windows 7 and a Shield, same behavior)

The multiple beep should happen by stopping on or immediately after crossing the left Hall sensor. But nothing happens until you reach about needle Left 85. It seems to be location rather than time, I tried stopping just past the sensor and waiting, nothing happened.

**Comment by clholgat** [comment]
This is because of the garter slop, it can be reduced. Let me see what I can do.

**Comment by zelatyna** [comment]
I tested it today with the desktop build from the 1.0-dev branch.
I can't really assess it correctly, for me the double beep was always bit delayed and needed the carriage to be moved quite a bit to the center, I think it is kinda the same now.

**Comment by Adrienne200** [comment]
At build test230626, you now have to move the carriage about an inch past the turn mark to get the beeps. The requirement is that a pattern that is 200 pixels wide can start immediately and select needles correctly starting at Left 100.  I've found that that will happen even if you're about 2 inches/5cm past the sensor, so it does function as I expect. At v0.95 you could stop with the magnet sitting right on the Hall sensor and get the beeps, which was tidier, but it turns out that an inch past also allows selection to start at L100. If this is because of the extra distance needed to detect the garter carriage, then it is acceptable as it stands now.

**Comment by dl1com** [comment]
> At build test230626, you now have to move the carriage about an inch past the turn mark to get the beeps. The requirement is that a pattern that is 200 pixels wide can start immediately and select needles correctly starting at Left 100. I've found that that will happen even if you're about 2 inches/5cm past the sensor, so it does function as I expect. At v0.95 you could stop with the magnet sitting right on the Hall sensor and get the beeps, which was tidier, but it turns out that an inch past also allows selection to start at L100. If this is because of the extra distance needed to detect the garter carriage, then it is acceptable as it stands now.

Might this behavior related to https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/100 ?

**Comment by zelatyna** [comment]
I was air knitting 200 pixel wide pattern and the pattern seem to be selected correctly even if the beeps happen quite late

**Comment by t0mpr1c3** [comment]
> > If this is because of the extra distance needed to detect the garter carriage, then it is acceptable as it stands now.
> 
> Might this behavior related to [AllYarnsAreBeautiful/ayab-firmware#100](https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/100) ?

Yes, I think this is essentially the same issue. @clholgat has dialed the delay down to a small value, presumably after some calibration.

**Comment by dl1com** [comment]
So it reads for me like we can close this for now. Please reopen in case there is a need for it.
