### ISSUE TITLE
Only knits one row, then dies.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#525]
Build: test230530. It selects needles correctly on row 1, then dies as it tries to start row 2.

Tested on:
Build: Desktop test230530, from which you load firmware 230529.
Computer: Mac Intel, 11.7.7 Big Sur
Knitting machine: KH910
AYAB hardware: EMSL interface
(also tested on: Windows 7 and a Shield, same behavior)

Steps:
1. Open any image, I used the sample Triangles_60x10. Single bed, all settings at default. Check that your port selection has found your hardware, is not in Simulation mode.
2. Carriage on KC1 or KC2, cross the left turn mark. Move a bit past it and stop, see #524, and make sure you hear the multiple beep.
3. Continue across. Notice that it has correctly selected needles for row 1, and beeped correctly at the end.
4. Turn around for row 2.
There's a sound from the solenoids, I think they all turned off. Try to continue knitting, all needles are selected to D and there are no more beeps.

**Comment by clholgat** [comment]
The beep delay is probably the extra garter slop that I have in there. I need to cut that down.

I'm seeing incorrect selection from left to right, let me see what's up with that.

**Comment by clholgat** [comment]
My incorrect selection was because I had the wrong machine type selected.

I can't repro the death on row 2 on my 910 from a mac with the latest everything.

**Comment by zelatyna** [comment]
I encountered the same behaviour today. After one row of knitting in fair isle, in the 2nd row all the needles are knit in color A and end in position D :/ 

Also noticed that the bar indicating where the knitting ended is off and shows almost the end of the image
![image](https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/14292230/aac4a8d8-a657-4c46-a10a-6e3984a28d84)


My specs:
Build: local build from current 1.0-dev branch,  firmware 230529.
Computer: Mac M1, 13.4 Ventura 
Knitting machine: KH950

**Comment by dl1com** [comment]
Just tested in simulation mode of the current 1.0-dev branch with the various test patterns, could not replicate.

@zelatyna could you please share your pattern, just in case it is related to the image?
Plus, please share the logfile, it might be interesting which line numbers are requested/sent, as it seems that the software skips to the end of the pattern.

**Comment by Adrienne200** [comment]
Simulation already worked, this issue only affects actual knitting. 
I tried it again today after (I think) installing today's firmware test20230615, but as there's no corresponding Desktop yet, I was still using the release Desktop test20230530. Still fails as before. I didn't see what zelatyna saw, about the line jumping to the top, mine stops at row 2.
I used one of the usual test images, triangles_60x10.png. 
Log attached.
[ayab_log.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/11764294/ayab_log.txt)

**Comment by t0mpr1c3** [comment]
Given that the desktop simulation and tests work, this must be a firmware issue. I'll raise a ticket there.

**Comment by zelatyna** [comment]
Ok I tested again using
* desktop local build from 1.0-dev
* firmware test20230615
* testPattern40x40 

what happened was something different that I encountered before
* knit 1st row fine , pattern is detected, at the end of the row there was beep
<img width="598" alt="image" src="https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/14292230/d467a202-e921-46a8-b6d5-b4a8c8e79347">

* knit row 2 - it knitted fine, but all needles end up in position D. In the meantime I think something happens cause in the app it looks like knitting just canceled? 
<img width="805" alt="image" src="https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/14292230/ade7f5c6-7371-4bcc-9717-34ef3edf877e">

* knit row 3 - no pattern, knit with color B only, all needles in position D afterwards 
<img width="805" alt="image" src="https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/14292230/5d82fe57-a646-435d-8927-6f4c4bf0cfbd">


I recorded the AYAB Desktop while knitting:


https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/14292230/b26449c8-3383-43c7-9d9d-415079095dae



* I did not have the issue now with the progress bar going to the top, need to double check that my previous pattern image was fine

In the log I see there  is an index error 🙀 looks like something easy to fix, unfortunatelly I have no time to investigate 

[ayab_log.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/11768242/ayab_log.txt)

**Comment by dl1com** [comment]
Yes, seems like a wrong index. Here's the relevant portion of the log:

```
...
2023-06-16 09:26:19,007 Engine   DEBUG    {'portname': '/dev/cu.usbserial-01F4C507', 'machine': 'KH910_KH950', 'mode': 'SINGLEBED', 'num_colors': 2, 'start_row': 0, 'inf_repeat': False, 'start_needle': 80, 'stop_needle': 119, 'alignment': 'CENTER', 'auto_mirror': False, 'continuous_reporting': False}
...
2023-06-16 09:26:27,810 Control  DEBUG    State CONFIRM_START
2023-06-16 09:26:27,916 root     INFO     Notification: Please knit.
2023-06-16 09:26:28,206 Control  DEBUG    State RUN_KNIT
...
2023-06-16 09:26:30,218 Control  DEBUG    0 0 reqLine: 0 pat_row: 0 row_index: 0 color: A
...
2023-06-16 09:26:40,813 Control  DEBUG    0 1 reqLine: 1 pat_row: 1 row_index: 2 color: A
...
2023-06-16 09:26:43,405 Control  DEBUG    State RUN_KNIT
Operation.KNIT
Traceback (most recent call last):
  File "/Users/msendal/PycharmProjects/ayab/ayab-desktop/src/main/python/ayab/thread.py", line 36, in run
    self.function(*self.args, **self.kwargs)
  File "/Users/msendal/PycharmProjects/ayab/ayab-desktop/src/main/python/ayab/engine/engine.py", line 168, in run
    output = self.control.operate(operation)
  File "/Users/msendal/PycharmProjects/ayab/ayab-desktop/src/main/python/ayab/engine/control.py", line 226, in operate
    result = dispatch(self, operation)
  File "/Users/msendal/PycharmProjects/ayab/ayab-desktop/src/main/python/ayab/engine/engine_fsm.py", line 172, in _API6_run_knit
    pattern_finished = control.cnf_line_API6(param)
  File "/Users/msendal/PycharmProjects/ayab/ayab-desktop/src/main/python/ayab/engine/control.py", line 157, in cnf_line_API6
    bits = self.select_needles_API6(color, row_index, blank_line)
  File "/Users/msendal/PycharmProjects/ayab/ayab-desktop/src/main/python/ayab/engine/control.py", line 216, in select_needles_API6
    )[row_index][self.start_pixel:self.end_pixel]
IndexError: list index out of range
```

**Comment by Adrienne200** [comment]
This is the same behavior that I've been seeing. But none of my logs have shown any errors, do release builds not log this kind of coding errors, and should they?  I hope your error is a useful step forwards.

**Comment by t0mpr1c3** [comment]
The log does indeed show that the knitting is cancelled after 2 rows.

**Comment by t0mpr1c3** [comment]
The early termination of the knitting operation occurs because after requesting the first line, the firmware skips to requesting an out of sequence line number. PR #540 helps deal with this by detecting the out of sequence line number request and terminating the knitting operation with an informative error message.

**Comment by t0mpr1c3** [comment]
I'm getting the error intermittently. Sometimes it skips from reqLine(0) to reqLine(54) and exits with an error. Other times it knits row 1, sets up row 2, and then hangs.

**Comment by Adrienne200** [comment]
This issue is no longer present in build test230626's Desktop/firmware. Multiple rows can now be knitted. I'm also closing firmware issue #86.
