### ISSUE TITLE
Image files open one stitch too narrow

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#526]
Build: test230530. 
Open any image file, and observe the Start and Stop needle boxes. A 60-pixel image has opened from Start-30 to Stop-29. You can manually click it up to 30. Also try a 200-pixel image; that opens Start-100 to Stop-99, but now it won't let you click up to 100.
This worked as expected in 0.95.

**Comment by t0mpr1c3** [comment]
There's a needle at 0, isn't there?

**Comment by t0mpr1c3** [comment]
![image](https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/1699266/a677e706-80f1-4869-8340-b35d2a4081a1)

The needle markers I have seen have 0 marked in green. This image is from an ebay seller, but I think it is typical. (Product link: https://www.ebay.com/itm/121841914778)

**Comment by Adrienne200** [comment]
Indeed it does. But you'll find that the 0 written on the number strip sits between Left1 and Right1, it does not represent a physical needle.

**Comment by t0mpr1c3** [comment]
Got it, thankjs for explaining.

**Comment by clholgat** [comment]
Looks fixed to me.

**Comment by zelatyna** [comment]
Yes the start and stop needles look correct
