### ISSUE TITLE
Choose Developers Certificate of Origin

### ISSUE THREAD

**Issue by niccokunzmann** [AllYarnsAreBeautiful/ayab-desktop#53]
I just heard about it in a [talk](https://www.youtube.com/watch?v=O9mtgMcqzug).
http://developercertificate.org/
I think we should choose this in a CONTRIBUTING file.

@kirstin @chris007de please share your thoughts.

**Comment by chris007de** [comment]
This is definitely reasonable to add. :+1: 
There are plenty of (big) projects (kernel, openwrt) using this for many years to avoid any hassle.

**Comment by niccokunzmann** [comment]
#7
