### ISSUE TITLE
Establish semantic versioning

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#534]
To be able to fulfil https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/476, we should move to semantic versioning already before releasing 1.0.0, so we can already test the latest version of fbs.

As discussed in Discord, fbs seems to demand strictly:
x.y.z

So we could go with 0.99.0 for now and increase the rightmost number for each testbuild.
Some goes for firmware.

Any thoughts on this, which parts of the software are affected by this move?

**Comment by t0mpr1c3** [comment]
The rationale should be recorded in the CHANGELOG so that it's consistent going forward. And the new firmware flash dialog/function needs to be aware of it when loading firmware versions from the repo.

**Comment by dl1com** [comment]
@t0mpr1c3 could you please point me to the requirements for version formatting of fbs? I did not find information about this in https://build-system.fman.io/manual/
I just want to double check the options we have for pre-release version naming (i.e. 1.0.0-rc1)

**Comment by t0mpr1c3** [comment]
https://github.com/mherrmann/fbs/blob/702761412a2c8617e68ea8c398f7df725ef71a79/fbs/builtin_commands/_util.py#L72C20-L72C20

**Comment by dl1com** [comment]
> 

meh, I see... ` \d+\.\d+\.\d+$` ...prepending the version number is pretty unusual and against semver.org.
I'd love to be able to use tags like 1.0.0-rc1 or similar to indicate a release candidate/alpha of an upcoming version. fbs prohibits this.

I see two possible solutions:
1. patch fbs so it accepts also other, semver compatible version number formats, or
2. use a semver-compatible format for our tags and versions like 1.0.0-rc1, also show it in our application in this format, but strip it down to 1.0.0 when writing it into the base.json for fbs, so it does not complain when running freeze. Updating an application from 1.0.0-rc1 to 1.0.0-rc2 automatically through Windows installer might not work as expected because then, they both are frozen as 1.0.0 by fbs, but for me that's no drawback as these are release *candidates*, no actual releases. For real releases, we have a difference in the version number (1.0.0 -> 1.0.1) and this should work as expected.

Therefore, I'd favor option 2.

**Comment by X-sam** [comment]
My vote is also on option 2. FBS being janky isn't a good reason not to use the most common `maj.min.patch-sub` format.

**Comment by X-sam** [comment]
(though that shouldn't stop us from opening an issue on FBS about this topic!)

**Comment by t0mpr1c3** [comment]
#2 seems fine to me and easier to maintain.
