### ISSUE TITLE
The "Pass" column is redundant in single bed mode

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#548]
AYAB software version: test230626
Computer/OS: Intel Mac/Big Sur
Knitting machine: KH910
AYAB hardware: Interface

In the new display showing the pattern row as you knit, when you're in Single bed mode the second column always says Pass 1. How about removing it?

1. Open any image
2. Leave all the settings at default, so you're using single bed and 2 color
3. Doesn't matter whether you're set to Simulation or actually connected.
4. Click Knit and let it run a few rows.

Columns 1 and 3 contain useful information, but column 2 always says "Pass 1" which isn't very informative.

<img width="344" alt="Screen Shot 2023-07-01 at 11 54 40 PM" src="https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/24358225/4f519481-e0e2-48f2-b915-e91d0f72c372">

**Comment by t0mpr1c3** [comment]
True
