### ISSUE TITLE
Update to a more recent version of Python

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#555]
Currently, AYAB-Desktop is depending on Python 3.6, which is no longer maintained.
We should evaluate to update to a more recent version of Python. Target should be 3.11, but perhaps we have to triage the complications caused by updating our dependencies (see requirements.txt) and stick to a version in between 3.6 and 3.11 for now.

**Comment by t0mpr1c3** [comment]
What are the alternatives to `fbs`?

**Comment by dl1com** [comment]
> What are the alternatives to `fbs`?

Don't know...but this might be a separate topic? I guess updating to a more recent version of Python a sensible thing to do, with or without fbs

**Comment by t0mpr1c3** [comment]
The freeware version of `fbs` constrains us to Python 3.6

**Comment by oskay** [comment]
Wow. That's really not good.

**Comment by t0mpr1c3** [comment]
It isn't. But the issue has been raised a couple of times recently and I thought we had taken a decision to stick with freeware fbs for the time being.

**Comment by dl1com** [comment]
I continuously forget about the details of the constraints of fbs, sorry 😄 it's really a very unusual licensing model to me 🙃

So, as a soft target, in case somebody wants to try to run fbs on a higher Python version, feel free to do so.
Apart from that we focus on getting AYAB 1.0 ready, although it will likely rely on Python 3.6 then.

After release of AYAB Desktop 1.0, we'll focus on the ESP32 webapp anyway.
Additionally, we can look for fbs alternatives for AYAB then, so we don't need to abandon it completely (because it will become more and more tedious to rely on Python 3.6) and still can do bugfix releases.

**Comment by t0mpr1c3** [comment]
> My first reading is that even if it is technically allowed to release GPL software that has a commercial dependency, it's "worst practice" to do so-- a hobbyist wouldn't be able to make a small change to AYAB and compile a working version without purchasing a commercial license to do so.

From the discussion a couple of months ago, I think we can say there is universal agreement on this point.

**Comment by t0mpr1c3** [comment]
> So, as a soft target, in case somebody wants to try to run fbs on a higher Python version, feel free to do so. Apart from that we focus on getting AYAB 1.0 ready, although it will likely rely on Python 3.6 then.

How about 3.8? There was a security bugfix for Python 3.8 just last month. I believe it is also the base release for Ubuntu 20.04.

**Comment by t0mpr1c3** [comment]
Just to note -- we previously rolled back from Python 3.7 to 3.6 for fbs compatibility (#389).

**Comment by dl1com** [comment]
> Just to note -- we previously rolled back from Python 3.7 to 3.6 for fbs compatibility (#389). Python 3.7 is also past its end-of-life.

Oh, I see...feels a bit like groundhog day. Let's hope for the best.
Did you try fbs run and freeze locally with 3.8?

**Comment by t0mpr1c3** [comment]
No, I should try that on Windows and Ubuntu 20.04.

**Comment by t0mpr1c3** [comment]
Python 3.8 end of life is in October, 2024.

**Comment by X-sam** [comment]
Updated to 3.11 in #572
