### ISSUE TITLE
Use version pinning for Python requirements

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#56]
As it already happened to cause some trouble end of last year, I propose to use version pinning for Python requirements instead of the ">=" style.
This is not applicable to current master, but I saw it on some of the branches.

We ran into problems as we used the requirement Pillow>=1.6.5 (or something like that) and Pillow did an API change in version 3.0.0. New users installed ayab and its requirements, but it did not run, as the automatically installed Pillow version was "too new". So the software did break due to third party influence, which should not be possible.
Some more reading on this topic: http://nvie.com/posts/pin-your-packages/

**Comment by niccokunzmann** [comment]
This is also documented in the DEVELOP.rst file.
