### ISSUE TITLE
Python 3.8 build process broken

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#563]
When trying to build the Windows and Mac binaries, the build breaks during install of the requirements.
It seems that the pip installation of PyInstaller 4.1 fails: https://github.com/AllYarnsAreBeautiful/ayab-desktop/actions/runs/5743504547/job/15567955617

````
File "C:\Users\runneradmin\AppData\Local\Temp\pip-install-e9k4k2yx\pyinstaller_002bac1a265f43209f2652ecb8936c55\PyInstaller.py", line 16, in <module>
      from PyInstaller.__main__ import run
  ModuleNotFoundError: No module named 'PyInstaller.__main__'; 'PyInstaller' is not a package
  [end of output]
````

During the work on https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/559 this was not the case, but the CI check ran on a linux system for that.

It's the same error message as stated in https://github.com/pyinstaller/pyinstaller/issues/6704
So if fbs likes it, we could give it a try with PyInstaller 4.4 to solve this

**Comment by t0mpr1c3** [comment]
> It's the same error message as stated in [pyinstaller/pyinstaller#6704](https://github.com/pyinstaller/pyinstaller/issues/6704) So if fbs likes it, we could give it a try with PyInstaller 4.4 to solve this

Let's try it.

**Comment by dl1com** [comment]
In case this fails, or is not compatible to fbs, we could pin setuptools to an earlier version (fbs dependency hell is getting out of hand...):
https://github.com/glencoesoftware/CellProfiler/commit/54cd230149f4ef5afe745d946a1f51481432422b

**Comment by t0mpr1c3** [comment]
Same with pip.
