### ISSUE TITLE
Build 0.99.0-rc1 doesn't launch on Mac (Big Sur)

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#565]
AYAB software version: 0.99.0-rc1
Computer/OS: Intel Mac, macOS 11.7.9 Big Sur
Knitting machine: N/A
AYAB hardware: N/A

1. Download AYAB-0.99.0-rc1.dmg from https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases
2. Double-click on the dmg.
Even before you drag it to Applications, there's a No-Entry sign on the executable.
<img width="391" alt="Screen Shot 2023-08-26 at 11 33 17 AM" src="https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/24358225/eced76f4-0afd-4ac4-8059-e195ed577a09">

3. Drag it to Applications anyway.
4. Double-click, or right-click>Open, it says that it's not supported.
<img width="274" alt="Screen Shot 2023-08-26 at 11 21 27 AM" src="https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/24358225/20db165d-1404-4001-8f11-900cac145a63">

5. Try opening from Terminal, it says that it's damaged.
<img width="549" alt="Screen Shot 2023-08-26 at 11 22 38 AM" src="https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/24358225/12751835-5441-4487-833f-74e6263d5cba">

If this behavior is intentional, or a necessary side-effect of recent changes, we need to discuss whether it's OK to not support an OS that's only 4 years old.

**Comment by dl1com** [comment]
Is this a new effect with 0.99.0-rc1 or was this the case with [test230626](https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/test230626) as well?

**Comment by X-sam** [comment]
Seeing the same thing on M1 with Monterey `12.6.6`. [test230626](https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/test230626) works fine. Possibly related to FBS or PyInstall updates? Investigating...

**Comment by t0mpr1c3** [comment]
> Seeing the same thing on M1 with Monterey `12.6.6`. [test230626](https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/test230626) works fine. Possibly related to FBS or PyInstall updates? Investigating...

Yes, the move to Python 3.8 involved updates to both `fbs` and `PyInstall` so those are good places to start looking.

**Comment by dl1com** [comment]
Any new insights on this?

**Comment by X-sam** [comment]
Locally, I can now build m1 releases on an m1 machine. Remotely, I _think_ intel builds are working as of #572 - try this [test build](https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/v0.99.0-pocmac). There's theoretically universal builds, but I haven't gotten super far into that yet.  
Sadly, [m1 runners are on GH's roadmap for next quarter](https://github.com/github/roadmap/issues/528) so I'm gonna have to kludge something up on a self-hosted runner to test that if the universal builds don't pan out.

**Comment by X-sam** [comment]
Fixed as of #572
