### ISSUE TITLE
Definition of Done

### ISSUE THREAD

**Issue by niccokunzmann** [AllYarnsAreBeautiful/ayab-desktop#58]
In Milestone 4 evaluate what is possible
In Milestone 5 define definition of done.

**Comment by niccokunzmann** [comment]
- statt issues: wo solls hingehen
- dann erst zu issues
- bis donnerstag, dh. morgen/heute

**Comment by niccokunzmann** [comment]
https://github.com/AllYarnsAreBeautiful/ayab-desktop/wiki/Definition-of-Done#milestone-plan

**Comment by niccokunzmann** [comment]
The mile stone plan is ready for review:
https://github.com/AllYarnsAreBeautiful/ayab-desktop/wiki/Definition-of-Done#milestone-plan

**Comment by chris007de** [comment]
I like it so far, guess it's ambitious but realistic.
From my point, let's proceed and dive into the details when the issues are created.
@andz82 any additional comments?

**Comment by andz82** [comment]
Looks good for me too. I miss a bit bugfixing of existing AYAB Issues and Documentation. But that could be seen implicit inside the other Goals.

**Comment by niccokunzmann** [comment]
issues are created they need to be estimated, 
@kirstin let's do this.
