### ISSUE TITLE
Improve black progress bar

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#592]
ETIBerlin commented:
When the bar that shows progress goes higher, I would like the image to get paler underneath it i.e. the black turns into grey to signify it has already been knitted.

**Comment by t0mpr1c3** [comment]
AdrienneH:
a) interesting idea. I've also considered revisiting the black bar, it tends to obscure exactly the area you wanted to look at. But with the new display below in 1.0 that's less of an issue. b) have you explored the feature that's in 0.95 under Image Actions -> Repeat? Thoughts on improving it? c) I don't think so, another interesting idea.

**Comment by t0mpr1c3** [comment]
ETIBerlin:
I just wanted to jot it down, as I hosted my usual workshop at the technical museum berlin and had problems seeing the bar and haveing request for pattern that would go on for longer than i usually let the kids knit. I´ll check out the 0.95 repeat. the black bar could be coloured, anything that stands out more is more user and disablity friendly.

**Comment by t0mpr1c3** [comment]
I really like the suggestion of greying out the part of the pattern that has already been knitted. It would show the progress in the pattern as a whole without obscuring the current row. It's a great idea.

**Comment by t0mpr1c3** [comment]
Even just setting the colour of the bar to semi-transparent grey is a big improvement, in my opinion. Perhaps we could try that as an incremental solution?

**Comment by Adrienne200** [comment]
I've been using this in 1.0 rc2. Mostly I like it, but now it's maybe not quite obvious enough where you are.
Works great for someone with good vision looking straight at the screen. But say you’re standing up and looking down at the screen at a bit of an angle, then it's not so clear. And for a low-vision person, could there be a bar but a lighter color? Or a short bar the equivalent of a few stitches long sticking out at the sides, where the bar used to be? 
Or leave it for a Beta and get user input?

**Comment by t0mpr1c3** [comment]
I tried with the bar sticking out at the sides on the web app, and it looks good.
