### ISSUE TITLE
Colored images display some colors incorrectly.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#603]
When opening an image with multiple colors, some colors display correctly and some show their opposite. It did this at 0.95 as well, see discussion in Desktop issue #297.

AYAB software version: 0.99 rc1 Aug 6 2023
Computer/OS: Windows 7)
(same on the June 26th Mac build, and in 0.95

I made this image with 8 colors
![Colors 8 60x60](https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/24358225/4660f72c-a061-415b-97c4-52a11f2dc910)

<img width="1249" alt="Screen Shot 2023-11-02 at 8 55 23 PM" src="https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/24358225/ad7df31b-e046-4431-a035-6ec9de61455b">
Here's what it looks like when opened in AYAB, with the correct colors shown in the lower right.
Notice that the white, black, pink, green and gray are displayed more or less correctly.
But the blue is red, the red is blue, and the yellow is cyan.

<img width="1055" alt="Screen Shot 2023-11-02 at 8 59 08 PM" src="https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/24358225/74f92f7a-b2db-4c78-ae4b-9133dfeb6980">
However the lower display with the separated out colors shows them correctly.

**Comment by t0mpr1c3** [comment]
> However the lower display with the separated out colors shows them correctly. 

Good to know, and will make it easier to find the bug.

**Comment by X-sam** [comment]
confirmed working from #624
