### ISSUE TITLE
[BUG] `CommunicationMock` with `step=True` fails

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#606]
The call to `QMessageBox` in `communication_mock.py` hangs because the GUI is in a different thread.

To fix this, make the `CommunicationMock` object inherit type `Signal_Sender` and use `emit_blocking_popup()`.

**Comment by jonathanperret** [comment]
I'm closing this as the lack of a step-by-step simulation mode hasn't been reported as a problem as far as I know. Feel free to reopen if I got it wrong.
