### ISSUE TITLE
Make selection of machine type more prominent on the main UI

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#611]
As discussed on today's meeting:

Currently, the choice of the machine type is done within the menu, and is only visible within this menu.

To avoid errors by having the wrong machine model selected in the menu (for first time users, or users who switch their hardware between multiple machines models), the currently chosen machine model should be shown (prominently) in the main UI.

**Comment by t0mpr1c3** [comment]
Where's the best place to display the machine type?

**Comment by dl1com** [comment]
solved by #625
