### ISSUE TITLE
[BUG] Improve the sideways scroll of the lower display.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#615]
AYAB software version: 0.99 RC2
Computer/OS: Windows 7, small laptop
Knitting machine: KH910
AYAB hardware: Interface or shield

I'm using a small Windows laptop with a minuscule screen, 1024x600. Mostly the UI scales down to this size quite well, but the new lower display doesn't scroll properly. It might also not scroll smoothly on a larger screen.

1. Open the "Stirnband" sample which is 160 pixels wide
2. All settings at default, start to knit a few rows.
3. Try scrolling sideways in the lower display.

Expected:
- [ ] It should scroll smoothly on any image up to 200 pixels wide, and any screen down to 1024 pixels, and be obvious where you are. 
- [ ] It needs a rule marked or numbered every 10 stitches or so.
- [ ] The section where it shows the row number and carriage should be sticky, always visible.
- [ ] Make the boxes zoom smaller
- [ ] Fix alignment (#620)
- [ ] Show flanking needles (#620)

Actual: 
On a small screen, when you move the slider it seems to jump from one area to the next without any indication of overlap, and never show the middle. It may be better on a larger screen but I'll guess that it isn't very good there either. 
![sideways scroll small screen](https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/24358225/a1ba2e22-dd72-486a-8004-1ae3bd4a0cd8)

**Comment by t0mpr1c3** [comment]
Good suggestions -- I edited the above to add checkboxes.

**Comment by t0mpr1c3** [comment]
This isn't straightforward in Qt, I propose postponing this to after v1.0, except for fixing the alignment.

**Comment by X-sam** [comment]
Some questions about changes to the knit progress view-
Windows doesn't support colored backgrounds on table headers, so the options are "highlight current color but the info isn't 'sticky'"(picture A) or "don't highlight current color but the info is 'sticky'"(picture B)
|  A|   B|
|---|---|
|![Screenshot 2024-07-04 160250](https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/6620407/168a9f5e-84b9-474d-a3ec-623e347fa12b)|![Screenshot 2024-07-04 161500](https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/6620407/1a9292c6-c7f4-499c-8986-a45db09fe6da)|

**Comment by X-sam** [comment]
Here are some videos to clarify:
| Non-sticky row info | Sticky Row Info |
| --- | --- |
| ![video of non-sticky](https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/6620407/4922e763-374c-4781-9c9e-24a7c6edf7c8) |   ![video of sticky](https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/6620407/9aeade0c-75cf-4070-9023-796968cd4654) |

**Comment by t0mpr1c3** [comment]
I was under the impression that implementing the sticky header was really complicated in Qt. I am far from expert though.

**Comment by X-sam** [comment]
> I was under the impression that implementing the sticky header was really complicated in Qt. I am far from expert though.

I mean, I did it... The videos are from test branches I made.
