### ISSUE TITLE
[BUG] Knit progress window is not properly aligned and does not show flanking needles

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#620]
![image](https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/1699266/8a403dc5-300b-4951-8160-616e1a40ce13)

**Comment by t0mpr1c3** [comment]
See also #622

**Comment by X-sam** [comment]
@clholgat understands this and will leave a comment explaining these things that we can use to add to the documentation

**Comment by jonathanperret** [comment]
I think this works as expected in 1.0 beta, closing now.
