### ISSUE TITLE
[BUG] Zoom does not work on mac v0.95

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#628]
Neither pinch zoom or cmd+ work on Mac, desktop v0.95. Reported by Discord user `mary`.

I expect this is fixed in recent test versions.

**Comment by X-sam** [comment]
Works as of [ed0296f](https://github.com/AllYarnsAreBeautiful/ayab-desktop/commit/ed0296f754f46a39b4f1a580f7fc6f7dd3209d4b)
