### ISSUE TITLE
Build 0.99.0-rc4 doesn't launch on Windows 7. Missing dll.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#639]
AYAB software version: 0.99.0-rc4 
Computer/OS: Windows 7
Knitting machine: KH910
AYAB hardware: Interface

Builds up to 0.99.0-rc3 installed and launched on Windows 7. The QT6 and 0.99.0-rc4 builds both stall out almost immediately on launch, missing api-ms-win-core-path-l1-1-0.dll

![Missing DLL](https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/24358225/ed29f843-492d-48bc-965a-a0f8d1175d4e)

**Comment by t0mpr1c3** [comment]
This is likely a problem specific to Windows 7.
