### ISSUE TITLE
Mac build 0.99.0-rc4 crashes on quit

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#640]
Good news is, it launches and runs. But it crashes when you quit.

AYAB software version: 0.99.0-rc4
Computer/OS: Intel Mac, Big Sur (11.7.10)
Knitting machine: KH910
AYAB hardware: Interface

Build 0.99.0-rc4. Installs firmware rc3. (Confusing, but correct AFAIK)
Basically works, so far.

But quit (by any method), wait a few seconds and the "AYAB quit unexpectedly" box comes up. Crash report attached. (I never send these to Apple.)

The most recent working Windows build also crashes on quit. That's build 0.99-rc3. Previous builds did not crash.

[AYAB-mac_2024-03-13-152332_Adriennes-MacBook-Pro.crash.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/14625279/AYAB-mac_2024-03-13-152332_Adriennes-MacBook-Pro.crash.txt)

**Comment by X-sam** [comment]
might be addressed in #637

**Comment by Adrienne200** [comment]
This is still crashing on quit on Mac. I had seen a crash on quit on Windows too back at rc2. Windows is not crashing now, rc6.

**Comment by jonathanperret** [comment]
@Adrienne200 #670 fixes this for me.
