### ISSUE TITLE
The About box is missing the logo on Mac, and the package-version is not populated.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#644]
AYAB software version: 0.99.0-rc4
Computer/OS: Intel Mac, Big Sur
Knitting machine: KH910
AYAB hardware: Interface

Do Help - About
Expected: A box with the logo, and a version number.
On Mac it's a big empty space where the logo should be, and 
All Yarns Are Beautiful PACKAGE_VERSION
On Windows the AYAB logo shows up correctly, but the package-version issue is the same.

<img width="619" alt="Screen Shot 2024-03-16 at 3 41 34 PM" src="https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/24358225/971165a6-2681-4322-b371-333fc984d0d2">

**Comment by X-sam** [comment]
This is fixed in the typing pr

**Comment by X-sam** [comment]
Logo is fixed, `PACKAGE_VERSION` still isn't.

**Comment by jonathanperret** [comment]
I can confirm that #661 (`0.99.0-test`) fixes the version number display in the about box, this can be closed I think.
