### ISSUE TITLE
Outdated "New version" dialog appears on launch

### ISSUE THREAD

**Issue by citizenkate** [AllYarnsAreBeautiful/ayab-desktop#647]
AYAB software version: 0.99.0-rc4
Computer/OS: Apple M1, Ventura 13.1
Knitting machine: n/a
AYAB hardware: n/a

Steps: 
Install and launch version 0.99.0-rc4.
Unexpected result:
Dialog announcing version 0.95 with a prompt to update.

<img width="616" alt="update-fake-news" src="https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/17323186/854f9e12-736c-47d3-ac14-bc7de8131777">

**Comment by X-sam** [comment]
I don't think this is a bug- technically 0.95 is the latest release version, the newer test builds are all labelled as `prerelease`. Let's keep an eye on it after we release 1.0 though!

**Comment by citizenkate** [comment]
Oh cool! I see `check_new_version` now in the code. So, if we play our cards right, this announcement will update automatically when we release 1.0, and notify users of earlier versions to upgrade. 

I have added a note about this to our draft documentation so that beta testers know it is a known issue.

**Comment by citizenkate** [comment]
Re-opening with `confirm post launch` label so we can check that this is working as expected when the time is right.

**Comment by jonathanperret** [comment]
Unfortunately, the code that checks for a newer version and pops up the dialog does not exist in the last officially released version which is 0.95. Which means that no matter what we put in the next release, current users won't be notified when it is released.

When we make an actual 1.0 release, the dialog won't pop up for users of that 1.0 release until yet another release (1.0.1, 1.1) is out.

**Comment by jonathanperret** [comment]
I think we need to get a fix for this (e.g. #715) into 1.0.0, otherwise by the time we roll out 1.1.0-beta1 we will end up having either 1.0.0 users being prompted to install the beta, or beta users being prompted to downgrade.
