### ISSUE TITLE
1.0.0-dev branch crashes immediately on M2 Max Mac

### ISSUE THREAD

**Issue by marygraceblair** [AllYarnsAreBeautiful/ayab-desktop#656]
I cloned the repo and followed the README instructions for MacOS (without running into errors), but the app crashes immediately after running `fbs run` .

There are no messages in ayab_log.txt but the python crash report suggests that there might be a segfault happening. 

<img width="1035" alt="image" src="https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/13790422/1754c097-d721-4f91-8c9b-66c4353411bf">

**Comment by X-sam** [comment]
Scratching my head a bit here as I've followed the steps in the instructions with a brand new Mac install and no issues... will follow up on discord to try and dig deeper!

**Comment by X-sam** [comment]
This should be fixed once #659 is merged
