### ISSUE TITLE
Build 0.99.0-rc5 fails to launch on Intel Mac, or Win11

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#658]
The rc4 build worked. rc5, and the next test build 0.99.0-test808f9d0 do not.

AYAB software version: 0.99.0-rc5
Computer/OS: Intel Mac, Big Sur 11.7.10
Knitting machine: KH910
AYAB hardware: Interface

So far the only successful release build for Mac has been rc4. It is broken again at rc5, (and also the next test build 0.99.0-test808f9d0 which wasn't trying to fix this issue.) It bounces once in the dock and dies.  I have stepped through the messages about malicious software.

Steps:
1.Download the dmg from the Releases page 
2.Double-click to launch. 
(There are multiple messages here and at the next steps about not being able to detect malicious software, which I won't show in detail. Right-click and find the Open Anyway options.)
3.Drag the AYAB icon to the Application folder.
4.In Applications, double-click AYAB-mac.app
Right-click and step past the malicious software warnings.

Expected: The Desktop app should launch.
Actual: Moves once in the dock, and dies.

5. Open a Terminal window.
6. type:
/Applications/AYAB-mac.app/Contents/MacOS/AYAB-mac.app

Expected: The Desktop app should launch
Actual: It does not launch. Debug log info attached.

[AYAB rc5 crash on launch.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/15016584/AYAB.rc5.crash.on.launch.txt)

**Comment by Adrienne200** [comment]
Similar fail on Win11. it brings up a black command line box, spews a bunch of debug crap, and closes without launching the app. Log attached.
[RC5 on Win11.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/15019864/RC5.on.Win11.txt)

**Comment by X-sam** [comment]
#659 addresses this, and [0.99.0-rc6](https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/0.99.0-rc6) runs properly.
