### ISSUE TITLE
Patterning can get stuck on row n-1 and never finish

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#662]
AYAB software version: 0.99.0-rc6
Computer/OS: Intel Mac, Big Sur
Knitting machine: KH910
AYAB hardware: Interface

 It's new in the rc4-rc6 timeframe, I've never seen this happen before.

Steps:
All settings and prefs at default, so Infinite Repeat is unchecked
You need to actually air-knit, Simulate is different and doesn't show the issue.
Open the Triangles sample. It is 10 rows.
(Optional: set the start row to 7 for more convenient testing.)
Start on the left, remembering to pause for two seconds after crossing the turn mark.
and knit as usual for 8 rows, noticing the end-of-row sounds from the hardware's buzzer and the "ding" from computer's speakers.
Keep going for rows 9 and 10 without slowing down.

Result: Usually it will select row 10 and complete as expected. But sometimes (about half the time on Mac, rarely on Windows but it did happen) I could get it to just keep repeating row 9 without ever finishing.

**Comment by X-sam** [comment]
possibly related to AllYarnsAreBeautiful/ayab-firmware#190 ?

**Comment by jonathanperret** [comment]
I've done a number of swatches with (recent) 1.0-dev firmware and not hit this, I think. @Adrienne200 are you up for trying it with `1.0.0-beta1`?

**Comment by jonathanperret** [comment]
Thanks for testing again. I’ll give it a try tomorrow on my 910 (from a Mac) with your exact instructions to see if I can reproduce it.

**Comment by jonathanperret** [comment]
@Adrienne200 I'm trying to looking into this more seriously. I seem to remember on the call last week you sais it occurred only with an AYAB Interface?
One thing I'd like to understand more clearly is what you see happening on the last row. Does the desktop app ever get to the point where it says "Finished knitting"? Or does it just stop reacting to rows being completed on the machine? Or does it keep emitting "dings" but repeating row 9?

**Comment by clholgat** [comment]
I can easily repro on my 270 with a Jens interface.

If the last row is row N. I never get the end of row beep for row N-1 and then a few seconds later, the desktop software gives me the end of pattern beeps but nothing more from the interface.

Digging.

**Comment by clholgat** [comment]
Found a fix https://github.com/AllYarnsAreBeautiful/ayab-firmware/pull/217

**Comment by jonathanperret** [comment]
🛎 A proposed fix for this is in #740 and can be tested in the release referenced there.
