### ISSUE TITLE
CLI control of ayab / API

### ISSUE THREAD

**Issue by marioangst** [AllYarnsAreBeautiful/ayab-desktop#663]
This is such an amazingly cool project, loving it!

For an art-science collaboration project, we are currently researching ways to interface a knitting machine with data streams (think sensor data, output from data analysis pipelines...).

To do so, I am planning to write a small JSON API to interface our data streams with ayab.

To do so, I would need a way to get higher-level/ CLI control over ayab (or API control of the GUI?).

I do not want to re-invent the wheel here and before I hack away at something that has been done before:
- has there been a successor to the deprecated CLI interface to ayab?
- if no, any pointers on where in this repo to start hacking away at this? I'm a data scientist, so machine-interfacing code is a bit out of my comfort zone, so it would be good to know where the higher-level routines are.

**Comment by dl1com** [comment]
Hi,
sorry for letting you wait...here are some answers for you:

> has there been a successor to the deprecated CLI interface to ayab?

No, there hasn't been a CLI successor

> if no, any pointers on where in this repo to start hacking away at this? I'm a data scientist, so machine-interfacing code is a bit out of my comfort zone, so it would be good to know where the higher-level routines are.

Have a look here: https://github.com/AllYarnsAreBeautiful/ayab-manual/blob/1.0.0-dev/docs/API.md
That's the API documentation of the v6 protocol, which is used for the upcoming version 1.0 of the AYAB software.
[Here's the place where it is used in the main software](https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/1.0.0-dev/src/main/python/main/ayab/engine/communication.py), so you could try and figure out how to adapt it to your needs.

Hope this helps!

**Comment by marioangst** [comment]
Thanks and sorry from me for not closing this earlier! This has been helpful!
