### ISSUE TITLE
Incorrect needle selection on 270, after starting AYAB with the carriage to the right of the left hall sensor.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#667]
270 only. If you click Cancel, then Knit, while to the right of the left Hall sensor, AYAB appears to start up correctly, but it the "shadows", coping the pattern again when it shouldn't.

AYAB software version: 0.99.0-rc6
Computer/OS: Intel Mac, Big Sur
Knitting machine: KH270
AYAB hardware: Interface

Steps
1. Make sure that you have AYAB's prefs set to 270, and have flashed the firmware
2. Use any non-repeating image, sample attached.
3. First test the image by air-knitting the conventional steps, placing the carriage outside the left turn mark, click Knit, cross the turn mark, wait a moment, continue. This should just work.
4. Now, stop the carriage anywhere to the _right_ of the left turn mark.
5. Click Cancel. Then click Knit
6. Move the carriage from right to left so that both magnets are to the left of the left turn mark
7. Take the carriage across the turn mark from left to right, wait a moment, continue.

Expected: It should start again at row 1, and just work. (Having ignored all right-left magnet movements)
Actual: It repeats the pattern twice.

![abcd vertical 32x64](https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/24358225/01cf5a1a-f3b4-4316-b9c1-55b28c6b3872)

it's supposed to ignore the right-left movement and

**Comment by clholgat** [comment]
Oh, I know what this is. There's an early out for the 270 carriage detection because of the two magnets, it's probably causing problems.

**Comment by dl1com** [comment]
> Oh, I know what this is. There's an early out for the 270 carriage detection because of the two magnets, it's probably causing problems.

Do you think this is a trivial fix and can make it into 1.0 or should be postponed?

**Comment by X-sam** [comment]
Is this related to https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/179

**Comment by jonathanperret** [comment]
> Is this related to [AllYarnsAreBeautiful/ayab-firmware#179](https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/179)

Right, this should probably be tested again.

**Comment by dl1com** [comment]
According to @Adrienne200 s report in Discord, still not fixed
(also incorporating with https://github.com/AllYarnsAreBeautiful/ayab-firmware/pull/207 )

**Comment by clholgat** [comment]
I can repro locally. Digging

**Comment by clholgat** [comment]
Well, that was easy https://github.com/AllYarnsAreBeautiful/ayab-firmware/pull/208

**Comment by jonathanperret** [comment]
Fix is included in https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/1.0.0-beta3 but a round of testing would be nice before closing this.

**Comment by Adrienne200** [comment]
Works now, in Beta 3.
