### ISSUE TITLE
Error flashing the arduino

### ISSUE THREAD

**Issue by mathPi** [AllYarnsAreBeautiful/ayab-desktop#675]
When trying to flash the arduino, I have an error.
In the log I have :

`2024-07-10 20:48:51,026 FirmwareFlash DEBUG    /usr/bin/avrdude -p atmega328p -c arduino -P /dev/ttyACM0 -b115200 -D -Uflash:w:"/home/mathieu/Documents/projects/ayab-desktop/src/main/resources/base/ayab/firmware/ayab_monolithic_uno.hex":i 
2024-07-10 20:48:52,246 FirmwareFlash INFO     Error flashing firmware: CalledProcessError(1, '/usr/bin/avrdude -p atmega328p -c arduino -P /dev/ttyACM0 -b115200 -D -Uflash:w:"/home/mathieu/Documents/projects/ayab-desktop/src/main/resources/base/ayab/firmware/ayab_monolithic_uno.hex":i ')
2024-07-10 20:48:52,246 root     DEBUG    MessageBox error: 'Error flashing firmware.'
`

After checking, this file .hex doesn´t exists, did I miss something ?

**Comment by X-sam** [comment]
Which version are you using?

**Comment by mathPi** [comment]
Hi,
it is the version from the 1.0.0-dev branch.

By the way that´s an other thing but I´m just starting using Ayab: I followed the documentation to install it on ubuntu and thus, as the default git branch is 1.0.0-dev that is the version I installed. It would be great in the documentation to specify the branch the clone or a specific tag to have the latest stable version.

**Comment by X-sam** [comment]
Generally for folks just using the software, I'd advise grabbing the latest
release from the releases page, not building from source- I suspect the
oversight here in our documentation  is that the desktop app repo doesn't
include the firmware files, you'd have to pull them in from the firmware
repo.

**Comment by mathPi** [comment]
Ohhh ok I understand, so the documentation should be updated ? I just followed it.

**Comment by dl1com** [comment]
> Ohhh ok I understand, so the documentation should be updated ? I just followed it.

Yes, thanks for pointing that out. The documentation should be improved to reflect this use case.

**Comment by X-sam** [comment]
closing as addressed
