### ISSUE TITLE
The machine type displayed is not updated when changed in Preferences

### ISSUE THREAD

**Issue by jonathanperret** [AllYarnsAreBeautiful/ayab-desktop#678]
**Environment**
AYAB software version: 1.0.0-dev (bc96d5c3e3f955fa75551ec44c82e966e0981112)
Computer/OS: macOS 14.2

**Describe the bug**
The machine type displayed is not updated when changed in Preferences.

**To Reproduce**
1. Launch AYAB Desktop
2. Click on Preferences/Set Preferences
3. Change the machine type
4. Click OK
5. See that the machine type in the right bar is unchanged

**Expected behavior**
The machine type should be updated.

**Screenshots**

https://github.com/user-attachments/assets/3e00450c-4bf9-4732-9b07-4c275da57120

**Comment by mathPi** [comment]
The issue seems even more important than just the machine name not updated. I think we should trigger a config refresh because the needle number can very when switching machines.

**Comment by jonathanperret** [comment]
> The issue seems even more important than just the machine name not updated. I think we should trigger a config refresh because the needle number can very when switching machines.

This is correct, but the needle count is already being updated when the machine type changes. As far as I can tell, only the machine type displayed fails to be updated.

**Comment by mathPi** [comment]
Ohh I didn't find the needle count update in the code.
