### ISSUE TITLE
milestones reviewen

### ISSUE THREAD

**Issue by niccokunzmann** [AllYarnsAreBeautiful/ayab-desktop#68]
die milestones sind 12. ist das richtig?
Bite schaut auch bei euch nach.

**Comment by andz82** [comment]
Es sind 12 Milestones plus Cleanup Week

1. 24.05. - 30.05
2. 31.05 - 06.06
3. 07.06 - 13.06
4. 14.06 - 20.06
5. 21.06 - 27.06 **-> Midterm Evaluations**
6. 28.06 - 04.07
7. 05.07 - 11.07
8. 12.07 - 18.07
9. 19.07 - 25.07
10. 26.07 - 01.08
11. 02.08 - 08.08
12. 09.08 - 15.08

16.06 - 23.08 **-> Students Submit Code and Student Evaluations (Cleanup, Test and Documentation Week)**
23.08 - 30.08 **-> Final Mentor Evaluations**

Siehe auch: https://summerofcode.withgoogle.com/how-it-works/

**Comment by niccokunzmann** [comment]
habe die letzten Milestones hinzugefügt.
