### ISSUE TITLE
[BUG] The firmware version displayed in the "Load firmware" dialog does not match the version flashed

### ISSUE THREAD

**Issue by jonathanperret** [AllYarnsAreBeautiful/ayab-desktop#688]
**Environment**
AYAB software version: 1.0.0-dev (3bed1bc54e7cd1ef21b5291dfe58612b475b0104)
Computer/OS: macOS 14.5
Knitting machine: —
AYAB hardware: —

**Describe the bug**

When opening the "Load firmware" dialog, a firmware version is displayed:

<img width="673" alt="ayab-load-firmware-version" src="https://github.com/user-attachments/assets/ee2bb607-728c-47ae-a877-54386deccde4">

However, the firmware version that is bundled with the app, and uploaded through this dialog, does not match the version displayed.

**To Reproduce**
1. Launch the AYAB application
2. Click on 'Load Firmware' in the 'Tools' menu
3. Select 'uno' as the controller
4. See that the only firmware version proposed is `0.99.0-rc1`

However, the file that is embedded in this build (found at `Contents/Resources/ayab/firmware/ayab_monolithic_uno.hex` in the application bundle) actually matches the [0.99.0-rc3 firmware release](https://github.com/AllYarnsAreBeautiful/ayab-firmware/releases/tag/0.99.0-rc3)

**Expected behavior**

The version displayed in the dialog should match the firmware that is uploaded.

**Additional context**

There appears to be two places where a firmware version is specified in the code. One is the `manifest.txt` file that is read by the `build-multi-os` workflow to download a firmware release:https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/fb76f4807f1086fd0861ba54a7de00950287c873/src/main/resources/base/ayab/firmware/manifest.txt#L1

The other place is the `firmware.json` file which is read by the "Load firmware" dialog: https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/fb76f4807f1086fd0861ba54a7de00950287c873/src/main/resources/base/ayab/firmware/firmware.json#L1-L11

**Comment by X-sam** [comment]
This isn't so much a bug as an opportunity for DRY-ing up code. Not critical-path for 1.0 release as we'll make sure to put the right version info in both places for that.

**Comment by jonathanperret** [comment]
This is fixed in `1.0.0-beta1` by https://github.com/AllYarnsAreBeautiful/ayab-desktop/commit/ca300aca6b0a0d0c833737852ccc00ea91306d75 setting both locations.

I'm closing this now as it was really about the fact that they were mismatched.
