### ISSUE TITLE
[BUG] Simulation claims to be showing a Lace carriage

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#692]
Simulation mode has no knowledge of the 3 different carriages, it just displays the pattern as given to it. 
Currently it usually (always?) says that it's using a lace carriage "L"
I propose that the carriage type should be removed. 

I'm using:
AYAB software version: 0.99.0-20240725-no-start-delay. (This is an interim build after RC6. Recent changes have no bearing on this behavior)
Computer/OS: Intel Mac, Big Sur 11.7.10

![Simulate claims to show Lace](https://github.com/user-attachments/assets/3632426e-0912-4c96-b799-93f4fbe273a3)

**Comment by jonathanperret** [comment]
🛎 A proposed fix for this is in #738 and can be tested in the release referenced there.
