### ISSUE TITLE
Builds on github actions are slow

### ISSUE THREAD

**Issue by X-sam** [AllYarnsAreBeautiful/ayab-desktop#702]
Apparently we need to update the version of cache action we use.

**Comment by dl1com** [comment]
Missed to merge the PR before triggering the build for 1.0.0-build1 😓  But now it's merged and will be fixed for upcoming builds...

**Comment by jonathanperret** [comment]
> Missed to merge the PR before triggering the build for 1.0.0-build1 😓 But now it's merged and will be fixed for upcoming builds...

No worries! It will make future builds cleaner and that's good.
