### ISSUE TITLE
Adjust branch names

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#703]
Adjust branch names to have a common approach:

* developing on "main"
* cutting a branch for each main release to be able to maintain and backport there

This causes following renaming of branches:

### ayab-desktop

* main -> 0.95-maint
* 1.0.0-dev -> main

### ayab-firmware

* main -> 0.95-maint
* v1.0-dev -> main

anything else?

**Comment by jonathanperret** [comment]
That looks pretty good (and standard) to me.

**Comment by dl1com** [comment]
Addressed in https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/710 and https://github.com/AllYarnsAreBeautiful/ayab-firmware/pull/202

**Comment by dl1com** [comment]
Branches in desktop and firmware have been renamed
