### ISSUE TITLE
Mac build broken

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#704]
While trying to build the 1.0.0-beta1 release, the Mac build failed: https://github.com/AllYarnsAreBeautiful/ayab-desktop/actions/runs/10762969747/job/29844332162#step:14:40

**Comment by jonathanperret** [comment]
Found the culprit hidden in the build log:

> 'delocate-fuse' is no longer available. To fuse two wheels together use 'delocate-merge'. NOTE: 'delocate-merge' does not overwrite the first wheel. It creates a new wheel with an automatically determined name. If the old behavior is needed (not recommended), pin the version to 'delocate==0.11.0'.

Let me have a quick look at `delocate-merge`. If changes are too invasive we can always pin to 0.11.0 as suggested but discouraged.
We should pin the version of `delocate` anyway to avoid this happening again.

**Comment by jonathanperret** [comment]
`delocate-merge` is broken on `numpy` currently: https://github.com/matthew-brett/delocate/issues/227
Pinning to `0.11.0`for now.
