### ISSUE TITLE
fix svg rendering errors

### ISSUE THREAD

**Issue by niccokunzmann** [AllYarnsAreBeautiful/ayab-desktop#71]
- [x] yarn over should be at front, always visible. Therefore you can add a z-index not to the svg but to the instruction definition. SVG-rendering takes care of that, then. This way other instructions can be put into front.
- [x] yarn over should be more to the left so it overlaps
- [x] turn the pattern up-side down and see if the symmetry is right. we start from bottom right

**Comment by kirstin** [comment]
Merged the fix for SVG orientation into master.
