### ISSUE TITLE
[BUG] On Windows, the Beta2 release build crashes on launch.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#720]
AYAB software version: 1.0.0-beta2
Computer/OS: Windows 11
Knitting machine: KH910
AYAB hardware: shield

The Beta2 build of 1.0 installs apparently correctly, launches as expected, then crashes after a few seconds. Beta 1 launched correctly and worked.

Steps:
1. If you have a previous version of AYAB installed, go to Settings - Installed Apps, right-click and Uninstall
2. Go to the Beta2 build on gitHub.com/AllYarnsAreBeautiful/ayab-desktop/releases
3. Download AYAB-1.0.0-beta2.exe. (You may need to go into your browser and allow the download, eg in Edge there's a Keep Anyway button.)
4. Double-click the installer and step through the install.
5. Launch AYAB

Expected: it should launch and run as usual
Actual: it quits after about 3 seconds. 

![AYAB Beta2 crash on launch Screenshot 2024-10-26 153444](https://github.com/user-attachments/assets/567e3d24-b6ea-49be-8031-81102ffb8529)

**Comment by dl1com** [comment]
Tried to reproduce on Win10 22H2, no crash.

**Comment by Adrienne200** [comment]
Not much info in the log file.

But the suggestion to run with no network connection was a good idea, it stays alive and works normally after turning off Wifi.

[ayab_log Beta2 with Wifi.txt](https://github.com/user-attachments/files/17535019/ayab_log.Beta2.with.Wifi.txt)
