### ISSUE TITLE
[BUG] Lower display is blank with edges wider than image

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#733]
AYAB software version: 1.0 Beta3
Computer/OS: Mac
Knitting machine: 930
AYAB hardware: shield

If you set start and stop edges that are wider than the image, and the stop edge is anywhere to the left of needle Right2, it can get into a situation where it is not displaying anything in the lower display, and not updating the upper display, though it is knitting correctly.

1. Start with all settings at default
2. Open test image uc3_3-x15.png
3. Set the edges. to L34 - R2, so the 30st image is centered in 36 stitches
4. Click Simulate, or Knit.
5. If you actually (air)knit it, it does knit in the right place
6. Wait for Simulate to finish, it is actually doing something, you get the ending sounds.

Expected: It should step through and display, with the image centered within its area and 3 squares of white on each side. 
Actual: the lower display is blank, and the upper display doesn't step up. The needle numbers displayed in the lower box are from the last time it worked. It does knit in the right place.

**Comment by jonathanperret** [comment]
🛎 A proposed fix for this is in #737 and can be tested in the release referenced there.
