### ISSUE TITLE
[BUG] Alignment is not correct [KH940 + Alignment left]

### ISSUE THREAD

**Issue by AntjeRumpf** [AllYarnsAreBeautiful/ayab-desktop#743]
**Environment**
AYAB software version: 1.0.0 beta-3
Computer/OS: macOS 15.1.1 (24B91)
Knitting machine: KH-940
AYAB hardware: Shield v1.4TH (Bought this week from RedPinkGreen KoFi)

**Describe the bug**
I installed the dmg-file on my Mac and startet playing around with the software. Opening the "stirnband_160x20.png" pattern from the examples. I only wanted to knit a small part of it so I played around with the settings, till I ended on: Infinity Repeat; Start Needle 18, left; Stop Needle 19, right; Alignment left. 

After knitting a few rows I saw the preview was very different from the knitting on the machine. 

**To Reproduce**
1. Open "stirnband_160x20.png" pattern
2. Set Settings to: 
<img width="244" alt="Bildschirmfoto 2024-12-14 um 17 36 14" src="https://github.com/user-attachments/assets/9fae4869-71cf-4f2f-a2e8-55ab194b95da" />
3. Knit 26 rows
4. Compare preview with knitting

**Expected behavior**
The preview should be the same as the knitting

**Screenshots**
<img width="1512" alt="Bildschirmfoto 2024-12-14 um 17 25 15" src="https://github.com/user-attachments/assets/f3048b7d-e230-4f5b-b639-2405798663f9" />

**Additional context**
I played around with the settings and then I flashed my shield and then I started knitting, don't know if this makes any difference.

**Comment by jonathanperret** [comment]
Hi! Thanks for the report. This may be a duplicate of https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/734 or at least it may have the same cause. 
We fixed that one recently but it has not made it into an official beta release yet.
Can you try this test release https://github.com/jonathanperret/ayab-desktop/releases/tag/1.0.0-20121213 to see if it fixes this issue?

**Comment by jonathanperret** [comment]
1.0.0-beta4 is out now: https://github.com/AllYarnsAreBeautiful/ayab-desktop/releases/tag/1.0.0-beta4

@AntjeRumpf Can you try it to see if your issue is fixed? From a quick attempt I couldn't reproduce it on beta 4, so I'll soon close this unless you report it's still present.

**Comment by AntjeRumpf** [comment]
@jonathanperret it is fixed in the new beta 4. I can close the issue 👍🏻
