### ISSUE TITLE
Create a GUI Mockup

### ISSUE THREAD

**Issue by niccokunzmann** [AllYarnsAreBeautiful/ayab-desktop#91]
It contains:

- Editor
- AYAB printer
- Handknit printer

Also add this to the talk in strickforum.
Maybe use some digital tool.

Also see #67

**Comment by niccokunzmann** [comment]
Editor
=====
![sdc18830](https://cloud.githubusercontent.com/assets/564768/16614374/33c273ae-4371-11e6-900b-be599498efac.JPG)
![sdc18829](https://cloud.githubusercontent.com/assets/564768/16614375/33c5f11e-4371-11e6-93e2-e207b44c1e92.JPG)
![sdc18831](https://cloud.githubusercontent.com/assets/564768/16614376/33c5d9f4-4371-11e6-8b18-e0742759bd52.JPG)

**Comment by chris007de** [comment]
Would be great to have this a bit cleaner, perhaps you could do a quick svg drawing.
Also, I would be interested how you would implement the knitter section (choosing output (hand/ayab), setting ayab parameters)

**Comment by niccokunzmann** [comment]
Am 06.07.2016 um 12:17 schrieb chris007de:
>
> Would be great to have this a bit cleaner, perhaps you could do a
> quick svg drawing.
>
For mockups, if we use this sketchyness, we  get more feedback on the
content. If you have a specific problem with what is there, I can solve it.
An SVG mockup will require several hours and may hinder feedback, so I
will not do it now but later and if I understand that the picture
hinders feedback.
>
> Also, I would be interested how you would implement the knitter
> section (choosing output (hand/ayab), setting ayab parameters)
>
We are currently working on the knitter mockup.

**Comment by niccokunzmann** [comment]
Knitter
=====

![sdc18833](https://cloud.githubusercontent.com/assets/564768/16615239/8613c51e-4375-11e6-9398-a3c41c6e2899.JPG)
![sdc18832](https://cloud.githubusercontent.com/assets/564768/16615240/86140e3e-4375-11e6-9e69-545bbb56c944.JPG)

**Comment by niccokunzmann** [comment]
I added this to the wiki: https://github.com/AllYarnsAreBeautiful/ayab-desktop/wiki/Mockup
We can close it but still discuss the mockups here, in the wiki and in new issues.
